      SUBROUTINE ALLOC
C     This subroutine allocates dynamic arrays on the heap at the start
C     of the run.  It should be called after CRDRD1.
      USE PARM2
      COMMON /DUMB3/  IMXB,JMXB,IMXB1,JMXB1,IMXB2,JMXB2
      IF (ALLOCATED(IMANN)) DEALLOCATE (IMANN)
      ALLOCATE (IMANN(IMXB,JMXB))
      IF (ALLOCATED(ITREE)) DEALLOCATE (ITREE)
      ALLOCATE (ITREE(IMXB,JMXB))
      IF (ALLOCATED(KSKP)) DEALLOCATE (KSKP)
      ALLOCATE (KSKP(IMXB,JMXB))
      IF (ALLOCATED(IHMX)) DEALLOCATE (IHMX)
      ALLOCATE (IHMX(IMXB,JMXB))
      IF (ALLOCATED(HSUB)) DEALLOCATE (HSUB)
      ALLOCATE (HSUB(IMXB,JMXB))
C      ALLOCATE (HMX(IMXB,JMXB))
      RETURN
      END
