      SUBROUTINE ARCHIV
C       ARCHIV SURGE ENVELOP DATA FOR DISPLAY
      USE PARM2
      INCLUDE 'parm.for'
      COMMON /DUMB3/  IMXB,JMXB,IMXB1,JMXB1,IMXB2,JMXB2
      COMMON /IDENT/  AIDENT(40),DACLOK(7)
      COMMON /FLES/ FLE5,FLE9,FLE8,FLE91,FLE99,FLE10,FLE20,FLE30,FLE1
      CHARACTER*256 FLE5,FLE9,FLE8,FLE91,FLE99,FLE10,FLE20,FLE30,FLE1
C        ARCHIVE SURGE ENVELOP TO A FILE
C      OPEN (91,FILE=FLE91,FORM='UNFORMATTED',STATUS='UNKNOWN')
       CALL TOPEN (91,FLE91,1,2)
C       WRITE(91) IMXB,JMXB
C       WRITE(91) AIDENT
       CALL TWRITE (91,IMXB,1)
       CALL TWRITE (91,JMXB,1)
       CALL TWRITEC (91,AIDENT,160)
C          SAVE HMX*10 (10TH A FT ACCURACY) IN INTEGER FORMAT
C       WRITE(91) ((IHMX(I,J),I=1,IMXB),J=1,JMXB)
       DO J=1,JMXB
         DO I=1,IMXB
           CALL TWRITES (91,IHMX(I,J),1)
         END DO
       END DO
C       CLOSE (91)
       CALL TCLOSE (91)
C
       RETURN
       END
