      SUBROUTINE CASENAME(CSNM,TRK,AS1,BSNN,AS5,LENCS)
C     D.Y 11/2017
C     GIVEN INPUT STRING STRIN AND ITS LENGTH LENIN, RETURN A NEW STRING
C     STRING OUT WITH 'UN-EFFECTIVE' CHARACTERS REMOVED, ALSO RETURNED IS
C     THE NUMBER OF 'EFFECTIVE' CHARACTERS IN THE INPUT STRING
C     EFFECTIVE CHARACTERS INCLUDE LETTERS IN UPPER/LOWER CASE, NUMBERS
C     FROM 0 TO 9, AND SYMBOLS './_-'

      IMPLICIT NONE

      INTEGER LENCS
      INTEGER AS1,AS5
      CHARACTER(LEN=80)CSNM
      CHARACTER(LEN=AS1),INTENT(IN):: TRK
      CHARACTER(LEN=AS5),INTENT(IN):: BSNN
      INTEGER C,I,TRKB,TRKE,BSNB,BSNE
      INTEGER SIDX1,SIDX2,SIDX3
      CHARACTER(26),PARAMETER :: CAP='ABCDEFGHIJKLMNOPQRSTUVWXYZ'
      CHARACTER(26),PARAMETER :: LOW='abcdefghijklmnopqrstuvwxyz'
      CHARACTER(26),PARAMETER :: NUM='0123456789./_-:~'

      ! GET LENGTH OF TRACK FILENAME
      TRKB=1
      DO I=1,AS1
        IF (TRK(I:I)=='/')TRKB=I+1
      ENDDO
      TRKE=MAX(INDEX(TRK,'.trk'),INDEX(TRK,'.TRK'))-1

      ! GET LENGTH OF BASIN ABBREVIATION
      C=0
      DO I=1,4
        SIDX1=INDEX(CAP,BSNN(I:I))
        SIDX2=INDEX(LOW,BSNN(I:I))
        SIDX3=INDEX(NUM,BSNN(I:I))
        IF (((SIDX1.GE.1).AND.(SIDX1.LE.26)).OR.
     1      ((SIDX2.GE.1).AND.(SIDX2.LE.26)).OR.
     1      ((SIDX3.GE.1).AND.(SIDX3.LE.16)))THEN
          C=C+1
        ENDIF
      ENDDO
      IF (C .EQ. 3)THEN
        BSNB=2
        BSNE=4
      ELSE IF (C .EQ. 4)THEN
        BSNB=1
        BSNE=4
      ELSE
        PRINT *, 'WRONG BASIN ABREV LENGTH, SHOULD BE 3 OR 4'
        STOP
      ENDIF

      ! GET CASENAME AND ITS LENGTH
      CSNM=BSNN(BSNB:BSNE)//'_'//TRK(TRKB:TRKE)//'_'
      LENCS=C+TRKE-TRKB+3

      RETURN
      END
