      SUBROUTINE CLNUP (HHB, iENV)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C THIS SUBROUTINE CALLS THE FORTRAN SUBROUTINES NEEDED TO SAVE THE
C MAX ENVELOP, AND TO CLEAN UP EXECUTION OF THE CODE.
C
C ORIGINALLY THIS WAS DONE AT THE END OF CMPUTE (AFTER 999) AND AT THE
C END OF PROGRAM MAIN.
C THE CODE IS THE SAME EXCEPT CUT AND PASTED HERE.
C
C THIS ALSO RETURNS TO C THE VARIOUS VARIABLES NEEDED SO THAT
C IT CAN DISPLAY THE MAX ENVELOP.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      include "parm.for"
      REAL HHB(M_,N_)
      COMMON /FFTH/   ITIME, MHALT
      COMMON /KEYS/ KEY1
      COMMON /FLES/ FLE5,FLE9,FLE8,FLE91,FLE99,FLE10,FLE20,FLE30,FLE1
      CHARACTER*256 FLE5,FLE9,FLE8,FLE91,FLE99,FLE10,FLE20,FLE30,FLE1
      COMMON /DUMB3/  IMXB,JMXB,IMXB1,JMXB1,IMXB2,JMXB2

C FINISHING UP THE CMPUTE CODE
CC      write (*,*)'   finished at time step=',itime
CC      write (*,*)'   mhalt=' ,mhalt
c      CALL FILTRP
      CALL FHMXSV
      if (ienv.eq.1) CALL ARCHIV

c       CALL PLOTS1
C
C      CALL GETDAT(MYR,MMON,MDAY)
C      CALL GETTIM(MHR,MMIN,MSEC,MI100)
C
C      WRITE(*,100) MMON,MDAY,MYR,MHR,MMIN,MSEC,MI100
C 100  FORMAT(1H0,'         CALCULATIONS ENDED AT DAY - TIME ',
C    1   2(I2.2,':'),I4.4,'--',2(I2.2,':'),I2.2,'.',I2.2//)

C CODE TO RETURN VALUES TO C-CODE.
      DO J=1,JMXB
         DO I=1,IMXB
            HHB(I,J)=HMX(I,J)
         END DO
      END DO
      RETURN
      END
