       SUBROUTINE CNSTNT
C        JELESNIANSKI    SEPTEMBER 1980 TDL   IBM 360/195
C
C        PURPOSE
C           THIS SUBROUTINE (CNSTNT) FIXES SOME PROGRAM CONSTANTS.
C
C        DATA SET USE
C           NONE
C
C        VARIABLES
C            X1(50) = STORED ARRAY OF CONSTANTS
C              DELT = TIME INCRMNT FOR FINITE DIFFRNCNG, SET IN 'INTDLT'
C               COR = CORIOLIS (1/SEC), (SET IN 'INTVAL')
C         IMXB JMXB = NO. OF GRID PTS ALONG A RAY/CIRCLE, IN 'CRDRD1'
C       IMXB1 JMXB1 = IMXB LESS 1, JMXB LESS 1
C       IMXB2 JMXB2 = IMXB LESS 2, JMXB LESS 2
C            DEGREE = ANGLE BETWEEN TWO RAYS, READ IN 'CRDRRD1'
C              DELA = VALUE OF 'DEGREE' IN RADIANS
C               RAD = RADIAN MEASURE
C           X1B(10) = STORED ARRAY OF CONSTANTS
C                 G = GRAVITY = 32.2 FT/SEC-2
C       AMAN->AGB13 = FIXED CONSTANT FOR SUBROUTINE 'CHANNL'
C
C        GENERAL COMMENTS
C           THIS SUBROUTINE IS CALLED BY SUBROUTINES INITLZ AND STMVAL.
C
C      COMMON /SLAT/   FSOUTH
      COMMON /FRST/   X1(50),X12(50)
      COMMON /EGTH/   DELS,DELT,G,COR
      COMMON /DUMB3/  IMXB,JMXB,IMXB1,JMXB1,IMXB2,JMXB2
      COMMON /POLAR/  DEGREE,RMOUTH,AZMTH,DELA
      COMMON /GAMAF/  GAMA,GAMA1,GAMFP(4)
      COMMON /DUMB4/  X1B(10)
      COMMON /DUMB4I/ CORL(90)
      COMMON /CHNLNO/ AMAN,BMAN,GB,AGB,AGB13
      X1B(1)=G*DELT/DELA
      X1B(2)=DELT/DELA
C
      X1B(4)=DELT*COR
      DO 10 L=1,90
      CORL(L)=2.*(7.292116E-5)*SIN((L-1)*1.74532925199433E-2)/COR
 10   CONTINUE
C
C        FSOHTH=-1. FOR SOUTHERN HEMISPHERE, NEGATIVE CORIOLIS PARAMETER
C              = 1. FOR NORTHERN HEMISPHERE,
C      X1B(4)=DELT*COR*FSOUTH
C
      X1B(5)=.5*X1B(2)
      X1B(6)=.5*X1B(1)
C        WEIR COEFFICIENT
      X1B(7)=.6*DELT*SQRT(2.*G/3.)/3.
C        SET SMOOTHING CONSTSNTS FOR POLAR COORDINATES
      EXPDLA=EXP(DELA)
      COSHLA=.5*(EXPDLA+1./EXPDLA)
      GAMA =EXPDLA/COSHLA-1.
      GAMA1=-GAMA
      GAMFP(1)=0.
      GAMFP(3)=0.
      GAMFP(2)=GAMA
      GAMFP(4)=GAMA1
C         COMPUTING FIXED CONSTANTS FOR SUBROUTINE 'CHANNL'
      CMAN =1.5/.03
      AMAN =3.*(CMAN**2)/13.
      BMAN =3.*(CMAN**2)/(4.*G)
      GB   =G*BMAN
      AGB  =AMAN-G*BMAN
      AGB13=13.*AGB/3.
      RETURN
       END
