       SUBROUTINE CONTTY
C        JELESNIANSKI     SEPTEMBER 198TDL   IBM 360/195
C
C        PURPOSE
C           THIS SUBROUTINE (CONTTY) IS AN ALGORITHM FOR THE CONTINUITY
C           EQUATION, FOR AN IMAGE PLANE; POLAR COORDINATES ARE
C           TRANSFORMED ONTO THE IMAGE PLANE. THE SYSTEM AXIS ARE
C           (P,Q), BUT THE SUBROUTINE USES (I,J) FOR INTEGER SBSCRPTNG
C           TWO LEVELS IN TIME (FORWARD IN CONTTY PLUS BACKWARD IN MOMN)
C           ARE USED. THE GRID (SEE DIAGRAM BELOW) IS STAGGERED IN SPACE
C           A 5-POINT SCHEME (4 CORNERS OF A SQUARE) ARE USED FOR
C           THE MOMENTUM SPACE GRADIENT.
C
C              .****.****.         WHEN WATER DESCENDS BELOW SQUARE
C              *I-1 * I  *         (I,J), THE MOMENTUM ON 4-SURROUNDNG
C              * +  * +  *         CORNERS ARE REDUCED TO ALLOW THE
C              * J  * J  *         SQUARE TO BECOME DRY.  THE
C              .****.****.****.    PREVIOUSLY COMPUTED SURGES ON THE
C              *I-1 * I  *I+1 *    4-SURROUNDING SQUARES ARE UPDATED
C              * +  * +  * +  *    ACCORDING TO THE REVISED MOMENTUMS
C              *J-1 *J-1 *J-1 *    ON THE 4-CORNER POINTS OF (I,J).
C              .****.****.****.    SEE DIAGRAM BELOW FOR SUBSCRIPTING.
C
C        DATA SET USE
C
C        VARIABLES
C       IMXB1 JMXB1 = MAX SUBSCRIPTS FOR SURGE SQUARES
C        HB(  ,   ) = SURGE HEIGHTS
C       HSUB(  ,  ) = STORAGE FOR A SECOND COPY OF HB
C            IS(  ) = START LOOP, EXCLUDE HI TERRAIN, SET IN 'CRDRD2'
C            IB IFN = BEGINNING/ENDING A 'DO LOOP' IN I-DIRECTION
C             ISKIP = 1,FOR J=1,CHECK ZBM AT 2 BNDRY CORNERS FOR SKIPPIN
C                       STAATIC CONDITION.
C                     2,AND I=IMXB1 FOR BOTTOM BOUNDARY
C                     3,FOR J=JMXB1 FOR RIGHT BOUNDARY
C              JUMP = CONDITIONAL INTEGER FOR STANDARD LOOP,
C                     OR RETRIEVAL OF PREVIOUSLY COMPUTED SURGES,
C                     SEE DIAGRAM ABOVE FOR AFFECTED SQUARES
C              LEAP = CONDITIONAL 'GO TO' TO DRY AN (I,J) SQUARE,
C                     SEE DIAGRAM ABOVE FOR AN (I,J) SQUARE
C         IFST ISND = BEGIN/END I SUBSCRIPT ON UPDATED (J-1) SQUARES
C             IPASS = CONDITIONAL INTEGER, TO SET A SQUARE DRY
C         ZB(  ,  ) = DEPTHS AT CENTER OF SURGE SQUARES
C       IP(4) JP(4) = SHIFT SUBSCRIPTS TO 4 MOMENTUM POINTS
C     UB VB(  ,   ) = COMPONENTS OF MOMENTUM FIELDS
C              HPST = DUMMY VALUE FOR SUEGE VALUEC
C           DUX DVY = COMPONENTS OF MOMENTUM GRADIENT
C               FCT = FACTOR TO MULTIPLY MOMENTUM GRADIENT
C              CHNG = SURGE PLUS DEPTHS (TO TEST FOR DRY SQUARE)
C              DENM = CHANGE IN SURGE, ONE TIME ITERATION
C              ANUM = CHANGE IN SURGE HT, TO TO DRY A SQUARE
C              RFCT = RATIO, <1, OF ANUM TO DENM, REDUCTION FACTOR
C              ISET = I-SUBSCRIPT FOR DRIED SQUARE
C
C        GENERAL COMMENTS
C           THIS SUBROUTINE RESIDES IN OVERLAY 'CMPUTE'. IT IS CALLED
C           IN BY SUBROUTINE 'CMPUTE'
C           THE SYSTEM ROUTINE 'ERRSET' IS USED TO ISOLATE VARIABLES
C           IF AN UNDER/OVERFLOW OCCURS; VARIABLE PRINT OUT IS
C           AIDED VIA 'HELP' AND THE 'COMMON/CHELP/'.
C
C           THE SUBSCRIPT FOR COMPUTATIONS OF SURGES ARE OFFSET (.5,.5)
C           FROM THE MOMENTUM POINTS. SEE BELOW:
C
C             (I,J)       (I,J+1)
C              .         .
C                                  .=MOMENTUM POINTS (UB,VB)
C                                  +=SURGE    POINTS (HB)
C                 (I,J)
C                   +
C                                  .=BARRIER  POINTS (ZBM)
C                                  +=DEPTH    POINTS (ZB)
C
C              .         .            IP(4)=0,1,1,0 JP(4)=0,0,1,1
C             (I+1,J)   (I+1,J+1)
C
      USE PARM2
      INCLUDE 'parm.for'
C
      COMMON /DUMB3/  IMXB,JMXB,IMXB1,JMXB1,IMXB2,JMXB2
      COMMON /DUMB8/  IP(4),JP(4),IH(4),JH(4)
      COMMON /DUM88/  IIH(4),JJH(4),IHH(4),JHH(4)
      COMMON /DUMB4/  X1B(10)
      COMMON /CHELP/  ANUM,DENM,RFCT,I,J,HBJ,HPST,UP(4),VP(4)
C
C        PRODUCE A DUPLICATE COPY OF HB(,) IN CASE WATER DECEND BELOW
C        GROUND.
      DO 100 J=1,JMXB
      DO 100 I=1,IMXB1
 100  HSUB(I,J)=HB(I,J)
C        SET UB,VB TO LOWER BOUNDS OR ZEROS TO AVOID UNDERFLOW.
      DO 110 J=2,JMXB1
      DO 110 I=2,IMXB1
      IF(ABS(UB(I,J)).GT.1.E-10) GO TO 110
      UB(I,J)=0.
      VB(I,J)=0.
 110  CONTINUE
C
C         SET PARAMETERS FOR J=1
C
      J=1
      IB=IS(J)
      IFN=IE(J)
      JUMP=4
      LEAP=1
      GO TO 130
C
C        BEGINING LOOP WHEN J DECENDS BY ONE FOR DRYING OF A SQUARE
C
 120  IB=IFST
      IFN=ISND
C
C        BEGINING OF REGULAR J LOOP FROM 1 THRU JMXB1
C
 130  CONTINUE
      IF (IFN.LT.IB) GOTO 330
      DO 320 I=IB,IFN
C
      IF (KSKP(I,J).EQ.'0') GOTO 320
C       LEAP=1, REGILAR CASE. LEAP=2, RETURN TO THE SQUARE BEING DRIED.
C
      GO TO (170,160),LEAP
 160  IF(I.NE.IPASS) GO TO 170
      HB(I,J)=-ZB(I,J)
      LEAP=1
      GO TO 320
C
 170  CONTINUE
C
C        BYPASS CHECKINGS FOR DEPTH >30 FT, OR TERRAIN >  35 FT.
C
      DUX=-UB(I,J)+UB(I+1,J)+UB(I+1,J+1)-UB(I,J+1)
C
C        TEST FOR DEPTH > 30 FT
      IF(ZB(I,J).GT.30.) GO TO 210
C
C        TEST FOR DRY SQUARES, IF U'S AT 4 CORNERS ARE 0., OR DUX=0.
C        IN EQUIVALENCE.
      IF (DUX.EQ.0.) GO TO 320
C
C        CONTINUITY EQUATION.
 210  HPST=HSUB(I,J)
      Z=ELPDL2(I)+(ELPCL2(I)-ELPDL2(I))*SINL2(J)
      FCT=X1B(5)/Z
      DVY=-VB(I,J)-VB(I+1,J)+VB(I+1,J+1)+VB(I,J+1)
      HBJ=HPST-FCT*(DUX+DVY)
C
C        TEST IF SURGE IS BELOW DRY LAND, IF SO, SET SURGE TO LAND HGT.
C        REVISE SURROUNDING TRANSPORTS TO GIVE ZERO TOTAL DEPTH.
C
      CHNG=HBJ+ZB(I,J)
      IF (CHNG.GE.0.) GO TO 220
CCCCCC     MODIFICATION 10/27/99  RE-TESTED by Pro Fortran 09/20/01
      IF (-CHNG.LT.1E-3) THEN
      HB(I,J)=-ZB(I,J)
      GOTO 320
      ENDIF
CCCCCC
      GO TO 230
 220  HB(I,J)=HBJ
      GO TO 320
C**********END OF LOOP FOR REGULAR RETURN*******************************
C
C***********************************************************************
C
C        READJUST TRANSPORTS TO ACCOUNT SUQARES DECENDING BELOW TERRAIN.
C
 230  CONTINUE
      IF (HSUB(I,J).EQ.-ZB(I,J)) GO TO 320
      DENM=HBJ-HPST
      DENM=SIGN(AMAX1(1.E-5,ABS(DENM)),DENM)
 240  ANUM=-ZB(I,J)-HPST
      RFCT=ANUM/DENM
 250  IF (RFCT.LT.0.) GO TO 260
C        RFCT SHOULD NORMALLY BE POSITIVE.
      IF (ABS(RFCT).LT.1.) GO TO 290
 260  CONTINUE
CC      WRITE(*,270)I,J,ZB(I,J),HPST,HBJ
CC      WRITE(*,280)RFCT,ANUM,DENM
 270  FORMAT (2I5,3F15.10)
 280  FORMAT (3F20.10)
 290  IF(ABS(RFCT).LT.1.E-5) RFCT=0.
      DO 300 K=1,4
      IA=I+IP(K)
      JA=J+JP(K)
      UB(IA,JA)=RFCT*UB(IA,JA)
      VB(IA,JA)=RFCT*VB(IA,JA)
 300  CONTINUE
C        RECOMPUTE 3 SQUARES ON J-1 LINE
      J=J-1
      JUMP=1
      ISET=I
      LEAP=1
      IF (J.EQ.0) GO TO 330
      IF (KSKP(I,J).EQ.'0') GOTO 330
 310  IF (IS(J).GT.I) GO TO 330
      IFST=MAX0(I-1,IS(J))
      ISND=MIN0(I+1,IE(J))
      GO TO 120
 320  CONTINUE
 330  CONTINUE
C        INCREMENT J, OR CONTINUE ON OLD J LINE
      JUMP=JUMP+1
      LEAP=1
C        TEST FOR INCREMENTED OR OLD J
      IF (JUMP.NE.2) GO TO 340
C        OLD J LINE, WITH 2 OLD SQUARES TO BE UPDATED
      J=J+1
      LEAP=2
      IB=MAX0(ISET-1,IS(J))
      IFN=IE(J)
      IPASS=ISET
      GO TO 130
C        INCREMENT J FOR NEW COMPUTATION LINE
 340  J=J+1
      IF (J.GT.JMXB1) GO TO 350
      IB=IS(J)
      IFN=IE(J)
      GO TO 130
C
C***********  RETURN WITH A NEW J-LINE  **********************
C
 350  CONTINUE
      DO 360 I=1,IMXB1
 360  HB(I,JMXB)=HB(I,1)
C
      RETURN
       END
