      SUBROUTINE DEPSFC
C        JELESNIANSKI    SEPTEMBER 1980 TDL   IBM 360/195
C
C        PURPOSE
C           THIS SUBROUTINE (DEPSFC) INITIALIZES INLAND SURFACE WATERS
C           TO LAKE DATUM (SEA WATER TO SEA DATUM IS DONE IN SUBROUTINE
C           'INILHT'). BARRIERS AND THEIR HEIGHTS ARE PLACED AT
C           SELECTED MOMENTUM GRID POINTS. FOR 1-DIM FLOW, DEPTHS AND
C           LATERAL BOUNDARIES ARE SET. BOUNDARIES ARE TEMPORARILY
C           SET AS A 100 FOOT WALL. PRINT OUTS ARE MADE OF THE DEPTH
C           FIELD, AND HIGHEST LAND VALUE AT MOMENTUM GRID POINTS
C           ARE SET.
C
C        DATA SET USE
C           NONE
C
C        VARIABLES
C         IMXB JMXB = TOTAL GRID SPACINGS, SET IN 'CRDRD1'
C       IMXB1 JMXB1 = IMXB LESS 1, JMXB LESS 1
C            DOLLAR = '$' FOR ISLAND, OTHERWISE FOR REGULAR BASIN
C         ZB(  ,  ) = BATHY/TOPO HEIGHTS,    RELATIVE TO NGVD
C        ZBM(  ,  ) = HIGHEST ELEVATION AT A MOMENTUM POINT
C                     OR, VALUES INDICATING BOUNDARY TYPES
C             NSQRW = NUMBER OF SQUARES WITH 1-DIM FLOW
C    ISQR JSQR(   ) = SUBSCRIPTS FOR SQUARES WITH 1-DIM FLOW
C        ISIDE(   ) = THE SIDE OF A SQUARE TO PASS 1-DIM FLOW
C     IIH(4) JJH(4) = SHIFT SUBSCRIPTS TO 4 MOMENTUM POINTS ON A SQUARE
C        HWEIR(   ) = LOWEST BARRIER ELEVATION AT ISIDE(   )
C     IZ1(4) IZ2(4) = SET P SUBSCRIPTS ON 4 SIDES OF ISIDE(   )
C     JZ1(4) JZ2(4) = SET Q SUBSCRIPTS ON 4 SIDES OF ISIDE(   )
C        ZBMIN(   ) = LOWEST DEPTH OF TWO SQUARES BOUNDING ISIDE(30
C              MGPT = TOTAL NUMBER OF MANGROVE PTS
C     IMG( ) JMG( ) = I/J COORDINATES OF MANGROVE PTS
C      ITREE(  ,  ) = 0 FOR NO TREE, 1 FOR TREE ON A GRID POINT
C
C        GENERAL COMMENTS
C           THIS SUBROUTINE RESIDES IN OVERLAY 'INITLZ'. IT IS
C           CALLED IN SUBROUTINE 'INITLZ'.
C
      INCLUDE 'parm.for'
C
      PARAMETER (NBCPTS=12000)
      common /opts/   nofld,nof1d
      character*1     nofld,nof1d
      COMMON /DUMB3/  IMXB,JMXB,IMXB1,JMXB1,IMXB2,JMXB2
      COMMON /DUMB8/  IP(4),JP(4),IH(4),JH(4)
      COMMON /DUM88/  IIH(4),JJH(4),IHH(4),JHH(4)
      COMMON /BSN/    PHI,ALTO,ALNO,PHI1,ALT1,ALN1,ALT1C
      PARAMETER (NT_=999)
      COMMON /SPLN/   ALT(15),ALN(15),AX(15),AY(15),RL(15),ANGD(15),
     1                PT(15),RT(15),XLAT(NT_),YLONG(NT_),RLNGTH
      COMMON /BCPTS/  TIDESH(NBCPTS),NBCPT,ISH(NBCPTS),JSH(NBCPTS)
      COMMON /FLWCPT/ NSQRS,NSQRW,NSQRWC,NPSS,NCUT
      COMMON /SWTCH/  IOPERL(5)
      COMMON /GPRT1/  DOLLAR,EBSN
      COMMON /HTERAIN/ HTER
!-------------------------------------------------------
! Added Basin Name Variable by Huiqing.Liu/MDL June/2015
! for Modifying Cd wind drag coefficient parameter only
! in New Bering Sea extra-tropical basin (ENO3)
!-------------------------------------------------------
      COMMON /GPRT/   STA
      CHARACTER*16  STA
      CHARACTER*2     DOLLAR
      CHARACTER*1     EBSN
      DIMENSION IZ1(4),IZ2(4),JZ1(4),JZ2(4)
      DATA IZ1/0,1,0,0/,  IZ2/0,1,1,1/, JZ1/1,1,0,1/, JZ2/0,0,0,1/
C
      DO 401 J=2,JMXB
      DO 401 I=2,IMXB
      ZMX=AMAX1(-ZB(I-1,J-1),-ZB(I,J-1),-ZB(I-1,J),-ZB(I,J))
      IF (ZMX.LT.-1499.) ITREE(I,J)='6'
c     IF (ZMX.LE.-799.) ITREE(I,J)='6'
 401  CONTINUE
C     IF (DOLLAR.EQ.'$') THEN
C     DO I=2,IMXB
C     ZMX=AMAX1(-ZB(I-1,JMXB),-ZB(I,JMXB),-ZB(I-1,1),-ZB(I,1))
C     IF (ZMX.LE.-289.) ITREE(I,1)='6'
C     ENDDO
C     ENDIF
C
C      DETERMINE THE ACTIVE/NONACTIVE SQUARES FOR HEIGHT COMPUTATIONS
      DO 400 J=1,JMXB1
      DO 400 I=1,IMXB1
C     CHANGED BY NSM TO -HTER FROM -35 11/20/2010 : Accepted 4/4/2011
      IF (ZB(I,J).GT.-HTER) THEN
        KSKP(I,J)='1'
        KCT=1
C       SPECIAL TRUNCATED SQUARES IN DEEP OCEAN
        IF (ITREE(I,J).EQ.'6') KCT=KCT+1
        IF (ITREE(I+1,J).EQ.'6') KCT=KCT+1
        IF (ITREE(I,J+1).EQ.'6') KCT=KCT+1
        IF (ITREE(I+1,J+1).EQ.'6') KCT=KCT+1
        IF(KCT.NE.1.AND.KCT.LT.5) THEN
          KSKP(I,J)='2'
        ELSE IF(KCT.EQ.5) THEN
          ZB(I,J)=-67.
          KSKP(I,J)='0'
        ENDIF
      ELSE
        KSKP(I,J)='0'
      ENDIF
 400  CONTINUE
      DO 421 J=1,JMXB
 421  KSKP(IMXB,J)='0'
      DO 420 I=1,IMXB
 420  KSKP(I,JMXB)=KSKP(I,1)
C
C     WRITE(*,3334)
C     DO 3333 JJ=2,JMXB
C     J=JMXB-JJ+1
C     WRITE (*,3332) J,(KSKP(I,J),I=1,IMXB1)
C3332 FORMAT(1X,I3,1X,126A1)
C3333 CONTINUE
C     WRITE(*,3334)
C 3334 FORMAT(/5X,12('1234567890')/)
C
C        ISOLATE HIGHEST LAND SQUARE ABOUT A TRANSPORT POINT
C        FOR ISLAND ZB( ,JMXB)=ZB( ,1)
      J2=JMXB1
      IF (DOLLAR.EQ.'$')  J2=JMXB
      DO 130 I=2,IMXB
      DO 130 J=2,J2
      ZMX=AMAX1(-ZB(I-1,J-1),-ZB(I,J-1),-ZB(I-1,J),-ZB(I,J))
      IF (ZBM(I,J).LT.ZMX) THEN
        IF (ZBM(I,J).NE.-300.) THEN
          WRITE(*,120)I,J,ZBM(I,J)
 120  FORMAT ('   ERROR IN BARRIER HEIGHT AT POSITION I=',I5,' J=',I5,
     1 '  HW=',F5.0)
        ENDIF
        ZBM(I,J)=ZMX
      ENDIF
 130  CONTINUE
      IF (DOLLAR.EQ.'$') THEN
        DO 132 I=1,IMXB
        ZBM(I,1)=ZBM(I,JMXB)
 132    CONTINUE
      ENDIF
C
      DO 1401 J=2,JMXB
      DO 1401 I=2,IMXB
      IF (ITREE(I,J).EQ.'5'.AND.ZBM(I,J).GE.-15.) ITREE(I,J)='3'
C     ADDED BY AAT 4/8/2011 : This should cause what used to be high
C     terrain (> 35 feet) that was marked with a '4' to have friction
C     winds and be able to be inundated.
      IF (HTER.GT.35.) THEN
        IF (ITREE(I,J).EQ.'4'.AND.ZBM(I,J).LT.HTER) ITREE(I,J)='1'
      ENDIF
 1401 CONTINUE
C
C        IF ZBM GREATER THAN 35 FT IN INTERIOR POINTS, MOMENTUM PTS
C        ARE NONACTIVE.
      DO 40 J=2,J2
      DO 40 I=2,IMXB1
C     CHANGED BY NSM TO HTER FROM 35 11/20/2010 : Accepted 4/4/2011
      IF (ZBM(I,J).GE.HTER) ITREE(I,J)='4'
      IF (ITREE(I,J).EQ.'5') ITREE(I,J)='2'
 40   CONTINUE
C
C       REDEFINE MS(J). FOR EACH J, FIRST I THE COMPUTATION
C       STARTS IN MOMNTM (ZBM LESS THAN 35 FT).
      DO 50 J=2,JMXB
      MS(J)=1
      DO 60 I=1,IMXB
C    CHANGED BY NSM TO HTER FROM 35 11/20/2010 : Accepted 4/4/2011
      IF (ZBM(I,J).LT.HTER) GO TO 55
 60   CONTINUE
      I=I-1
 55   MS(J)=I
 50   CONTINUE
      IF (DOLLAR.EQ.'$') THEN
        MS(1)=MS(JMXB)
      ELSE
        MS(1)=MS(2)
      ENDIF
c
C       DEFINE IS(J). FOR EACH J, FIRST I THE COMPUTATION
C       STARTS IN CONTINUITY.
      DO 10 J=1,JMXB1
      IS(J)=1
      DO 20 I=1,IMXB1
      IF (KSKP(I,J).EQ.'1') GO TO 15
 20   CONTINUE
      I=I-1
 15   IS(J)=I
 10   CONTINUE
      IF (DOLLAR.EQ.'$')THEN
        IS(JMXB)=IS(1)
      ELSE
        IS(JMXB)=IS(JMXB1)
      ENDIF
C
C        DEFINE LOWER LIMIT OF I FOR MOMENTUM POINTS
      DO 450 J=2,JMXB1
      ME(J)=IMXB
      DO 460 II=2,IMXB1
      I=IMXB-II+1
C    CHANGED BY NSM TO HTER FROM 35 11/20/2010 : Accepted 4/4/2011
      IF (ZBM(I,J).GE.HTER) CYCLE
      IF (ITREE(I,J).NE.'6') GO TO 455
 460  CONTINUE
      I=I+1
 455  ME(J)=I
 450  CONTINUE
      ME(1)=IMXB1
      ME(JMXB)=IMXB1
C        DEFINE LOWER LIMIT OF I FOR CONTTY POINTS
C
      DO 610 J=1,JMXB1
      IE(J)=IMXB1
      DO 620 II=1,IMXB1
      I=IMXB1-II+1
      IF (KSKP(I,J).EQ.'1') GO TO 615
 620  CONTINUE
      I=I+1
 615  IE(J)=I
 610  CONTINUE
      IE(JMXB)=IE(1)
C     PRINT 1111,(IS(J),J=1,JMXB)
C     PRINT 1111,(MS(J),J=1,JMXB)
C 1111 FORMAT(1X,15I3)
C     PRINT 1111,(IE(J),J=1,JMXB)
C     PRINT 1111,(ME(J),J=1,JMXB)
C
C
      DO 42 J=2,JMXB
      MF(J)=IMXB
      DO 45 II=1,IMXB1
      I=IMXB-II
      IF (ITREE(I,J).EQ.'1'.OR.ITREE(I,J).EQ.'3') EXIT
 45   CONTINUE
      MF(J)=I
 42   CONTINUE
      IF (DOLLAR.EQ.'$') THEN
        MF(1)=MF(JMXB)
      ELSE
        MF(1)=MF(2)
      ENDIF
C     IF NO BANKS, THEN SET BANK HEIGHTS TO BARRIER HEIGHT
      IF (NSQRWC.NE.0) THEN
        DO 200 L=1,NSQRWC
        IF (BANK(L,1).EQ.0.) THEN
          I=ISQR(L)
          J=JSQR(L)
!          IF (I.LE.0.OR.J.LE.0.OR.I.GE.IMXB.OR.J.GE.JMXB) CYCLE
          BANK(L,1)=AMIN1(ZBM(I,J),ZBM(I,J+1),ZBM(I+1,J),ZBM(I+1,J+1))
        ENDIF
        IF (BANK(L,2).NE.0.) CYCLE
        K=ISIDE(L)
        I=ISQR(L)+IHH(K)
        J=JSQR(L)+JHH(K)
!        IF (I.LE.0.OR.J.LE.0.OR.I.GE.IMXB.OR.J.GE.JMXB) CYCLE
        BANK(L,2)=AMIN1(ZBM(I,J),ZBM(I,J+1),ZBM(I+1,J),ZBM(I+1,J+1))
 200    CONTINUE
C
C        SET UP DEPTHS AND SIDE HEIGHTS FOR 1-DIM FLOW AND RIVER BANKS
C        SET UP SPECIAL RAISED WEIRS OR SILLS FOR 1-DIM FLOW
C        AND ZBMIN FOR FLOW CUTS IN SUBROUTINE CRDRD2.
        IF (NSQRW.NE.NSQRS) THEN
          N1=NSQRS+1
          DO 232 L=N1,NSQRW
          I=ISQR(L)
          J=JSQR(L)
!          IF (I.LE.0.OR.J.LE.0.OR.I.GE.IMXB.OR.J.GE.JMXB) CYCLE
          K=ISIDE(L)
          I1=I+IZ1(K)
          I2=I+IZ2(K)
          J1=J+JZ1(K)
          J2=J+JZ2(K)
          IF (HWEIR(L).EQ.0.) HWEIR(L)=AMIN1(ZBM(I1,J1),ZBM(I2,J2))
 232      CONTINUE
          DO 1232 N=N1,NSQRW
          I=ISQR(N)
          J=JSQR(N)
!          IF (I.LE.0.OR.J.LE.0.OR.I.GE.IMXB.OR.J.GE.JMXB) CYCLE
          K=ISIDE(N)
          I1=I+IZ1(K)
          I2=I+IZ2(K)
          J1=J+JZ1(K)
          J2=J+JZ2(K)
          ITREE(I1,J1)='Q'
          ITREE(I2,J2)='Q'
 1232     CONTINUE
        ENDIF
        DO 3222 J=2,JMXB1
        DO 3222 I=2,IMXB1
        IF (ITREE(I,J).EQ.'Q') THEN
C     COMMENTED BY NSM 11/20/2010 : Should it be HTER or HTER + 1?
C      ZBM(I,J)=36.
          ZBM(I,J)=HTER+1
          ITREE(I,J)='4'
        ENDIF
 3222   CONTINUE
        DO 240 L=1,NSQRWC
        I=ISQR(L)
        J=JSQR(L)
!        IF (I.LE.0.OR.J.LE.0.OR.I.GE.IMXB.OR.J.GE.JMXB) CYCLE
        ZINT=-ZB(I,J)
        K=ISIDE(L)
        II=I+IHH(K)
        JJ=J+JHH(K)
!        IF (II.LE.0.OR.JJ.LE.0.OR.II.GE.IMXB.OR.JJ.GE.JMXB) CYCLE
        ZEXT=-ZB(II,JJ)
C      FOR WEIR HEIGHTS NOT A SILL
        IF (HWEIR(L).EQ.0.) THEN
          HWEIR(L)=AMAX1(ZINT,ZEXT)
        ENDIF
        I1=I+IZ1(K)
        I2=I+IZ2(K)
        J1=J+JZ1(K)
        J2=J+JZ2(K)
!        IF (I1.LE.0.OR.J1.LE.0.OR.I1.GE.IMXB.OR.J1.GE.JMXB) CYCLE
!        IF (I2.LE.0.OR.J2.LE.0.OR.I2.GE.IMXB.OR.J2.GE.JMXB) CYCLE
        IZBX=AMIN1(ZBM(I1,J1),ZBM(I2,J2))
        ZBMIN(L)=IZBX
 240    CONTINUE
C
        IF (NSQRW.NE.NSQRS) THEN
          DO 2221 N=N1,NSQRW
          I=ISQR(N)
          J=JSQR(N)
          K=ISIDE(N)
          I1=I+IZ1(K)
          I2=I+IZ2(K)
          J1=J+JZ1(K)
          J2=J+JZ2(K)
C       WRITE(*,2222) I,J,K,HWEIR(N),ZBMIN(N),ZBM(I1,J1),ZBM(I2,J2)
C 2222 FORMAT(3I5,4F6.1)
 2221     CONTINUE
        ENDIF
      ENDIF
C
C      DEFINE GRID COORDINATES FOR STATIC BOUNDARY CONDITION.
      N=0
      DO 1200 I=1,IMXB1
      DO 1200 J=1,JMXB1
      IF (KSKP(I,J).EQ.'2') THEN
        N=N+1
        IF (N.GT.NBCPTS) THEN
          WRITE (*,*) 'Number of boundary points exceeded', N, NBCPTS
          STOP
        ENDIF
        ISH(N)=I
        JSH(N)=J
        KSKP(I,J)='0'
      ENDIF
 1200 CONTINUE
      NBCPT=N
C     WRITE(*,225) NBCPT
C 225  FORMAT(I5,'     TOTAL POINTS FOR STATIC BOUNDARY CONDITION')
C     NNN=(NBCPT-1)/15+1
C     DO 223 K=1,NNN
C     N1=1+(K-1)*15
C     N2=MIN(N1+14,NBCPT)
C     WRITE(*,222) K,(ISH(N),N=N1,N2)
C     WRITE(*,224) K,(JSH(N),N=N1,N2)
C 222 FORMAT(T62,'I-B.C.',I2,T1,15I4)
C 224 FORMAT(T62,'J-B.C.',I2,T1,15I4)
C 223 CONTINUE
c        no flooding option
      IF (NOFLD.EQ.'+') THEN
        DO 1234 J=2,JMXB1
        DO 1234 I=2,IMXB1
        IF (ZBM(I,J).GT.0.) THEN
          ITREE(I,J)='4'
C         COMMENTED BY NSM 11/20/2010 : Should it be HTER or HTER+1?
C          zbm(i,j)=36.
          ZBM(I,J)=HTER+1
        ENDIF
 1234 CONTINUE
      ENDIF
C
C        REDUCED PRINTOUT FOR OPERATIONAL MODE.
C     IF(IOPERL(1).NE.2) THEN
C       WRITE(6,290)
C       WRITE(6,300)
C       NGRP=(JMXB1-1)/25+1
C
C       DO 270 NN=1,NGRP
C       J1=1+(NN-1)*25
C       J2=J1+MIN0(24,JMXB1-J1)
C       WRITE(6,340)(J,J=J1,J2)
C       DO 260 I=1,IMXB1
C       WRITE(6,320)I,(ZB(I,J),J=J1,J2)
C 260   CONTINUE
C 270   CONTINUE
C
C        PRINT OUT HIGHEST LAND VALUE AT MOMENTUM GRID POINTS
C       WRITE(6,290)
C       WRITE(6,310)
C
C       DO 280 NN=1,NGRP
C       J1=2+(NN-1)*25
C       J2=J1+MIN0(24,JMXB1-J1)
C       WRITE(6,340)(J,J=J1,J2)
C       DO 280 I=2,IMXB1
C       WRITE(6,320)I,(ZBM(I,J),J=J1,J2)
C 280   CONTINUE
C
C 290 FORMAT(1H1)
C 300 FORMAT(/5X,'DEPTH FIELD.')
C 310 FORMAT(/5X,'HIGHEST ELEVATION (INCLUDING RIDGES, ROADS, ETC) AT
C    1MOMENTUM GRID POINTS.')
C 320 FORMAT(1H ,I2,26F5.0)
C 330 FORMAT(1H ,I2,26F5.1)
C 340 FORMAT(/I6,26I5)
C     ENDIF
      RETURN
      END
