      SUBROUTINE FLT2G
C        AUG 22 1984   J. CHEN         TDL   IBM 360/195
C        PURPOSE
C           TO ELIMINATE 2-GRID COMPUTATIONAL NOISE NEARBY LAND-WATER
C           BOUNDARIES. GRIG POINTS NEARBY INTERIOR BOUNDARIES ARE
C           PICKED OUT FROM TESTING IN SUBROUTINE 'SMPT2G'. SMOOTHING
C           DOES CONSERVE MASS BY ASSUMING OUSIDE OF SELECTED POINTS IS
C           NON-INTERACTING WITH THE POINTS TO BE SMOOTHED.
C        DATA SET USE
C           NONE
C        RETURNS
C           NO
C        VARIABLES
C                MM2G = TOTAL NO. OF POINTS TO BE SMOOTHED
C                MCMX = SPECIAL SMOOTHING POINTS
C         I2G(),J2G() = I,J COORD'S OF GRID POINTS FOR SMOOTHING
C             HB( , ) = SURGE HEIGHT FILED
C             ZB( , ) = TERRAIN HEIGHTS
C            ZBM( , ) = BARRIER HEIGHTS
C                 HCT = CUTOFF DEPTH ,1 FT EXCEPT THE SPECIAL POINTS
C                       WHICH 0 FT IS USED
C       COORDINATES ARE PICKED OUT FROM SUBROUTINE 'CONTTY)'.
C
      USE PARM2
      INCLUDE 'parm.for'
C
      COMMON /DUMB3/  IMXB,JMXB,IMXB1,JMXB1,IMXB2,JMXB2
      COMMON /GAMAF/  GAMA,GAMA1,GAMFP(4)
      COMMON /GPRT1/  DOLLAR,EBSN
      CHARACTER*2     DOLLAR
      CHARACTER*1     EBSN
      COMMON /SM2G/   MM2G,MCMX,I2G(M2G_),J2G(M2G_)
      INTEGER*2       MM2G,MCMX,I2G,J2G
      COMMON /DUMB8/  IP(4),JP(4),IH(4),JH(4)
      COMMON /DUM88/  IIH(4),JJH(4),IHH(4),JHH(4)
      DIMENSION   GAMF(4)
C
C
      IF (MCMX.EQ.0) GO TO 10
      DO 1010 M=1,MCMX
      I=I2G(MM2G+M)
      J=J2G(MM2G+M)
 1010 HSUB(I,J)=999.
 10   CONTINUE
C
      HCT=1.
      M1=1
      MMM=MM2G
      NNN=0
 3000 CONTINUE
      NNN=NNN+1
      IF (NNN.GT.2) GO TO 2000
      DO 190 M=M1,MMM
      I=I2G(M)
      J=J2G(M)
      IF(HSUB(I,J)+ZB(I,J).LE.HCT) GO TO 190
C
      HSM=0.
      HDIF=0.
      GAM0=ELPDL2(I)+(ELPCL2(I)-ELPDL2(I))*SINL2(J)
C
      DO 170 K=1,4
      II=I+IIH(K)
      JJ=J+JJH(K)
      IF (II.EQ.0.OR.JJ.EQ.0) THEN
        GAMF(K)=0.
        GOTO 160
        ENDIF
      IF (EBSN.EQ.'$'.OR.EBSN.EQ.'+') THEN
      GAMFK=ELPDL2(II)+(ELPCL2(II)-ELPDL2(II))*SINL2(JJ)
c      GAMF(K)=.5*(1.+GAMFK/GAM0)-1.
      Z=GAMFK/GAM0
      GAMF(K)=2.*Z/(1.+Z)-1.
      ELSE
      GAMF(K)=GAMFP(K)
      ENDIF
c
      IF (II.EQ.IMXB.OR.JJ.EQ.JMXB) GOTO 160
      IF (HSUB(II,JJ).EQ.999.) GO TO 160
      IF (HSUB(II,JJ)+ZB(II,JJ).LE.HCT) GO TO 160
      KK=MOD(K,4)+1
      IA=I+IP(K)
      IB=I+IP(KK)
      JA=J+JP(K)
      JB=J+JP(KK)
      Z =ZBM(IA,JA)
      ZZ=ZBM(IB,JB)
      ZZZ=AMIN1(Z,ZZ)+HCT
C        WATER ON EITHER SIDE MUST EXCEED THE BARRIER(LOWER) BY AT
      IF(NNN.EQ.2) GO TO 200
      IF( HSUB(I,J).LT.ZZZ.OR.HSUB(II,JJ).LT.ZZZ) THEN
          HSM=HSM+HSUB(I,J)
          HZZ=HSUB(I,J)
          ELSE
          HSM=HSM+HSUB(II,JJ)
          HZZ=HSUB(II,JJ)
          ENDIF
      GOTO 210
 200  IF( HSUB(I,J).LT.ZZZ.AND.HSUB(II,JJ).LT.ZZZ) THEN
          HSM=HSM+HSUB(I,J)
          HZZ=HSUB(I,J)
          ELSE
          HSM=HSM+HSUB(II,JJ)
          HZZ=HSUB(II,JJ)
          ENDIF
      GOTO 210
 160  CONTINUE
          HSM=HSM+HSUB(I,J)
          HZZ=HSUB(I,J)
 210  CONTINUE
C       WEIGHTING ADJUSTMENTS IN I-DIRECTION DUE TO POLAR GRIDS.
       HDIF=HDIF+HZZ*GAMF(K)
  170 CONTINUE
C
      HBTEMP=(1./3.)*HSUB(I,J)+(HSM+HDIF)/6.
C      HBTEMP=.5*HSUB(I,J)+.125*(HSM+HDIF)
      HB(I,J)=AMAX1(HBTEMP,-ZB(I,J))
  190 CONTINUE
      IF(MCMX.EQ.0) GO TO 2000
      DO 1020 M=1,MM2G
      I=I2G(M)
      J=J2G(M)
 1020 HSUB(I,J)=999.
      HCT=0.
      M1=MM2G+1
      MMM=MM2G+MCMX
      DO 1030 M=M1,MMM
      I=I2G(M)
      J=J2G(M)
 1030 HSUB(I,J)=HB(I,J)
      GO TO 3000
 2000  CONTINUE
      RETURN
      END
