         BLOCK DATA
C        JELESNIANSKI/CHEN     JULY 1988    TDL   FORTRAN 77 VERSION
C
C        PURPOSE
C        DATA INITIALIZATION
C           NONE
C
C        VARIABLES
C       IP(4) JP(4) = SHIFT SUBSCRIPTS T 4 ADJACENT MOMENTUM POINTS
C       IH(4) JH(4) = SHIFT SUBSCRIPTS TO 4 ADJACENT SURGE POINTS ABOUT
C                     A MOMUMTUM POINT
C     IIH(4) JJH(4) = SHIFT SUBSCRIPTS TO 4 ADJACENT SURGE POINTS ABOUT
C                     A SURGE POINT
C            IOPERL = 2  AS DEFAULT IN OPERATIONAL MODE
C         MAPIN(HR) = SPECIFIES THE PRINT HOUR, BEFORE AND AFTER THE
C                     NEAREST APPROACH OF STORM, FOR SNAPSHOT OUTPUT
C                 G = GRAVITY
C                C7 = SLIP COEFFICIENT
C               C17 = AIR DENSITY
C               C19 = FRICTIONAL COEFFICIENT
C               C25 = EDDY VISCOSITY
C         MONTH(12) = ACCUMULATED DAYS AT MONTHLY INCREMENTS
C          AMON(12) = FIRST 3 CHARACTERS FOR EACH MONTH
C
C        GENERAL COMMENTS
C           THIS MEMBER  RESIDES IN THE ROOT OVERLAY
C
      COMMON /DUMB8/  IP(4),JP(4),IH(4),JH(4)
      COMMON /DUM88/  IIH(4),JJH(4),IHH(4),JHH(4)
      COMMON /SWTCH/  IOPERL(5)
      COMMON /DELH11/ MAPIN(10),NUMBER
      COMMON /EGTH/   DELS,DELT,G,COR
      COMMON /THRD/   C7,C17,C19,C25
      COMMON /MTH/    MONTH(12),AMON(12)
      CHARACTER*4     AMON
C
      DATA IP/0,1,1,0/,JP/0,0,1,1/,IH/-1,0,-1,0/,JH/-1,-1,0,0/
      DATA IIH/0,1,0,-1/,JJH/-1,0,1,0/,IHH/-1,1,0,0/,JHH/0,0,-1,1/
      DATA IOPERL/2,2,2,2,2/
      DATA MAPIN/-3,0,2,7*1000/
      DATA DELS,G/5280.,32.2/
      DATA C7,C17,C19,C25 / .006 , .00115 , 3.E-6,.25 /
      DATA MONTH /-1,30,58,89,119,150,180,211,242,272,303,333/
      DATA AMON/'JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP',
     1     'OCT','NOV','DEC' /
C       SET DEFAULTS TO NONARCHIVING MODE ( NOARCH='X'). NO TIME HISTRY
C       KHSPT=0.
      COMMON /ARCH/   NOARCH
      COMMON /NFILE/  KNPT,NDATA(3)
      COMMON /CESAV/  IPN(120),IPL(120),KHSPT
      CHARACTER*1     NOARCH
      DATA KNPT/0/,KHSPT/0/,NDATA/13,14,15/,NOARCH/'X'/
C       THIS BLOCK DATA IS TO BE USED FOR LAKE PONTCHARTRAIN
C       BASIN ONLY.
c
      INCLUDE 'parm.for'
C      INCLUDE 'parmmsy.for'
C
      DATA ZSUBCE/-1./,JSUB,JSUB1/38,50/
C      Following needs 1 entry for each value in N_
C      For N_ = 1655, last entry is 1555*1
C      For N_ = 1699, last entry is 1599*1.
C      For N_ = 1550, last entry is 1450*1
      DATA LDTMG/5*33,8*35,5*34,
     1 30,29,29,28,27,26,26,24,22,20,21,22,22,21,
     2 68*1,1555*1/
      DATA NODRY/74/
      DATA IDRY/21,22,22,23,23,23,23,24,24,24,24,25,25,25,25,26,26,26,
     1          27,27,27,28,28,28,29,29,29,29,30,30,30,30,30,30,31,31,
     2          31,31,28,28,28,28,28,29,29,29,29,30,30,30,30,30,31,31,
     3          31,32,32,32,32,32,32,32,33,33,33,33,33,34,34,34,34,34,
     4          34,34,5926*1/
      DATA JDRY/28,28,29,27,28,29,30,27,28,29,30,26,27,28,29,26,27,28,
     1          24,25,26,23,24,25,22,23,24,25,20,21,22,23,24,25,19,20,
     2          25,21,26,27,28,29,30,27,28,29,30,26,27,28,29,30,26,27,
     3          28,23,24,25,26,27,28,29,23,26,27,28,29,20,21,22,23,27,
     4          28,29,5926*1/
C
       END
      SUBROUTINE FLW1DM
C        JELESNIANSKI   SEPTEMBER 1980 TDL   IBM 360/195
C
C        PURPOSE
C           THIS SUBROUTINE (FLW1DM) COMPUTES 1-DIM FLOW ACROSS CHANNEL
C           SIDES OF INTERLOCKING SQUARES. WATER PASSES ONLY THRU 'OPEN'
C           SIDES OF A 1-DIM FLOW CHANNEL, SEE DIAGRAM BELOW:
C
C                .****.****.****.****.        -FLOW     *NO FLOW
C                -    -    -    -    *        -THRU     *THRU
C                - +  - +  - +  - +  *        -CHANNEL  *CHANNEL
C                -    -    -    -    *        -SIDE     *SIDE
C                -****.****.****.----.
C                               *    *        (OPEN)    (CLOSED)
C                               * +  *
C                               *    *
C                               .----.
C           THE 'LOOP' OF THE CONTINUITY EQUATION FILLS/DEPLETES
C           TWO ADJOINING SQUARES WITH FLOW THRU AN 'OPEN' SIDE,
C           ONE SIDE AT A TIME. IF WATER DROPS BELOW A SQUARE
C           FROM THE ACTION OF AN 'OPEN' SIDE, THEN THE FLOW THRU
C           THE SIDE IS REDUCED TO EXHAUST WATER ONLY TO A DRY
C           SQUARE.
C
C           EACH 'OPEN' SIDE HAS AN INTERIOR AND AN EXTERIOR SQUARE.
C           SUBROUTINE 'CRDRD2' READS THE SUBSCRIPTS FOR INTERIOR
C           SQUARES AND SETS UP PROCEDURES TO ISOLATE THE
C           ADJOINING EXTERIOR SQUARES AND 'OPEN' SIDES VIA
C           'COMMON/DUMB18/'. THE PRESENT SUBROUTINE ISOLATES THE TWO
C           INTERIOR/EXTERIOR SQUARES AND THE ADJOINING SIDE FOR
C           1-DIM FLOW. A 1-DIM FLOW SQUARE CAN BE EITHER AN INT/EXT
C           SQUARE, OR BOTH, 1-4 TIMES, DEPENDING ON THE AMOUNT OF
C           'OPEN' SIDES BOUNDING A SQUARE.
C
C           I,J SHIFTS ABOUT AN (I,J) INTERIOR SQUARE FOR 4 POSSIBLE
C              EXTERIOR SQUARES ARE:
C
C                            .////.
C                            IHH=0/
C                            / 4+ /
C                            JHH=1/
C                       .////.////.////.
C                      IHH=-1/ I  /IHH=1
C                       / 1+ / +  / 2+ /
C                      JHH=0 / J  /JHH=0
C                       .////.////.////.
C                            IHH=0/
C                            / 3+ /
C                            JHH=-1
C                            .////.
C
C        DATA SET USE
C           NONE
C
C        VARIABLES
C           AI(800) = BOTTOM FRICTION, AT ONE FOOT INTERVALS
C             NSQRW = NO OF SQUARES WITH 1-DIM FLOW POSSIBLE
C  ISQR(L) JSQRL(L) = I/J-SUBSCRIPT FOR SQUARE WITH 1-DIM FLOW
C        HB(  ,   ) = SURGE FIELD
C        ISIDE(300) = SIDE OF FLOW RELATIVE TO INTERIOR 1-DIM FLOW SQRE
C     IHH(4) JHH(4) = SHIFT I/J-SUBSCRIPT FOR CONTIGUOUS SQUARE
C         HINT HEXT = INTERIOR/EXTERIOR SURGE FOR SFC GRADIENT
C       HINT1 HEXT1 = INTERIOR/EXTERIOR SURGE HEIGHTS ON SQUARES
C        ZBMIN(300) = LOWEST BARRIER VALUE AT END OF AN 'OPEN' SIDE
C                ZL = DUMMY VALUE FOR ZBMIN(300)
C         ZB(  ,  ) = DEPTH FIELD
C        HWEIR(300) = HIGHEST DEPTH  OF INT/EXT SQUARES, OR WEIR HEIGHT
C              HOVT = DUMMY VALUE FOR HWEIR(300)
C     FLWSQR(300  ) = TRANSPORT ACROSS AN 'OPEN' SIDE, TWO TIME LEVELS
C        GRIDR2(  ) = JACOBEAN FOR POLAR COORDINATES
C           SIGA(4) = SIGN FOR FLOW ACROSS SIDES OF SQUARES
C          DPH1D(2) = DEPTH+SURGE AT INT/EXT SQUARES, PRESENT TIME
C     CHNGHI CHNGHE = SURGE INCREASE ON INT/EXT SQRES, FROM 'OPEN' SIDE
C       DEPLI DEPLE = TOTAL DEPTH OF INT/EXT SQRES, FUTURE TIME
C               CII = ACCUMULATED WATER FROM 'OPEN' SIDES, INTERIOR SQR
C              SUBE = SURGE FROM EXT SQR TO PREVENT WATER BLW INT SQR
C         )    CEE = ACCUMULATED WATER FROM 'OPEN' SIDES, EXTERIOR SQR
C              SUBI = SURGE FROM INT SQR TO PREVENT WATER BLW EXT SQR
C            ID DPH = MEAN TOTAL DEPTH OF INT/EXT SQUARES, PRESENT TIME
C               DZL = HEIGHT OF HWEIR ABOVE MEAN DEPTHS
C           FXB FYB = COMPONENTS OF SURFACE STRESS
C            X1B(N) = FIXED COEFFICIENTS FOR FINITE DIFFERENCING
C   BR(300) BI(300) = FRICTION COEFFICIENTS AT 1-FOOT INTERVALS
C              JUMP = 2 FOR STRESS COMPUTATIONS, 1 FOR NO STRESS
C
C        GENERAL COMMENTS
C           THIS IS A VERSION FOR 2-STEP SCHEME (JULY 1981).
C           THIS SUBROUTINE RESIDES IN OVERLAY 'CMPUTE'. IT IS CALLED
C           IN BY SUBROUTINE 'CMPUTE'. SUBROUTINE 'FLW1DM' CALLS IN
C
C           SOME (NOT ALL) ELEVTNS ON INT/EXT SQRES AT PRESENT TIME ARE:
C
C                              T=ZL=ZBMIN(300)
C                              I
C                              I
C                              I
C                              I
C                              I***********>HINT=HB(I,JC)
C              HEXT<***********I      /
C                        /     I      /DPH1D(1)=HINT+ZB
C                        /     I      /
C                DPH1D(2)/     I----------->-ZB(I,J)
C                        /     I   /
C                        /     I   /
C                -ZB<----------I   /
C                          /   I   /
C                          /   I   /
C                          /   I   /
C                          /   I   /
C                 DEPTH=ZB=V   I   V=ZB=DEPTH
C             <----------------I----------------->NGVD DATUM
C                (EXTERIOR)        (INTERIOR)
C
      USE PARM2
      INCLUDE 'parm.for'
C
      COMMON /EGTH/   DELS,DELT,G,COR
      COMMON /SCND2/ AR2(2,600),AI2(2,600),BR2(2,600),BI2(2,600),
     1               CR2(2,600),CI2(2,600)
      COMMON /DUMB4/  X1B(10)
      COMMON /DUMB8/  IP(4),JP(4),IH(4),JH(4)
      COMMON /DUM88/  IIH(4),JJH(4),IHH(4),JHH(4)
      COMMON /MF/     DPH,HPD(4),ID
      COMMON /FLWCPT/ NSQRS,NSQRW,NSQRWC,NPSS,NCUT
C
      DIMENSION       SIGA(4),DPH1D(2)
C
      DATA SIGA/-1.,1.,-1.,1./
C
      DO 100 L=1,NSQRWC
      I=ISQR(L)
      J=JSQR(L)
      K=ISIDE(L)
      II=I+IHH(K)
      JJ=J+JHH(K)
      HSUB(I,J)=0.
      HSUB(II,JJ)=0.
 100  F1DACT(L)='F'
C
CXXXXXXXXX BEGIN 1ST 'LOOP'. TREAT 2-DIM FLOW (FROM 'CONTTY') ONTO
CXXXXXXXXX A 1-DIM SQUARE AS A SOURCE.
C
      DO 510 L=1,NSQRWC
C
      IF (FLWSQR(L).EQ.0.) GO TO 510
C        ISOLATE A PARTICULAR SQUARE AND ITS SURFACE HEIGHT
      I=ISQR(L)
      J=JSQR(L)
C
C        DETERMINE WHICH OF 4 SIDES HAS FLOW AND ISOLATE ADJACENT SQUARE
C        AND ITS SURFACE HEIGHT
      K=ISIDE(L)
      II=I+IHH(K)
      JJ=J+JHH(K)
C
C        START CONTINUITY EQUATION FOR ONE SIDE OF A SQUARE
C        COMPUTE TOTAL FLOW IN/OUT OF INTERIOR SQUARE
 110  Z=ELPDL2(I)+(ELPCL2(I)-ELPDL2(I))*SINL2(J)
      Z1=ELPDL2(II)+(ELPCL2(II)-ELPDL2(II))*SINL2(JJ)
      CHNGHI=-SIGA(K)*X1B(5)*FLWSQR(L)/Z
      CHNGHE=-CHNGHI*Z/Z1
C
C     DETERMINE 1-DIM, OR EXPANSION, FLOW
      KCUT=1
      IF (L.GT.NSQRW) KCUT=2
      GO TO (120,130), KCUT
C
C     CHECK FOR EXISTENCE OF BANKS
 120  IF (DELCUT(L).GE.1.) GO TO 470
      GO TO 140
 130  LL=L-NSQRW
      IF (CUTLI(LL).GE.1..AND.CUTLE(LL).GE.1.) GO TO 420
C
C      TWO CASES EXIST: OUTFLOW VERSUS INFLOW
C      CASE 1: CHNGHI NEG (OUTFLOW), CHNGHE POS (INFLOW),  LEAP=1
C      CASE 2: CHNBHI POS (INFLOW),  CHNGHE NEG (OUTFLOW), LEAP=2
 140   LEAP=1
       IF (CHNGHI.GT.0.) LEAP=2
       GO TO (192,194),LEAP
 192   CHNG=CHNGHI
       CSTRT=CHNGHI
        HT=HB(I,J)
        BK=BANK(L,1)
        IF(KCUT.EQ.2) CUTW=CUTLI(LL)
        GO TO (200,300),LEAP
 194   CHNG=CHNGHE
       CSTRT=CHNGHE
       HT=HB(II,JJ)
       BK=BANK(L,2)
       IF(KCUT.EQ.2) CUTW=CUTLE(LL)
       GO TO (300,200),LEAP
C******LOGIC FOR NEGATIVE WATER CHANGES (OUTFLOW)
 200   IF (HT.GT.BK) GO TO 230
        GO TO (210,220),KCUT
C       INITIAL WATER BELOW BANK AND DESCENDING
 210   CHNG=CHNG
       GO TO 280
 220   CHNG=CHNG*CUTL(LL)/CUTW
       GO TO 272
C      INITIAL WATER ABOVE BANK AND DESCENDING
 230   DELB=HT-BK
       GO TO (240,260),KCUT
C      WATER DOES NOT DESCEND BELOW BANK, PURE 1-D FLOW
 240   IF(-CHNG*DELCUT(L).GT.DELB) GO TO 250
       CHNG=CHNG*DELCUT(L)
       GO TO 272
C      WATER DESCENDS BELOW BANK, PURE 1-D FLOW
 250   CHNG=CHNG-DELB+DELB/DELCUT(L)
       GO TO 272
C      WATER DOES NOT DESCEND BELOW BANK, CUT-TYPE FLOW
 260   IF (-CHNG*CUTL(LL).GT.DELB) GO TO 270
       CHNG=CHNG*CUTL(LL)
       GO TO 272
C      WATER DESCENDS BELOW BANK, CUT-TYPE FLOW
 270   CHNG=(CHNG*CUTL(LL)+DELB)/CUTW-DELB
 272   CONTINUE
 280   GO TO (290,295),LEAP
 290   CHNGHI=CHNG
       HSUB(I,J)=HSUB(I,J)+ABS(CSTRT-CHNG)
       GO TO 194
 295   CHNGHE=CHNG
       HSUB(II,JJ)=HSUB(II,JJ)+ABS(CSTRT-CHNG)
       GO TO 192
C$$$$$$LOGIC FOR POSITIVE WATER CHANGES (INFLOW)
 300   IF (HT.LT.BK) GO TO 330
       GO TO (310,320),KCUT
C      INITIAL WATER ABOVE BANK AND ASCENDING
 310   CHNG=CHNG*DELCUT(L)
       GO TO 372
 320   CHNG=CHNG*CUTL(LL)
       GO TO 372
C      INITIAL WATER BELOW BANK AND ASCENDING
 330   DELB=BK-HT
       GO TO (340,360),KCUT
C      WATER DOES NOT ASCEND ABOVE BANK, PURE 1-D FLOW
 340   IF (CHNG.GT.DELB) GO TO 350
       CHNG=CHNG
       GO TO 380
C      WATER ASCENDS ABOVE BANK, PURE 1-D FLOW
 350   CHNG=DELB+(CHNG-DELB)*DELCUT(L)
       GO TO 372
C      WATER DOES NOT ASCEND ABOVE BANK, CUT-TYPE FLOW
 360   IF (CHNG*CUTL(LL).GT.DELB*CUTW) GO TO 370
       CHNG=CHNG*CUTL(LL)/CUTW
       GO TO 372
C      WATER ASCENDS ABOVE BANK, CUT-TYPE FLOW
 370   CHNG=CHNG*CUTL(LL)-DELB*CUTW+DELB
 372   CONTINUE
 380   GO TO (390,395),LEAP
 390   CHNGHE=CHNG
       HSUB(II,JJ)=HSUB(II,JJ)+ABS(CSTRT-CHNG)
       GO TO 470
 395   CHNGHI=CHNG
       HSUB(I,J)=HSUB(I,J)+ABS(CSTRT-CHNG)
       GO TO 470
 420   CHNGHI=CHNGHI*CUTL(LL)/CUTLI(LL)
       CHNGHE=CHNGHE*CUTL(LL)/CUTLE(LL)
 470   HBJ=HB(I,J)+CHNGHI
      HBJJ=HB(II,JJ)+CHNGHE
C        FINISH CONTINUITY EQUATION FOR ONE SIDE OF A SQUARE BY
C        TESTING IF WATER LIES BELOW SQUARES
 480  DEPLI=HBJ+ZB(I,J)
      DEPLE=HBJJ+ZB(II,JJ)
      IF (DEPLI.GE.0.) GO TO 490
C        WATER LIES BELOW INTERIOR SQUARE (DEPLI IS NEGATIVE)
      CII=CHNGHI-DEPLI
      SUBE=-CII*Z/Z1
      HB(I,J)=-ZB(I,J)
      HB(II,JJ)=AMAX1(HB(II,JJ)-CHNGHE+SUBE,-ZB(II,JJ))
      FLWSQR(L)=FLWSQR(L)*CII/CHNGHI
      GO TO 510
C        WATER LIES BELOW EXTERIOR SQUARE (DEPLE IS NEGATIVE)
 490  IF(DEPLE.GE.0.) GO TO 500
      CEE=CHNGHE-DEPLE
      SUBI=-CEE*Z1/Z
      HB(I,J)=AMAX1(HB(I,J)-CHNGHI+SUBI,-ZB(I,J))
      HB(II,JJ)=-ZB(II,JJ)
      FLWSQR(L)=FLWSQR(L)*CEE/CHNGHE
      GO TO 510
C
C        BOTH INTERIOR AND EXTERIOR SQUARES HAVE WATER ABOVE TERRAIN
C        AFTER UPDATES.
 500  HB(I,J)=HBJ
      HB(II,JJ)=HBJJ
C
      F1DACT(L)='T'
 510  CONTINUE
C***********************************************************************
C        END OF HEIGHT UPDATES BY COMPUTED FLOW ACCROSS SIDES
C***********************************************************************
C
C        USE UPDATED HEIGHTS COMPUTE FLOW ACCROSS SIDES.
C
C        FRICTION CHANGE BETWEEN 1-2 FEET OF TOTAL DEPTH, USED
C        FOR EXTRAPOLATION FROM 1 TO 0 FT.
C        SET PARAMETERS FOR FRCPNT ARGUMENTS, LAKE WINDS, WITH STATIC
C        PRESSURE FORCE.
      SLPA=AI2(1,2)-AI2(1,1)
!      SLPA=AI(2)-AI(1)
      NCATG=1
      NPLS=1
C
      DO 630 L=1,NSQRWC
C        ISOLATE A PARTICULAR SQUARE AND ITS SURFACE HEIGHT
      I=ISQR(L)
      J=JSQR(L)
!--------------------------
!      Check for land cells for friction array
       IF (ZB(I,J) < 0) THEN
         iFrict=2
       ELSE
         iFrict=1
       END IF
!-------------------------
      HINT=HB(I,J)
C        DETERMINE WHICH OF 4 SIDES HAS FLOW AND ISOLATE ADJACENT SQUARE
C        AND ITS SURFACE HEIGHT
      K=ISIDE(L)
      II=I+IHH(K)
      JJ=J+JHH(K)
      HEXT=HB(II,JJ)
C        ISOLATE MINIMUM ZBM ON SIDE CONNECTING TWO SQUARES
      ZL=ZBMIN(L)
C        TEST IF SFC LIES ABOVE ZL, E.G., 2-DIM FLOW IN BOTH SQUARES
      IF (AMIN1(HINT,HEXT).GE.ZL) GO TO 520
C        TEST IF BOTH SQUARES ARE DRY
      IF (HINT.EQ.-ZB(I,J).AND.HEXT.EQ.-ZB(II,JJ)) GO TO 520
C        DETERMINE HT OF WEIR OR HIGHEST DEPTH OF TWO SQUARES
      HOVT=HWEIR(L)
C        TEST IF ANY SQUARE(S) OVERTOP THE WEIR AT PRESENT TIME
      IF(AMAX1(HINT,HEXT).GT.HOVT) GO TO 530
 520  FLWSQR(L)=0.
      HSUB(I,J)=0.
      HSUB(II,JJ)=0.
      GO TO 630
 530  CONTINUE
C        COMPUTE MOMENTUM ON ONE SIDE OF A SQUARE
      HINT1=HB(I,J)
      HEXT1=HB(II,JJ)
      HINT=AMIN1(AMAX1(HINT1,HOVT),ZL)
      HEXT=AMIN1(AMAX1(HEXT1,HOVT),ZL)
      JUMP=2
      IF (AMAX1(HINT,HEXT).GE.ZL) JUMP=1
      HEAD=HEXT-HINT
      HEAD=SIGA(K)*HEAD
      DPH1D(1)=HINT+ZB(I,J)
      DPH1D(2)=HEXT+ZB(II,JJ)
      DPH=.5*(DPH1D(1)+DPH1D(2))
CCCCCCCCCCC Arthur fix of dph close to 0.
      if (dph.lt.0.00000001) then
        FLWSQR(L)=0.
        HSUB(I,J)=0.
        HSUB(II,JJ)=0.
        GO TO 630
      end if
CCCCCCCCCCC Arthur end fix of dph close to 0.
      ID=DPH
      ID=AMIN1(599.,DPH)
      ID=MAX0(ID,1)
      BIOBR=BI2(iFrict,ID)/BR2(iFrict,ID)
      IF (NSQRW.EQ.NSQRS) GOTO 1492
          IF (L.GT.NSQRS.AND.L.LE.NSQRW) BIOBR=0.
 1492 CONTINUE
      HCOFF=BR2(iFrict,ID)+BI2(iFrict,ID)*BIOBR
      FLWT=-X1B(1)*HCOFF*DPH*HEAD
         IF (JUMP.EQ.1)  GOTO 589
C
C        AVERAGE SHELTERING COEFF IF WATER BECOME LESS THAN 1 FT ABOVE
C        BED,OR 1 FT BELOW CHANNEL BANK,OR BARRIER HEIGHT.
      IF (KTREE(L).EQ.'T') THEN
         CSHLTR=(DPH/50.)**2
       ELSE
         CSHINT=1.-DIM(1.,DIM(HINT1,HOVT))
         CSHEXT=1.-DIM(1.,DIM(HEXT1,HOVT))
         CSH2I=1.-DIM(1.,DIM(ZL,HINT1))
         CSH2E=1.-DIM(1.,DIM(ZL,HEXT1))
         CSHLTR=.5*AMIN1(CSHINT+CSHEXT,CSH2I+CSH2E)
       ENDIF
C
      III=I
      JJJ=J
      GO TO (116,112,113,114),K
C        COMPUTE (X,Y) POSITION OF FORCE POINTS ON POLAR GRID
 112  III=I+1
 116  XR0=COSL(JJJ)
      YR0=SINL(JJJ)
      ELPCZ=ELPCT(III)
      ELPDZ=ELPDT(III)
      GO TO 115
 114  JJJ=J+1
 113  XR0=COST(JJJ)
      YR0=SINT(JJJ)
      ELPCZ=ELPCL(III)
      ELPDZ=ELPDL(III)
 115  CONTINUE
      XR=XR0*ELPCZ
      YR=YR0*ELPDZ
C
      CALL FRCPNT(XR,YR,FXB,FYB,NCATG,CSHLTR,NPLS,I,J)
C        CHANGE FORCING FROM (X,Y) SYSTEM TO IMAGE PLANE
      XR=XR0*ELPDZ
      YR=YR0*ELPCZ
      FXBP=XR*FXB+YR*FYB
      FYBP=XR*FYB-YR*FXB
C        CORRECT STRESS DIRECTION ACCORDING TO ACTURAL FLOW
      IF(COS1D(L).NE.1.) THEN
      FXB=COS1D(L)*FXBP-SIN1D(L)*FYBP
      FYB=SIN1D(L)*FXBP+COS1D(L)*FYBP
      ELSE
      FXB=FXBP
      FYB=FYBP
      ENDIF
C
      FRC1=.75*FXB
      FRC2=.75*FYB
      IF (K.EQ.3.OR.K.EQ.4) THEN
      Z=FRC2
      FRC2=-FRC1
      FRC1=Z
      ENDIF
C
      FRC12T= DELT*(FRC1+BIOBR*FRC2)
C           ENDED STRESS COMPUTATIONS.
      GOTO 590
C
C        INITIALIZE FLOW WITH GRAVITY AND WITHOUT SURFACE STRESS
 589  FRC12T=0.
C
 590   CONTINUE
C        TAKE AVERAGE OF 'AI' ON TWO SQUARES
      AINTRP=0.
      DO 620 KK=1,2
      IDD=AMIN1(299.,DPH1D(KK))
      IF (IDD.GT.1) GO TO 600
      AITR=AI2(1,1)+SLPA*(DPH1D(KK)-1.)
      GO TO 610
 600  SLPAI=AI2(iFrict,IDD+1)-AI2(iFrict,IDD)
      DPHI=IDD
      AITR=AI2(iFrict,IDD)+SLPAI*(DPH1D(KK)-DPHI)
 610  AINTRP=AINTRP+AITR
 620  CONTINUE
      AINTRP=.5*AINTRP
      FLWCOF=X1B(4)*(AINTRP-AR2(iFrict,ID)*BIOBR)+1.
      FLW=FLWT+FLWCOF*FLWSQR(L)+FRC12T
      FWD=HSUB(II,JJ)-HSUB(I,J)
      IF (FWD.EQ.0.) GO TO 628
      FD2=-SIGA(K)*FWD*X1B(2)/(DPH*DPH)
      FD2=ABS(FD2)
      Z=ELPDL2(I)+(ELPCL2(I)-ELPDL2(I))*SINL2(J)
      Z1=ELPDL2(II)+(ELPCL2(II)-ELPDL2(II))*SINL2(JJ)
      XY=.5*(1./Z+1./Z1)
      FD2=FD2*XY
      FLW1=FLW
      DO 627 ITR=1,20
      FLW1=FLW/(1.+FD2*ABS(FLW1))
 627  CONTINUE
      FLWSQR(L)=FLW1
      GO TO 630
 628  FLWSQR(L)=FLW
 630  CONTINUE
C++++++++END MOMENTUM COMPUTATIONS FOR 1-DIM FLOW+++++++++++++++++++++++
C
C--------END MAIN 'LOOP'------------------------------------------------
      RETURN
       END
