       SUBROUTINE INITLZ
C        JELESNIANSKI    SEPTEMBER 1980TDL   IBM 360/195
C
C        PURPOSE
C           THIS SECOND OVERLAY 'INITLZ' USES SUBROUTINE 'INITLZ' AS A
C           CALLING SEQUENCE FOR 5 SUBROUTINES.
C           THE PURPOSE OF THE OVERLAY IS TO FIX SOME PROGRAM CONSTANTS,
C           SOME POLAR GRID CONSTANTS; TO SET BATHYMETRY/TOPOGRAPHY AND
C           BARRIER HEIGHTS, AND TO INITIALIZE A TIMING SEQUENCE.
C
C        DATA SET USE
C           NONE
C
C        VARIABLES
C         ALTO (DEG)= LATITUDE OF BASIN CENTER OR ORIGIN
C
C        GENERAL COMMENTS
C     THIS SUBROUTINE RESIDES IN OVERLAY 'INITLZ'. IT IS CALLED
C           BY THE ROOT OVERLAY AND NOT BY ANY OTHER SUBROUTINE.
C
      COMMON /DUMB3/  IMXB,JMXB,IMXB1,JMXB1,IMXB2,JMXB2
      COMMON /FRANK/  IRANK,ISTAR,ISTOP,JSTAR,JSTOP
C      COMMON /SLAT/   FSOUTH
      COMMON /BSN/    PHI,ALTO,ALNO,PHI1,ALT1,ALN1,ALT1C
      COMMON /SWTCH/  IOPERL(5)
      COMMON /GPRT1/  DOLLAR,EBSN
      CHARACTER*2     DOLLAR
      CHARACTER*1     EBSN
C      CHARACTER*40    FILNAM
C      CHARACTER*80    DUM
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C DTA OPTIONS FOR DTA VERSION AND ELLIPSOID TYPE IF EXIST
C IVER = 199201(ORIGINAL DTA FORMAT) / 201408(NEW DTA FORMAT)
C IPRJ = 0(CLARKE ELLIPSOID) / 1(GRS80 ELLIPSOID)
C D.Y 8/2014
      COMMON /DTAOPT/ IVER, IPRJ
      INTEGER IVER, IPRJ
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      CALL INPUTN2
C          READ BASIN PROJECTION DATA
      IVER = 199201
      IPRJ = 0
      CALL CRDRD1(IVER,IPRJ)
      CALL STERON

C           READ IN SLOSH GEOGRAPHY DATA
      IF (IVER .EQ. 199201) THEN
        CALL CRDRD2
      ELSE
        CALL CRDRD2_N(IVER)
      ENDIF
      CALL MAPSHIFT
      IMXB=ISTOP-ISTAR+1
      IMXB1=ISTOP-ISTAR+1-1
      IMXB2=ISTOP-ISTAR+1-2
      JMXB=JSTOP-JSTAR+1
      JMXB1=JSTOP-JSTAR+1-1
      JMXB2=JSTOP-JSTAR+1-2
C           CHANNEL COORDINATES REQUIRED FOR SETDST TO DEFINE AREAS.
      IF (DOLLAR.EQ.'2$') CALL DEPMSY
       CALL DEPSFC
c       IF(IOPERL(1).NE.2) CALL BSNPRT
C
       ZLATO=ALTO
C       IF (FSOUTH.LT.0.) ZLATO=-ALTO
       CALL BTMSTR(ZLATO)
       CALL SETDST
       CALL INTDLT
       CALL INTVAL
       CALL CNSTNT
      RETURN
       END
