      SUBROUTINE INTDLT
C        JELESNIANSKI      AUGUST 1980 TDL   IBM 360/195
C
C        PURPOSE
C           THIS SUBROUTINE (INTDLT) ASCERTAINS TIME STEP 'DELT' FOR
C           COMPUTATIONS, INITIALIZES STORM AT SUBSCRIPT 'IBGNT' AND
C           SETS 'ITEND' FOR ENDING COMPUTATIONS AFTER NEAREST STORM
C           APPROACH.
C
C        DATA SET USE
C           NONE
C
C        VARIABLES
C              DELT = TIME INTERVAL FOR EXPLICIT FINITE DIFFERENCING
C              DLTB = THE SMALLEST REDUCTION OF DELT IN THE RUN
C            RLNGTH = DISTANCE OF STORM FROM NEAREST APPROACH
C               JHR = SUBSCRIPT FOR NEAREST APPROACH TO BASIN CENTER
C           PT(100) = HOURLY PRESSURE DROPS
C     X(100) Y(100) = HOURLY COMPONENTS FOR STORM POSITIONS
C            R(100) = HOURLY STORM SIZES
C            XMOUTH = X-DISTANCE FROM POLE TO BASIN CENTER
C            YMOUTH = Y-DISTANCE (USUALLY EQUAL TO 0)
C             IBGNT = TABULATED SUBSCRIPT FOR STORM INITIALIZATION
C             ITEND = TABULATED SUBSCRIPT FOR STORM TERMINATION
C              IBGS = NUMBER OF HOURS FOR COMPUTATIONS BEFORE
C                     NEAREST STORM APPROACH
C              ITMS = NUMBER OF REMAINING HOURS, AFTER NEAREST APPROACH,
C          DLTIN(3) = TIME STEPS FOR 3 CATEGORIES OF STORMS FROM DATA
C
C        GENERAL COMMENTS
C           THIS SUBROUTINE LIES IN OVERLAY 'STRMPR'. IT IS CALLED IN
C           BY SUBROUTINE 'STRMPR'.
C
      COMMON /EGTH/   DELS,DELT,G,COR
      COMMON /DLTDTA/ DLTIN(3),DLTB
      COMMON /BSN/    PHI,ALTO,ALNO,PHI1,ALT1,ALN1,ALT1C
      PARAMETER (NT_=999)
      COMMON /SPLN/   ALT(15),ALN(15),AX(15),AY(15),RL(15),ANGD(15),
     1                PDUM(15),RT(15),XLAT(NT_),YLONG(NT_),RLNGTH
      COMMON /STRMPS/ X(NT_),Y(NT_),PT(NT_),R(NT_),DIR(NT_),SP(NT_)
C STIME interferes with C code, so switched to STIME2
      COMMON /STIME2/  ISTM,JHR,ITMADV,NHRAD,IBGNT,ITEND
      COMMON /ORIGN/  XMOUTH,YMOUTH
      COMMON /INZSTM/ IBGS,ITMS
      COMMON /OPT/ NOPT
      COMMON /FLES/ FLE5,FLE9,FLE8,FLE91,FLE99,FLE10,FLE20,FLE30,FLE1
      CHARACTER*256 FLE5,FLE9,FLE8,FLE91,FLE99,FLE10,FLE20,FLE30,FLE1
C
C        SET DLTB FOR REDUCTION OF DELT.
      DLTB=DLTIN(2)
C
C        RESET A SMALLER DLTB IF STORM IS STRONG OR STORM IS CLOSE.
      IF(RLNGTH.GT.90.) GO TO 100
      MAXP=AMAX1(PT(JHR),PT(JHR-3))
      IF (MAXP.GT.60) DLTB=DLTIN(3)
C
  100 CONTINUE
C        SET INITIAL DELT.
      DELT=DLTIN(1)
C
      IF (DELT.GT.500..OR.DELT.LT.5.) GO TO 130
      GO TO 150
 130  CONTINUE
CC      WRITE(*,140) DELT,(DLTIN(I),I=1,3)
 140  FORMAT('  TIME STEP=',F10.3,' IS IMPROPERLY CHOSEN FROM BASIN',
     1' DATA ',3F15.6)
c      STOP
 150  CONTINUE
C
C        SET HOUR FOR STORM INITIALIZATION
C      DO 110 II=1,JHR
C      I=JHR-II+1
C      XZ=X(I)-XMOUTH
C      YZ=Y(I)-YMOUTH
C      DIS=SQRT(XZ*XZ+YZ*YZ)
C      DISCRT=6.*AMAX1(RLNGTH,R(I))
C      IF(DIS.GT.DISCRT) GO TO 120
C  110 CONTINUE
C
C        COMPUTE HOURS OF COMPUTATION BEFORE NEAREST STORM APPROACH
C  120 IBGS=MIN0(MAX0(JHR-I,18),60)
C         SET 12 HOURS OF COMPUTATION, AFTER NEAREST APPROACH
C      ITMS=12
C      IF (NOPT.EQ.1) THEN
C      OPEN (1,FILE=FLE1)
C      READ(1,210,END=200) IBGS,ITMS,JHR1
C      CLOSE (1)
C 210  FORMAT(2I3,4X,I2)
C      IF(JHR1.NE.0) GO TO 220
C      GO TO 200
C 220  JHR=JHR1
C 200  CONTINUE
C      ENDIF
C        THE ABOVE COMPUTES INITIALIZATION BASED ON TRACK
C        AND SIZE OF THE STORM. 18<=HOURS<=60 BEFORE NEAREST
C        APPROACH ARE ASSUMED.
C        COMPUTE TABULATED SUBSCRIPT FOR STORM INITIALIZATION
C      IBGNT=MAX0(JHR-IBGS,1)
C      ITEND=MIN0(99,JHR+ITMS)
      RETURN
      END
