      SUBROUTINE INTVAL
C        JELESNIANSKI    AUGUST 1980   TDL   IBM 360/195
C        PURPOSE
C           THIS SUBROUTINE (INTVAL) SETS INITIAL STORM PARAMETERS,
C           SOME FIXED CONSTANTS FOR INITIALIZATION, AND OUTPUT TIMES.
C
C        DATA SET USE
C           NONE
C
C        VARIABLES
C              DELT = TIME INTERVAL FOR EXPLICIT FINITE DIFFERENCING
C     NDLTHR NDLTH2 = NUMBER OF TIME STEPS IN ONE AND 1/2 HOUR
C            IPRTSV = AT THIS TIME PRINT HISTORICAL SURGES (10 POINTS)
C            IPRTAD = ADVANCE 'IPRTSV' BY 'IPRTAD'
C             IBGNT = SUBSCRIPT FOR STORM INITIALIZATION
C     X(100) Y(100) = HOURLY COMPONENTS FOR STORM POSITIONS
C           SP(100) = HOURLY FORWARD STORM SPEEDS
C          DIR(100) = HOURLY STORM AZIMUTHS
C            R(100) = HOURLY STORM SIZES
C              IBGS = NO OF HRS FOR COMPUTATIONS BEFORE NEAREST APPROACH
C              ITMS = NO OF HRS FOR COMPUTATIONS AFTER NEAREST APPROACH
C             MHALT = number of time steps for total compuations
C             ITEND = TABULATED SUBSCRIPT FOR STORM TERMINATION
C              IC19 = GROWTH TIME TO MATURE STORM
C              ALTO = LATITUDE OF BASIN CENTER
C         MAPIN(10) = PRINT OUT TIME FOR ENVELOPE SNAPSHOT
C            IOPERL = 2 IF IN OPERATIONAL MODE
C            ISTMAP = AT THIS TIME, PRINT A SNAPSHOT OF SURGES
C            NUMBER = NEAREST HOUR TO NEAREST APPROACH
C
C        GENERAL COMMENTS
C           USE ONLY TIME STEPS DIVISIBLE BY 600 S(10 MIN),OR 900 S(
C           15 MIN).
C           THIS SUBROUTINE LIES IN OVERLAY STRMPR. IT IS CALLED IN BY
C           SUBROUTINE STRMPR.
C
      COMMON /EGTH/   DELS,DELT,G,COR
      COMMON /DELTH/  NDLTHR,NDLTH2,DLTHR,DLTH2
      COMMON /FRTH/   IC12,IC19,BT
      COMMON /PRTSV/  IPRTSV,IPRTAD
C STIME interferes with C code, so switched to STIME2
      COMMON /STIME2/  ISTM,JHR,ITMADV,NHRAD,IBGNT,ITEND
      PARAMETER (NT_=999)
      COMMON /STRMPS/ X(NT_),Y(NT_),PT(NT_),R(NT_),DIR(NT_),SP(NT_)
      COMMON /INZSTM/ IBGS,ITMS
      COMMON /FFTH/   ITIME,MHALT
      COMMON /BSN/    PHI,ALTO,ALNO,PHI1,ALT1,ALN1,ALT1C
      COMMON /DELH11/ MAPIN(10),NUMBER
      COMMON /SWTCH/  IOPERL(5)
      COMMON /MAPTME/ ISTMAP,IADMAP
C
C        NUMBER OF TIME STEPS IN AN HOUR/HALF-HOUR
      NDLTHR=3600./(DELT-.001)
      NDLTH2=NDLTHR/2
      DLTHR =NDLTHR
      DLTH2 =NDLTH2
C
C        NUMBER OF TIME STEPS BETWEEN TIME-HISTORY PRINT-OUT.
      IPRTAD=NDLTHR/4
      IF(MOD(NDLTHR,6).EQ.0) IPRTAD=NDLTHR/6
      IPRTSV=IPRTAD
C
C
C
C        TOTAL RUN TIME
      T=ITEND-IBGNT
C      write (*,*) "Mhalt", MHALT, (T*3600.+1.)/DELT
      MHALT=(T*3600.+1.)/DELT
CC      write (*,*)' total hours and time steps',t,mhalt
C
C        PRE-SET STORM GROWTH TO 2 HOURS
      IC19=2*NDLTHR
C
C        COMPUTE STORM GROWTH TIME TO MATURITY
      IF (SP(IBGNT).LT.1.E-5) GO TO 100
C
C        NO OF TIME STEPS FOR STORM TO MOVE 1 DIAMETER IN LENGTH
      IGRWTH=(2.*R(IBGNT)/SP(IBGNT))*DLTHR
      GO TO 110
  100 IGRWTH=4*NDLTHR+4
  110 CONTINUE
      IC19=MAX0(IC19,MIN0(4*NDLTHR+4,IGRWTH))
C
      DO 120 I=1,5
      J=IBGNT+I-1
      IF(ABS(X(J)-1.).LT.(.25*R(IBGNT))) IC19=4*NDLTHR
  120 CONTINUE
C
CC      write (*,*) ' spin-up hours = ',(ic19+1)/ndlthr
C        SET MAPIN(10)  AS SELECTED HOURS, FOR SNAPSHOT OUTPUTS
C      IF(IOPERL(1).NE.2) GO TO 125
C      MAPIN(1)=0
C      DO 122 I=2,10
C 122  MAPIN(I)=200
C 125  CONTINUE
      DO 130 I=1,10
  130 MAPIN(I)=JHR+MAPIN(I)
C
      DO 140 I=1,10
      IF(MAPIN(I).GT.IBGNT+1) GO TO 150
  140 CONTINUE
C
  150 NUMBER=I
C        SET PRINT OUT TIME OF STORM AT NEAREST APPROACH
C        INITIALIZE OUTPUT TIME FOR SNAPSHOT ENVELOPE OF SURGES
      ISTMAP=MAPIN(I)
      RETURN
      END
