#!/bin/make
#------------------------------------------------------------------------------
# makefile.linux                                        Last Change: 2021-07-27
#                                                        Arthur.Taylor@noaa.gov
#                                                              NWS/OSTI/MDL/DSB
#
# Makefile for slosh (command line) on LINUX systems
# Usage:
#    make                     Build the executable
#    make install             Move the built executable to the exec dir
#    make clean               Start with a clean slate
#
#    make B=gcc               Build using gcc suite (linux)
#    make B=intel             Build using intel suite
#------------------------------------------------------------------------------
SHELL=/bin/bash#              # Shell for script evaluations
MPI=false#                    # Do we build with MPI?
MINGW=false#                  # Allow MinGW specific functions
B=gcc#                        # See usage.
DOUBLE=true#                  # Use double precision flags
BIT=32#                       # Use 32 (vs 64) bit compilation

#-------------------------------------------
# Set up the called executables and version
#-------------------------------------------
CC=gcc
VER:=$(shell $(CC) --version |head -n1 |cut -d' ' -f2,3 --output-delimiter='-')
FC=gfortran
ifeq ($(B),intel)
   CC=icc
   FC=ifort
endif
MV=/bin/mv
RM=/bin/rm
MKDIR=/bin/mkdir

#--------------------------
# Set the C compiler flags
#--------------------------
CFLAGS=-O3#                   # Optimization level
CFLAGS+=-Wall#                # Activate all warnings
ifeq ($(B),intel)
   CFLAGS+=-strict-ansi -fp-model strict# Activate more warnings
endif
ifeq ($(B),gcc)
   CFLAGS+=-Wextra -pedantic -ansi# Activate more warnings
endif
CFLAGS+=-D_LINUX_#            # Operating system (_LINUX_,_UNIX_,_WINDOWS_)
ifeq ($(BIT),64)
  CFLAGS+=-DSIZEOF_LONG_INT=8#  # Compile on a 64 bit platform
endif
CFLAGS+=-D_GCC_#              # Use GCC wrappings for binding to FORTRAN
ifeq ($(DOUBLE),true)
   CFLAGS+=-DDOUBLE_FORTRAN#  # Compile with double precision in FORTRAN
endif
ifeq ($(MPI),true)
   CFLAGS+=-D_MPI_#           # Compile with MPI
endif
ifeq ($(MINGW),true)
   CFLAGS+=-D_MINGW_#         # Allow MinGW specific sleep(), mkdir() functions
endif
# CFLAGS+=-DEBUG#             # Turn on debug flags
CFLAGS+=-D_EXPR_#             # Activate experimental options
CFLAGS+=-I.#                  # Add '.' to the include path
ifeq ($(BIT),32)
  CFLAGS+=-m32
endif

#-----------------------------------
# Set up the FORTRAN compiler flags
#-----------------------------------
FFLAGS=-O3#                   # Optimization level
ifeq ($(DOUBLE),true)
   ifeq ($(B),intel)
      FFLAGS+=-r8#            # Use double precision flags
   else
      FFLAGS+=-fdefault-real-8# Use double precision flags
   endif
endif
ifeq ($(B),intel)
   FFLAGS+=-fp-model strict#  # Activate more warnings
   FFLAGS+=-check bounds#     # Make sure no out of array index calls.
#   FFLAGS+=-warn all
#   FFLAGS+=-warn nodeclarations
#   FFLAGS+=-warn unused
#   FFLAGS+=-fp-stack-check
#   FFLAGS+=-heap-arrays 10
endif
ifeq ($(BIT),32)
  FFLAGS+=-m32
endif

#------------------------------------------
# Set up the Library flags (order matters)
#------------------------------------------
LIBS=-lgfortran
# LIBS+=-Wl,-Bstatic
# LIBS+=-lquadmath#           # Used for EMC's workstation (8/9/2019)


LIBS+=-L/usr/lib -lm
ifeq ($(B),intel)
   LIBS=-lifcore -limf
endif

#-------------------------------------
# Set up the command executable flags
#-------------------------------------
#CFLAGS+=-DCC_VER="\"$(VER)\""# Add compiler version.
#CMDFLAGS1=$(CFLAGS)# Add compiler version.
CMDFLAGS1=$(CFLAGS) -DCC_VER="\"$(VER)\""# Add compiler version.

#--------------------------------------------------------
# Set up the Linker flags
#--------------------------------------------------------
LDFLAGS=
ifeq ($(B),intel)
   LDFLAGS=-xAVX#             # Avoid complaint about MOVBE, FMA, BMI, LZCNT,
                              # AVX2 when at higher than O0 optimization.
endif

#------------------------------------------------------------------------------
# Source (CSRC, MPISRC, FSRC); HEADERS, FORT_HEADERS; OBJS; Main
#------------------------------------------------------------------------------
CSRC=amyutil.c
CSRC+=clock.c
CSRC+=complex.c
CSRC+=myassert.c
CSRC+=myutil.c
CSRC+=pack.c
CSRC+=rex.c
CSRC+=savellx.c
CSRC+=setup.c
CSRC+=slosh2.c
CSRC+=tendian.c
CSRC+=tideutil.c
CSRC+=tio3.c
CSRC+=usrparse.c

MPISRC=mpiutil.c

#----------------------------------
# Intrface.f :: Was in this order.
#----------------------------------
FSRC=parm2.f#                 # Compile FORTRAN modules first.
# FSRC+=inital.f
FSRC+=wind.f
FSRC+=wav.f
# FSRC+=tmstep.f
FSRC+=clnup.f
FSRC+=cln_hs.f
FSRC+=dealloc.f
FSRC+=xy2llx.f
FSRC+=staticht.f
FSRC+=issubgrid.f
FSRC+=casename.f

#--------------------------------
# Spinup.f :: Was in this order.
#--------------------------------
FSRC+=intlhtsub.f
FSRC+=intlhtadd.f
FSRC+=momntm2.f
FSRC+=mntmbd2.f
FSRC+=flw1dm2.f
FSRC+=tmstp2.f

FSRC+=initalcommon.f

#---------------------------------
# runslhg.f :: Was in this order.
#---------------------------------
FSRC+=extrpt.f
FSRC+=intdlt.f
FSRC+=intval.f
FSRC+=cnstnt.f
# ifeq ($(FC),gfortran)
#ifeq ($(BIT),64)
#FSRC+=btmstr_gnu.f
#else
FSRC+=btmstr.f
#endif
FSRC+=setcmp.f
FSRC+=stmval.f
FSRC+=cnsdlt.f
FSRC+=force1.f
FSRC+=intwnd.f
FSRC+=prtstm.f
FSRC+=crdrd1.f
FSRC+=alloc.f
FSRC+=ttimer.f
FSRC+=initlz.f
FSRC+=inputn.f
FSRC+=steron.f
FSRC+=setdst.f
FSRC+=depmsy.f
FSRC+=intlht.f
FSRC+=crdrd2.f
FSRC+=crdrd2_n.f
FSRC+=depsfc.f
FSRC+=contty.f
FSRC+=bdryht.f
FSRC+=channl.f
FSRC+=flw1dm_block.f#         # subblock and flw1dm combined.
FSRC+=frcpnt.f
FSRC+=momntm.f
FSRC+=mntmbd.f
FSRC+=fhmxsv.f
FSRC+=archiv.f
FSRC+=histry.f
FSRC+=hstry2.f
FSRC+=filtrp.f
FSRC+=hmxsv.f
FSRC+=smpt2g.f
FSRC+=flt2g.f
FSRC+=filter.f
FSRC+=flter2.f
FSRC+=snapsh.f
FSRC+=xfilter.f
FSRC+=inputn2.f
FSRC+=spline.f
FSRC+=splint.f
ifeq ($(B),intel)
   FSRC+=rstout_WCOSS.f
else
   FSRC+=rstout.f
endif
FSRC+=setcmp_hs.f
FSRC+=hbuv_hs.f

#-------------------------------------
# FORTRAN code for command line only.
#-------------------------------------
FSRC1=wave.f
FSRC1+=inital.f
FSRC1+=tmstep.f

# FORTRAN code for GUI only.
FSRC2=inital_GUI.f
FSRC2+=tmstep_GUI.f

#----------------
# C header files
#----------------
HEADERS=amyutil.h
HEADERS+=clock.h
HEADERS+=complex.h
HEADERS+=halotype.h
HEADERS+=mpiutil.h
HEADERS+=myassert.h
HEADERS+=myutil.h
HEADERS+=pack.h
HEADERS+=rex.h
HEADERS+=savellx.h
HEADERS+=setup.h
HEADERS+=slosh2.h
HEADERS+=tendian.h
HEADERS+=tideutil.h
HEADERS+=tio3.h
HEADERS+=type.h
HEADERS+=usrparse.h

#------------------------------------
# FORTRAN include (aka header) files
#------------------------------------
FORT_HEADERS+=parm.for
FORT_HEADERS+=parmmsy.for
FORT_HEADERS+=wav1.for

#---------------------------------
# Setup OBJ1 list and CMD1 target
#---------------------------------
OBJS1=$(CSRC:.c=.o)
# Handle MPISRC
ifeq ($(MPI),true)
   OBJS1+=mpiutil.o
endif
OBJS1+=$(FSRC:.f=.o)
OBJS1+=$(FSRC1:.f=.o)
MAIN1=cstart.c
CMD1=sloshLinux

#------------------------------------------------------------------------------
# Targets
#------------------------------------------------------------------------------
all: $(CMD1)
.PHONY: all

$(CMD1): $(OBJS1) $(MAIN1) $(HEADERS) $(FORT_HEADERS)
ifeq ($(B),intel)
	@echo "********************************************************************"
	@echo "Remember to 'module load ./Intel.module' for icc version 14."
	@echo "********************************************************************"
endif
	$(CC) $(MAIN1) $(CMDFLAGS1) $(LDFLAGS) $(OBJS1) $(LIBS) -o $(CMD1)

.PHONY: install
install: $(CMD1)
	$(MKDIR) -p ../../exec
	$(MV) $(CMD1) ../../exec

.PHONY: clean
clean:
	-$(RM) -f $(OBJS1)
	-$(RM) -f $(CMD1)
	-$(RM) -f *.mod
	-$(RM) -f *genmod.f90

#------------------------------------------------------------------------------
# Suffixes
#------------------------------------------------------------------------------
.c.o: $(HEADERS)
	$(CC) -c $(CFLAGS) $<

.f.o: $(FORT_HEADERS)
	$(FC) -c $(FFLAGS) $<

mpiutil.o: mpiutil.c $(HEADERS)
	$(CC) -c $(CFLAGS) mpiutil.c

topology.o: topology.c $(HEADERS)
	$(CC) -c $(CFLAGS) topology.c

winBuffer.o: winBuffer.c $(HEADERS)
	$(CC) -c $(CFLAGS) winBuffer.c
