#!/bin/make
SHELL = /usr/bin/bash

############################
# This makefile is intended to create the Windows executable.
#
# USAGE:
#    make B=gcc342 | gcc450 | gcc461 (B is for build)
#
# Other options...
#    make MEM=true, DEBUG=true, DOUBLE=true, EXPR=true
#    EXPR=true means enable experimental options.
#       EXPR should be false for FOIA CD so it has well tested options.
############################
#B=gcc342
#DOUBLE=false
B=gcc450
MEM=false
DEBUG=false
DOUBLE=true
MPI=false
MINGW=true
EXPR=true

# MPI currently only works for cygwin (gcc453)...
ifeq ($(MPI),true)
  B=gcc453
  MINGW=false
endif

############################
# Set up the path.
############################
ifeq ($(MINGW),true)
  ifeq ($(B),gcc342)
  BINDIR = /cygdrive/c/sys/MinGW/MinGW-3.4.2/bin
  else
    ifeq ($(B),gcc450)
    BINDIR = /cygdrive/c/sys/MinGW/MinGW-4.5.0/bin
    else
    BINDIR = /cygdrive/c/sys/MinGW/MinGW-4.6.1/bin
    endif
  endif
else
  BINDIR=/usr/bin
endif
PATH := $(BINDIR)

############################
# Set up the binary files and version info.
############################
HEAD = /usr/bin/head
CUT = /usr/bin/cut
CP = /usr/bin/cp
MKDIR = /usr/bin/mkdir
RM = /usr/bin/rm
ifeq ($(MPI),true)
  CC = mpicc
else
  CC = gcc
endif
ifeq ($(B),gcc342)
  F77 = g77
else
  F77 = gfortran
endif
STRIP = strip

############################
# Set up Targets
############################
NAME = sloshGui
ifeq ($(DOUBLE),true)
  PRJ_NAME = $(NAME)_$(B)Dbl
else
  PRJ_NAME = $(NAME)_$(B)
endif
TARGETS = $(PRJ_NAME)
SUFFIX = .exe

############################
# Set up Compiler flags...
#   CFLAGS (via STD_DEF and STD_INC) and FFLAGS
############################
      # _WINDOWS_ ==> Means use Windows GUI support.
STD_DEF = -D_WINDOWS_
      # _WINDOWS_ ==> Means use Tcl API connections.
STD_DEF += -DHAVE_TCL
      # _GCC_ ==> Means use GCC wrappings for connecting to fortran.
STD_DEF += -D_GCC_
      # CC_VER ==> embeds the compiler version into exectuable.
CC_VER := $(shell $(BINDIR)/$(CC) --version | $(HEAD) -n1 | $(CUT) -d' ' -f2,3 --output-delimiter='-')
STD_DEF += -DCC_VER="\"$(CC_VER)\""
      # Compile with double precision flags.
ifeq ($(DOUBLE),true)
  STD_DEF += -DDOUBLE_FORTRAN
endif
      # Allows Mingw specific sleep(), mkdir() functions.
ifeq ($(MINGW),true)
  STD_DEF += -D_MINGW_
endif
      # Compile with MPI
ifeq ($(MPI),true)
  STD_DEF += -D_MPI_
endif
      # Allow for MemWatch diagnostics.
ifeq ($(MEM),true)
  STD_DEF += -DMEMWATCH -DMEMWATCH_STDIO -DDEBUG
  MEMWATCH = memwatch.o
  STD_INC = -I./memwatch
else
  ifeq ($(DEBUG),true)
     STD_DEF += -DDEBUG
  endif
  MEMWATCH =
  STD_INC =
endif
   # check to see if EXPR options should be enabled (not true in FOIA case)
ifeq ($(EXPR),true)
  STD_DEF += -D_EXPR_
endif

# Add Tcl/Tk headers.
STD_INC += -I../../gui/include/tcl8.5.3_win
STD_INC += -I.

CFLAGS = -O3 -Wall -Wextra -pedantic -ansi
CFLAGS += $(STD_DEF) $(STD_INC)

ifeq ($(DOUBLE),true)
  FFLAGS = -O3
  FFLAGS += -fdefault-real-8
else
  FFLAGS = -O0
endif

############################
# Set up Linker flags...
#    STD_LIB and LD_FLAGS
############################
ifeq ($(DOUBLE),true)
  LD_FLAGS = -Wl,--stack,68000000
else
  LD_FLAGS = -Wl,--stack,34000000
endif
ifeq ($(B),gcc342)
  STD_LIB = -lg2c
else
  STD_LIB = -Wl,-Bstatic -lgfortran
endif
      # Compile with MPI
ifeq ($(MPI),true)
  STD_LIB += -Wl,-Bdynamic -lmpi -lesmtp
endif

# Add TK/TCL/halo85 libraries to Lib Path.
STD_LIB += -L../../gui/exec -Wl,-Bdynamic -ltk85
STD_LIB += -L../../gui/exec -Wl,-Bdynamic -ltcl85
STD_LIB += -L../../gui/exec -Wl,-Bdynamic -lhalo85

# Provide console diagnostics
LD_FLAGS += -mconsole
STD_LIB += -L/usr/lib -lm

############################
# FILES
############################
SOURCE = amyutil.c \
         clock.c \
         complex.c \
         mpiutil.c \
         myassert.c \
         myutil.c \
         pack.c \
         rex.c \
         savellx.c \
         setup.c \
         slosh2.c \
         tendian.c \
         tideutil.c \
         tio3.c \
         usrparse.c

FSOURCE = intrface.f \
          runslhg.f \
          spinup.f

GUISOURCE = haloclock2.c \
            tclslosh.c

OBJECTS = $(SOURCE:.c=.o) \
          $(FSOURCE:.f=.o) \
          $(GUISOURCE:.c=.o) \
          $(MEMWATCH)

HEADERS = amyutil.h \
          clock.h \
          complex.h \
          halotype.h \
          mpiutil.h \
          myassert.h \
          myutil.h \
          pack.h \
          parm.for \
          parmmsy.for \
          rex.h \
          savellx.h \
          setup.h \
          slosh2.h \
          tendian.h \
          tideutil.h \
          tio3.h \
          type.h \
          usrparse.h

GUIHEADERS = haloclock2.h \
             halo_out.h \
             tclslosh.h

C_MAIN = tclstart.c

############################
# TARGETS
############################
all: $(TARGETS)
	@echo ""

help:
	@echo "make B=(gcc342 | gcc450 | gcc461)"
	@echo "     other options: MEM=true, DEBUG=true, DOUBLE=true, EXPR=true"

$(PRJ_NAME): $(OBJECTS) $(C_MAIN) $(HEADERS) $(LIB_DEP)
	$(CC) $(C_MAIN) $(CFLAGS) $(LD_FLAGS) $(OBJECTS) $(STD_LIB) -o $(PRJ_NAME)
	$(STRIP) -s $(PRJ_NAME)$(SUFFIX)

install: $(TARGETS)
	$(MKDIR) -p ../../gui/exec
#	$(CP) $(PRJ_NAME)$(SUFFIX) ../../gui/exec
	$(CP) $(PRJ_NAME)$(SUFFIX) ../../gui/exec/$(NAME)$(SUFFIX)

clean:
	$(RM) -f *.o *.bak *.BAK

############################
# SUFFIXES
############################
.c.o : $(HEADERS)
	$(CC) -c $(CFLAGS) $<

.f.o :
	$(F77) -c $(FFLAGS) $<

memwatch.o: ./memwatch/memwatch.c ./memwatch/memwatch.h
	$(CC) -c $(CFLAGS) ./memwatch/memwatch.c
