      SUBROUTINE MNTMBD(JUMP,IJUMP,ISB,JSB,ARJ,AII,I,J,UBJ,VBJ,
     1   FXB,FYB,NCATG,CSHLTR,NPLS)
C        JELESNIANSKI   OCTOBER 1980   TDL   IBM 360/195
C
C        PURPOSE
C           THIS SUBROUTINE (MNTMBD) COMPUTES TRANSPORTS ON MOMENTUM
C           BOUNDARY POINTS, BETWEEN LAND AND DEEP WATERS. IN SHALLOW
C           WATERS THE BOUNDARY CONDITION EQUATES SURFACE GRADIENT AT
C           BOUNDARY AND NEAREST INTERIOR POINT.  IN INTERMEDIATE
C           WATERS THE BOUNDARY CONDITION IGNORES TIME VARIATIONS AND
C           EQUATES SURGE GRADIENT AS STATIC HEIGHT GRADIENT AT A
C           BOUNDARY POINT.
C           BELOW IS ARRANGEMENT OF MOMENTUM BOUNDARY LINE
C           AND NEAREST INTERIOR LINE.
C
C          .    .(I,J)          .    .(I,J)      .    . INTERIOR LINE
C                                                *    *
C            +                    +              * +  *
C                                                *    *
C          .    .<---IJUMP=2--->.    .< IJUMP=1 >.****. BOUNDARY LINE
C               (ISB,JSB)          (ISB,JSB)
C  DEEP--->      <INTERMEDIATE >      <SHALLOW  >     <---LAND-----
C
C        DATA SET USE
C           NONE
C
C        VARIABLES
C             ISKIP = 1 TO COMPUTE MOMENTUM ON J=1    BOUNDARY
C                     2 TO COMPUTE MOMENTUM ON I=IMXB BOUNDARY
C                     3 TO COMPUTE MOMENTUM ON J=JMXB BOUNDARY
C         ISB JSB = REVISED SUBSCRIPTS FOR A BOUNDARY POINT
C     UB VB(  ,   ) = TRANSPORTS
C              JUMP = 1 FOR SURFACE FORCING,2 FOR NO SURFACE FORCING
C             IJUMP = 1 FOR SHALLOW WATER BOUNDARY COMPUTATIONS
C                     2 FOR INTER DEPTH   BOUNDARY COMPUTATIONS
C           FXB FYB = COMPONENTS OF DRIVING FORCES
C       AIT AII AIU = PRE-COMPUTED VALUES IN 'MOMNTM'
C       AIV ARJ XTT = DITTO
C            AINTRP = DITTO
C           X1B(10) = FIXED CONSTANTS
C           UBJ VBJ = TRANSPORTS AT (I,J) AT PRESENT TIME,SAVED BEFORE
C                     UPDATED
C
C        GENERAL COMMENTS
C           THIS SUBROUTINE RESIDES IN OVERLAY 'CMPUTE'. IT IS CALLED
C           IN BY SUBROUTINE 'MOMNTM'. SUBROUTINE 'MOMNTM' IS CALLED
C          IN BY SUBROUTINE 'CMPUTE'. THIS SUBROUTINE ALSO CALLS IN
C           SUBROUTINE 'STRESS'.
C
      INCLUDE 'parm.for'
C
      COMMON /EGTH/   DELS,DELT,G,COR
      COMMON /DUMB4/  X1B(10)
      COMMON /SCND2/ AR2(2,600),AI2(2,600),BR2(2,600),BI2(2,600),
     1               CR2(2,600),CI2(2,600)
C
      AIUL=AII*(UB(ISB,JSB)-UBJ)
      AIVB=AII*(VB(ISB,JSB)-VBJ)
C       TEST FOR PARTIAL FLOODING (NO FORCING).
         IF (JUMP.EQ.2) THEN
      XTTX=0.
      XTTY=0.
      GO TO 140
         ENDIF
C           TEST FOR SHALLOW WATER BOUNDARY AND INTERMEDIATE WATER BOUNDARY
      IF (IJUMP.EQ.2) GOTO 160
C
C        SHALLOW WATER COMPUTATIONS, FORCING COMPUTED ON BOUNDARY POINTS
C
      FXD=FXB
      FYD=FYB
C        GRID TRANSFORMATION FROM (I,J) TO (X,Y)
      XR=ELPCT(ISB)*COST(JSB)
      YR=ELPDT(ISB)*SINT(JSB)
      NPLS=1
      CALL FRCPNT(XR,YR,FXBP,FYBP,NCATG,CSHLTR,NPLS,I,J)
C        CHANGE FORCING FROM (X,Y) SYSTEM BACK TO IMAGE PLANE
      XR=ELPDT(ISB)*COST(JSB)
      YR=ELPCT(ISB)*SINT(JSB)
      FXB=XR*FXBP+YR*FYBP
      FYB=XR*FYBP-YR*FXBP
C        STRESS DIFFERENCE BETWEEN BOUNDARY POINT AND INTERIOR POINT
      XTTX=DELT*(FXB-FXD)
      XTTY=DELT*(FYB-FYD)
C
C        COMPUTE MOMENTUM ON SHALLOW DEPTH BOUNDARIES. SURFACE GRADIENT
C        TERMS CANCELED BY ASSUMED B.C.
C        NOTE: USE SIELECKI'S SCHEME FOR CORIOLIS TERM.
C              VBJ = V-COMPONENT AT PRESENT TIME AT I,J
C              UB(I,J),VB(I,J) = U,V IN FUTURE TIME
  140 UB(ISB,JSB)=UB(I,J)+AIUL+ARJ*(VB(ISB,JSB)-VBJ)    +XTTX
      VB(ISB,JSB)=VB(I,J)+AIVB-ARJ*(UB(ISB,JSB)-UB(I,J))+XTTY
      GO TO 170
C
C        NO FORCING WHEN JUMP=2
C
C        COMPUTE MOMENTUM ON INTERMEDIATE DEPTH BOUNDARIES
C        ELIMINATE STATIC PRESSURE TERM IN FRCPNT(NPLS=0).
  160 NPLS=0
      CSHLTR=1.
C        GRID TRANSFORMATION FROM (I,J) TO (X,Y)
      XR=ELPCT(ISB)*COST(JSB)
      YR=ELPDT(ISB)*SINT(JSB)
C
      CALL FRCPNT(XR,YR,FXBP,FYBP,NCATG,CSHLTR,NPLS,I,J)
C        CHANGE FROM (X,Y) SYSTEM TO IMAGE PLANE
      XR=ELPDT(ISB)*COST(JSB)
      YR=ELPCT(ISB)*SINT(JSB)
      FXB=XR*FXBP+YR*FYBP
      FYB=XR*FYBP-YR*FXBP
C
  166 UB(ISB,JSB)=AII*UB(ISB,JSB)+ARJ*VB(ISB,JSB)+ DELT*FXB
      VB(ISB,JSB)=AII*VB(ISB,JSB)-ARJ*UB(ISB,JSB)+ DELT*FYB
  170 RETURN
       END
