       SUBROUTINE MOMNTM
C        JELESNIANSKI,CHEN   SEPTEMBER 1980 TDL   IBM 360/195
C
C        PURPOSE
C           THIS SUBROUTINE (MOMNTM) COMPUTES FUTURE MOMENTUM COMPONENTS
C           ON ALL INTERIOR GRID POINTS, AFTER FIRST COMPUTING FUTURE
C           SURGE BY SUBROUTINE 'CONTTY'. IT CHECKS IF MOMNTM CAN EXIST
C           AT A GRID POINT; E.G.,  OVERTOPPING THE GRID POINT .
C           FUTURE SURGES UPDATED FROM SUB. 'CONTTY' ARE USED TO COMPUTE
C           HEIGHT GRADIENTS AND TO CHECK FOR ELIGIBLE MOMENTUM POINTS--
C           BACKWARD SCHEME---. CHECKS ARE MADE IF MOMENTUM IS TO BE
C           COMPUTED AT OPEN BOUNDARY POINTS.
C
C        DATA SET USE
C           NONE
C
C        VARIABLES
C             NCATG = 1 FOR LAKE WINDS, 2 FOR OCEAN WINDS
C              NPLS = 0 REMOVE STATIC PRESSURE TERM IN FORCING(INT.B.C.)
C                   = 1  OTHERWISE
C             JMXB1 = MAX NO. OF J-POINTS, LESS A BOUNDARY POINT
C              JUMP = 1, FULLY FLOODED; 2,PARTIALLY FLOODED (NO STRESS)
C            MS(  ) = BEGIN I-SUBSCRIPT ON A J-LINE
C       ITREE( ,  ) = INDICATOR ARRAY FOR LAKE/OCEAN, TREE/NO TREE
C                     A,B,C,D FOR BNOUDARY TYPES
C        ZBM(  ,  ) = MAXIMUM BARRIER HT AT A SURGE POINT
C       IH(4) JH(4) = SHIFT I/J-SUBSCRIPTS TO 4 SURRNDNG SRGE PTS
C       IP(4) JP(4) = SHIFTS I/J-SUBPTS FROM SURGE PTS TO 4 MOM. CORNERS
C        HB(  ,   ) = SURGE HEIGHTS
C         ZB(  ,  ) = DEPTHS
C             HF(4) = STORAGE FOR 4 SURRNDNG SURGE PTS,
C            HPD(4) = STORAGE FOR 4 SURRNDNG TOTAL DEPTH POINTS
C     UB VB(  ,   ) = COMPONENTS OF TRANSPORT
C           DHX DHY = COMPONENTS OF SURFACE GRADIENT
C            ID DPH = MEAN TOTAL DEPTH
C   AI(300) AR(300) = FRICTION COEFFICIENTS ON TRANSPORTS
C           FXB FYB = COMPONENTS OF DRIVING FORCES
C           X1B(4)  = DEL*CORIOLIS PARM
C            CSHLTR = EXTINCTION COEF OF STRESS FOR WATER LESS THAN 1 FT
C             ISKIP = 1, COMPUTE MOMENTUM ON J=1    BOUNDARY
C                     2, COMPUTE MOMENTUM ON I=2 BOUNDARY
C                     3, COMPUTE MOMENTUM ON J=JMXB BOUNDARY
C                     4, COMPUTE MOMENTUM ON I=IMXB BOUNDARY
C             IJUMP = 1, SHALLOW WATER BOUNDARY COMPUTATIONS
C                     2, INTER DEPTH   BOUNDARY COMPUTATIONS
C    ISBS JSBS(4) = SHIFT SUBSCRIPTS FROM INTERIOR TO BOUNDARY PT
C         ISHF(3,4) = SUBSCIPTS SHIFTS FROM INTERIOR TO 3 CORNER
C                     MOM-POINTS FOR ALL 4 CORNERS
C
C        GENERAL COMMENTS
C           THIS SUBROUTINE RESIDES IN OVERLAY 'CMPUTE'. IT IS CALLED
C           IN BY SUBROUTINE 'CMPUTE'. THE PRESENT SUBROUTINE CALLS
C           IN 2 SUBROUTINES, 'FRCPNT' AND 'MNTMBD'.
C
C
      USE PARM2
      INCLUDE 'parm.for'
C
      COMMON /FRTH/   IC12,IC19,BT
      COMMON /MF/     DPH,HPD(4),ID
      COMMON /DUMB3/  IMXB,JMXB,IMXB1,JMXB1,IMXB2,JMXB2
      COMMON /EGTH/   DELS,DELT,G,COR
      COMMON /SCND2/ AR2(2,600),AI2(2,600),BR2(2,600),BI2(2,600),
     1               CR2(2,600),CI2(2,600)
      COMMON /DUMB8/  IP(4),JP(4),IH(4),JH(4)
      COMMON /DUM88/  IIH(4),JJH(4),IHH(4),JHH(4)
      COMMON /DUMB4/  X1B(10)
      COMMON /DUMB4I/ CORL(90)
      COMMON /GPRT1/  DOLLAR,EBSN
      DIMENSION     SLPAI(600),HFX(4),ISBS(4),JSBS(4),ISHF(3,4)
      CHARACTER*2   DOLLAR,SIG_
      CHARACTER*1   EBSN
      DATA ISBS/0,-1,0,1/,  JSBS/-1,0,1,0/
      DATA SIG_/'$'/,SHGT/50./
      DATA ISHF/1,2,4, 1,2,3, 1,3,4, 2,3,4/
C       PRECALCULATED SLOPES OF AI(ID). MAY BE PERMANENTLY STORED.
      DO 10 I=1,599
 10   SLPAI(I)=AI2(1,I+1)-AI2(1,I)
      SLPAI(600)=SLPAI(599)
C
      JEND=JMXB1
      IF (DOLLAR.EQ.SIG_) JEND=JMXB
C
      DO 570 J=2,JEND
C
C         ISKIP SET 3 RANGES FOR J
C
      ISKIP=2
C        FOR CILCULAR ISLAND, NO SIDE-BOUNDARIES (1 OR 3) TO BE TESTED.
C        FOR J=1, U/V  REPEAT THOSE AT J=JMXB (JEND).
      IF (DOLLAR.NE.SIG_) THEN
        IF(J.EQ.2) ISKIP=1
        IF(J.EQ.JEND) ISKIP=3
        ENDIF
C
      IST=MS(J)
      IFN=ME(J)
C        SKIP A J-COLUMN IF MS(J) IS SET TO IMXB OR GREATER.
      IF ((IFN-IST).LT.0) GO TO 570
C
      DO 560 I=IST,IFN
!--------------------------
!      Check for land cells for friction array
       IF (ZB(I,J) < 0) THEN
         iFrict=2
       ELSE
         iFrict=1
       END IF
!--------------------------
      JUMP=1
C        NO TERRAIN HIGHER THAN 35 FT CAN BE FLOODED.

C     CHANGED BY NSM 11/20/2010 TO ALLOW TERRAIN HIGHER THAN 35FT TO FLOOD
C     DID NOT Accept.  The '4' is now correctly shifted to 56 and above
C     and if it was a '4' for 35..56, it is now a '1'.
      IF (ITREE(I,J).EQ.'4'.OR.ITREE(I,J).EQ.'6') GO TO 560
C      IF (ITREE(I,J).EQ.'6') GO TO 560

C        ITREE IS SET TO 1 OR 3 FOR LAKE WINDS, 2 OR 5 FOR OCEAN WINDS
        IF (ITREE(I,J).EQ.'2'.OR.ITREE(I,J).EQ.'5') THEN
         NCATG=2
         ELSE
         NCATG=1
         ENDIF
      IF (NCATG.EQ.1) GOTO 140
      IF (ITREE(I,J).EQ.'2'.AND.ZBM(I,J).LT.-50.) GOTO 160
C
C      TEST IF SURRNDNG SQRS ARE DRY, PART/FULL FLOOD .
C
 140  CONTINUE
c
      HMN=AMIN1(HB(I,J),HB(I-1,J),HB(I,J-1),HB(I-1,J-1))
      IF (HMN.GT.ZBM(I,J)) GO TO 200
      HMXX=AMAX1(HB(I,J),HB(I-1,J),HB(I,J-1),HB(I-1,J-1))
      IF (HMXX.GT.ZBM(I,J)) GO TO 300
C       NO TRANSPORTS ARE ALLOWED, GO TO CHECK IF NEXT TO BOUNDARY.
      GO TO 220
C        ALL SURROUNDING SQUARES ARE FLOODED, CALCULATE GRADIENT TREM
C        WITH CENTER DIFFERENCES
 200  JUMP=1
      DHX=-HB(I-1,J-1)+HB(I,J-1)-HB(I-1,J)+HB(I,J)
      DHY=-HB(I-1,J-1)-HB(I,J-1)+HB(I-1,J)+HB(I,J)
      GO TO 340
C
C        AT LEAST ONE SQUARE IS NOT OVERTOPPED. USE HYDRULIC HEAD FOR
C        SLOPE ON THAT SQUARE (1/4 EFFECT) AS APPROXMATION
 300  JUMP=2
C      DEFINE A MODIFIED SURFACE GRADIENT FOR A PARTIALLY FLOODED POINT
      HF1=AMAX1(HB(I-1,J-1),ZBM(I,J))
      HF2=AMAX1(HB(I  ,J-1),ZBM(I,J))
      HF3=AMAX1(HB(I-1,J  ),ZBM(I,J))
      HF4=AMAX1(HB(I  ,J  ),ZBM(I,J))
      DHX=-HF1+HF2-HF3+HF4
      DHY=-HF1-HF2+HF3+HF4
C
C        TAKE AVERAGE (D+H), OR TOTAL DEPTH, OF 4 SURROUNDING SQUARES
C        USED TO DEFINE BOTTOM STRESS COEFFICIENTS
 340  CONTINUE
      HPD(1)=HB(I-1,J-1)+ZB(I-1,J-1)
      HPD(2)=HB(I  ,J-1)+ZB(I  ,J-1)
      HPD(3)=HB(I-1,J  )+ZB(I-1,J  )
      HPD(4)=HB(I  ,J  )+ZB(I  ,J  )
      DPH=.25*(HPD(1)+HPD(2)+HPD(3)+HPD(4))
      DPHZ=DPH
      ID=AMIN1(599.,DPHZ)
C
C        FOR VERY THIN SHEET OF WATER ON BARE TERRAIN, BOTTOM FRICTIONS
C        ARE ARTIFICIALLY INCREASED WITH A CUBIC FORMULA
      IF (DPH.GT.5.) GO TO 405
C        IT IS UNNECESSARY IF PARTIALLY FLOODED.
      IF (JUMP.EQ.2) GO TO 400
C
C        REVISE DPH AND ID
      DO 380 K=1,4
      IF(HPD(K).GE.5.) GO TO 370
C        USE ALTERNATIVE X-1+(1-X/5)**3 = X*(.4+.12*X-.008*X**2)
      HPD(K)=HPD(K)*(.4+.12*HPD(K)-.008*HPD(K)*HPD(K))
      GO TO 380
 370  HPD(K)=HPD(K)-1.
 380  CONTINUE
C
      DPH=.25*(HPD(1)+HPD(2)+HPD(3)+HPD(4))
      DPHZ=DPH
      ID=AMIN1(599.,DPHZ)
 400  ID=MAX0(1,ID)
C
C+++++++ TAKE AVERAGE 'AI(TOTAL DEPTH)' ON 4 SQUARES++++++++++++++++++++
C        EXTRAPOLATION IF DPH IS LESS THAN 1 FT
 405  AINTRP=0.
      DO 430 K=1,4
      DPHZ=HPD(K)
      IDD=MIN(599.,DPHZ)
      IDD=MAX0(IDD,1)
C        EXTRAPOLATION RESULTS IF DEPTH IS LESS THAN 1 FT.
      DPHI=IDD
      AITR=AI2(iFrict,IDD)+SLPAI(IDD)*(DPHZ-DPHI)
 420  AINTRP=AINTRP+AITR
 430  CONTINUE
      AINTRP=.25*AINTRP
      GOTO 450
C
C        ALL SURROUNDING SQUARES ARE FLOODED
 160  CONTINUE
      JUMP=1
      DHX=-HB(I-1,J-1)+HB(I,J-1)-HB(I-1,J)+HB(I,J)
      DHY=-HB(I-1,J-1)-HB(I,J-1)+HB(I-1,J)+HB(I,J)
      DPH=.25*(HB(I-1,J-1)+HB(I,J-1)+HB(I-1,J)+HB(I,J)+
     1         ZB(I-1,J-1)+ZB(I,J-1)+ZB(I-1,J)+ZB(I,J))
      DPHZ=MIN(599.,DPH)
      ID=MIN(599.,DPHZ)
      DPHI=ID
      AINTRP=AI2(iFrict,ID)+SLPAI(ID)*(DPHZ-DPHI)
C
 450  AII=1.+X1B(4)*AINTRP
C
C      CORIOLIS PARAMETER DEPENDS ON THE THE LATITUDE OF THE GRID.
      LLAT=YLT(I,J)
      ZCOR=CORL(LLAT+1)+(YLT(I,J)-LLAT)*(CORL(LLAT+2)-CORL(LLAT+1))
      ARJ=AR2(iFrict,ID)*X1B(4)*ZCOR
C
C
      AIU=AII*UB(I,J)
      AIV=AII*VB(I,J)
      FCT=X1B(6)*DPH
C
C        IF PARTIALLY FOODED, NO STRESS IS APPLIED FOR CURRENT TIME.
      IF (JUMP.EQ.2) GOTO 490
C -----------------------------------------------------------------------
      IF (NCATG.EQ.2) THEN
       CSHLTR=1.
       ELSE
         HFX(1)=HB(I-1,J-1)-ZBM(I,J)
         HFX(2)=HB(I  ,J-1)-ZBM(I,J)
         HFX(3)=HB(I-1,J  )-ZBM(I,J)
         HFX(4)=HB(I  ,J  )-ZBM(I,J)
C
C        SHELTERING WIND STRESS LINEARLY IF WATER IS LESS THAN 1 FT
C        ABOVE TERRAIN OR BARRIER.
           IF (ITREE(I,J).NE.'1') THEN
           CSH1=AMIN1(HFX(1),1.)
           CSH2=AMIN1(HFX(2),1.)
           CSH3=AMIN1(HFX(3),1.)
           CSH4=AMIN1(HFX(4),1.)
           CSHLTR=.25*(CSH1+CSH2+CSH3+CSH4)
             ELSE
C
C        STRONGER CSHLTERING FOR MANGROVES OR TREES. SHGT = HEIGHT OF
C        TREE TOP.
             CSHLTR=0.
             DO 484 KX=1,4
             HFXX=1.
             IF(HFX(KX).LE.0.) THEN
               HFXX=0.
               ELSE IF(HFX(KX).LT.SHGT) THEN
               HFXX=(HFX(KX)/SHGT)**2
               ENDIF
             CSHLTR=CSHLTR+HFXX
 484       CONTINUE
             CSHLTR=.25*CSHLTR
             ENDIF
      ENDIF
C
C        LOCATE GRID (I,J) ON PHYSICAT PLANE  Z=(XR,YR)=ZETA
      XR=ELPCT(I)*COST(J)
      YR=ELPDT(I)*SINT(J)
      NPLS=1
c
      CALL FRCPNT(XR,YR,FXBP,FYBP,NCATG,CSHLTR,NPLS,I,J)
C
C        CHANGE FORCING FROM (X,Y) SYSTEM BACK TO IMAGE PLANE,
C        CONJ(DZ/DZETA)*(FXBP,FYBP), WHERE DZ/DZETA=(XR,YR)
      XR=ELPDT(I)*COST(J)
      YR=ELPCT(I)*SINT(J)
      FXB=(XR*FXBP+YR*FYBP)
      FYB=(XR*FYBP-YR*FXBP)
C
      XTTX=DELT*FXB
      XTTY=DELT*FYB
      GO TO 480
C -----------------------------------------------------------------------
C        NO FORCINGS
 490  XTTX=0.
      XTTY=0.
C
 480  CONTINUE
C
C       TEMPORARILY STORE PRESENT U/V TO BE USED FOR BOUNDARY POINTS
      UBJ=UB(I,J)
      VBJ=VB(I,J)
C        COMPUTE MOMENTUM ON INTERIOR POINT, SIELECKI'S SCHEME FOR
C        CORIOLIS TERM IS USED.
      UB(I,J)=AIU-FCT*(BR2(iFrict,ID)*DHX-BI2(iFrict,ID)*DHY)+
     1ARJ*VB(I,J)+XTTX
      VB(I,J)=AIV-FCT*(BR2(iFrict,ID)*DHY+BI2(iFrict,ID)*DHX)-
     1ARJ*UB(I,J)+XTTY
C
      GO TO 500
C
C        TRANSPORT POINT NOT OVERTOPPED IN FUTURE
 220  UB(I,J)=0.
      VB(I,J)=0.
C ------------------------------------------------------------------
C        CHECK IF MOMENTUM COMPUTATIONS REQUIRED ON BOUNDARY
C        ISKIP=1, LEFT BOUNDARY(J=1)
C             =2, AND I=2, NEXT TO TOP BOUNDARY
C             =3, RIGHT BOUNDARY
C             =4, AND I=IMXB1,NEXT TO BOTTOM BOUNDARY
C        IJUMP=1, INTERMEDIATE WATER; =2, SHALLOW WATER
C
 500  IJUMP=1
      GO TO (530,520,540),ISKIP
C
C        CHECK FOR 4 CORNER POINTS AND SET ICOR.
C        ICOR=1,LEFT-TOP; 2,LEFT-BOTTOM;3,RIGHT-TOP;4,RIGHT-BOTTOM
 530  IF(I.NE.ME(J)) GO TO 512
      ICOR=2
 512  IF(I.NE.MS(J)) GO TO 510
      ICOR=1
      GO TO 600
 540  IF(I.NE.ME(J)) GO TO 514
      ICOR=4
 514  IF(I.NE.MS(J)) GO TO 510
      ICOR=3
      GO TO 600
C
C        TEST FOR BOTTOM BOUNDARY
 520  IF(I.EQ.MS(J)) GO TO 510
      IF(I.EQ.ME(J)) GO TO 516
      GO TO 560
 516  ISKIP=4
 510  CONTINUE
      IA=ISBS(ISKIP)
      JA=JSBS(ISKIP)
      ISB=I+IA
      JSB=J+JA
C        IF AT (I,J),TRANSPORTS ARE ZERO,SET TRANSPORTS AT BOUNDY ZEROS.
      IF(UB(I,J).EQ.0.) THEN
      UB(ISB,JSB)=0.
      VB(ISB,JSB)=0.
        GOTO 560
        ENDIF
C        PRE-SET ITREEALONG BOUNDARIES; =4  FOR LAND (SKIP COMP.)
C                                       =9  FOR SHALLOW WATER
C                                       =8  FOR INTERMEDIATE DEPTHS
C                                       =6  FOR DEEP WATER (SKIP COMP.)
      IF(ITREE(ISB,JSB).EQ.'6'.OR.ITREE(ISB,JSB).EQ.'4') GO TO 560
      IF(ITREE(ISB,JSB).EQ.'8' ) IJUMP=2
C      WRITE(*,*) '  MNTMBD ISB,JSB',ISB,JSB,IJUMP
      CALL MNTMBD(JUMP,IJUMP,ISB,JSB,ARJ,AII,I,J,UBJ,VBJ,
     1   FXB,FYB,NCATG,CSHLTR,NPLS)
      GO TO 560
C        THREE MOMENTUM POINTS MUST BE CHECKED FOR COMPUTATIONS FOR
C          CORNER POINTS.
C        B   *                              *    B
C      L O   *                              *    O
C      E U   *                              *  R U
C      F N  1.     .(I,J)         (I,J).    .4 I N
C      T D   *                              *  G D
C        A   *  +(I,J-1)            (I,J) + *  H A
C        R   *                              *  T R
C        Y  2.*****.****  BOUNDARY ****.****.3   Y
C                  3                    2
C
 600  DO 610 KK=1,3
      K=ISHF(KK,ICOR)
      ISB=I+IH(ICOR)+IP(K)
      JSB=J+JH(ICOR)+JP(K)
C        IF AT (I,J),TRANSPORTS ARE ZERO,SET TRANSPORTS AT BOUNDY ZEROS.
      IF(UB(I,J).EQ.0.) GOTO 630
C
      IF(ITREE(ISB,JSB).EQ.'6'.OR.ITREE(ISB,JSB).EQ.'4') GO TO 560
      IF(ITREE(ISB,JSB).EQ.'8' ) IJUMP=2
      CALL MNTMBD(JUMP,IJUMP,ISB,JSB,ARJ,AII,I,J,UBJ,VBJ,
     1   FXB,FYB,NCATG,CSHLTR,NPLS)
      GOTO 610
 630  UB(ISB,JSB)=0.
      VB(ISB,JSB)=0.
 610  CONTINUE
C -------------------------------------------------------------------
 560  CONTINUE
 570  CONTINUE
 580  CONTINUE
C       FOR CIRCULAR ISLAND, PERIODIC BOUNDARY CONDITIONS ARE USED.
      IF (DOLLAR.EQ.'$') THEN
        DO 700 I=1,IMXB
        UB(I,1)=UB(I,JMXB)
 700    VB(I,1)=VB(I,JMXB)
       ENDIF
      RETURN
       END
