      MODULE PARM2
      INTEGER,DIMENSION(:,:),ALLOCATABLE :: IMANN
      CHARACTER*1,DIMENSION(:,:),ALLOCATABLE :: ITREE
      CHARACTER*1,DIMENSION(:,:),ALLOCATABLE :: KSKP
      INTEGER*2,DIMENSION(:,:),ALLOCATABLE :: IHMX
      REAL,DIMENSION(:,:),ALLOCATABLE :: HSUB
C      REAL,DIMENSION(:,:),ALLOCATABLE :: HMX
      END MODULE PARM2
