      SUBROUTINE SETCMP
C        JELESNIANSKI    SEPTEMBER 1980 TDL   IBM 360/195
C
C        PURPOSE
C           THIS SUBROUTINE (SETCMP) SETS UP THE FIRST HOURLY
C           METEOROLOGICAL AND TRACK DATA FOR COMPUTATIONS. IT ALSO
C           SETS CHANGES IN DATA FOR THE FIRST INCREMENTAL TIME STEP.
C
C        DATA SET USE
C
C        VARIABLES
C             ITIME = NUMBER OF TIME STEPS; INITIALIZED TO ZERO
C            NDLTHR = NUMBER OF TIME STEPS IN ONE HOUR
C             HHRAD = ACCUMULATIVE TIME STEPS ON THE HOUR
C             IBGNT = TABULATED SUBSCRIPT FOR STORM INITIALIZATION
C           PT(100) = HOURLY PRESSURE DROPS
C             PDROP = DUMMY VALUE FOR 1ST HOUR PRESSURE DROP
C       YDELP ZDELP = PRESSURE DROP AT PRESENT  TIME STEP
C                PN = PRESS DROP AT PRESENTS TIME
C               PNN = PRESS DROP AT PREVIOUS TIME
C            R(100) = HOURLY STORM SIZES
C              YC24 = STORM SIZE AT PRESENT  TIME STEP
C              ZC24 = STORM SIZE AT PREVIOUS TIME STEP
C               C21 = DUMMY VALUE FOR SPEED OF STORM IN MPH, 1ST HOUR
C                     C21 INITIALLY SET IN 'INTVAL'
C            X12(7) = SPEED OF STORM IN FT/SEC, 1ST HOUR
C   X12(20) X12(21) = DIRECTIONS OF STORM MOTION FOR 1ST HR, SET IN 'INTVAL'
C    X12(9) X12(10) = COMPONENTS OF FORWARD SPEED, 1ST HOUR
C              DELT = UNIT TIME STEP
C   X12(11) X12(12) = COMPONENTS OF STORM MOTION UNIT TIME STEP, 1ST HOUR
C               C22 = DIRECTION OF STORM MOTION, 1ST HR, SET IN 'INTVAL'
C           X12(17) = FRICTION COEFFICIENT (3X10-6) TIMES SQUARE OF STORM SIZE
C   X12(23) X12(24) = COMPONENTS OF WIND DISTORTION (LAKE WINDS), 1ST HR
C            PTENCY = CHANGE IN PRESSURE DROP FOR 1ST HOUR
C            RTENCY = CHANGE IN STORM SIZE    FOR 1ST HOUR
C            ITMADV = COUNTER FOR HOURLY TIME, 1ST HOUR
C             AX AY = COMPONENTS OF TOTAL STORM TRAVERSE WITH TIME
C           WMAX(2) = MAX WIND SPEED OVER INLAND WATER BODIES OR OCEAN
C          W1218(2) = TWICE THE MAXIMUM WINDS (LAKE OR OCEAN)
C     C(800) S(800) = COS/SIN OF INFLOW ANGLE, MILE INTERVALS FROM
C                     STORM CENTER (SEA WINDS), COMPUTED IN 'FORCE1'
C   CW(800) SW(800) = COS/SIN INFLOW ANGLE (LAKE WINDS), FROM 'FORCE1'
C
C        GENERAL COMMENTS
C           THIS SUBROUTINE RESIDES IN OVERLAY 'CMPUTE'. IT IS CALLED
C            IN ONLY ONCE BY SUBROUTINE 'CMPUTE'. IT CALLS IN 2
C            SUBROUTINES, 'FORCE1' AND 'INTLHT'.
C
C      COMMON /SLAT/   FSOUTH
      COMMON /FFTH/   ITIME,MHALT
      COMMON /DUMB3/  IMXB,JMXB,IMXB1,JMXB1,IMXB2,JMXB2
      COMMON /DELTH/  NDLTHR,NDLTH2,DLTHR,DLTH2
C STIME interferes with C code, so switched to STIME2
      COMMON /STIME2/  ISTM,JHR,ITMADV,NHRAD,IBGNT,ITEND
      PARAMETER (NT_=999)
      COMMON /STRMPS/ X(NT_),Y(NT_),PT(NT_),R(NT_),DIR(NT_),SP(NT_)
      COMMON /SPLN/   ALT(15),ALN(15),DUMX(15),DUMY(15),RL(15),ANGD(15),
     1                PDUM(15),RDUM(15),XLAT(NT_),YLONG(NT_),RLNGTH
      COMMON /FRST/   X1(50),X12(50)
      COMMON /EGTH/   DELS,DELT,G,COR
      COMMON /TMEREL/ TREAL
      COMMON /BSN/    PHI,ALTO,ALNO,PHI1,ALT1,ALN1,ALT1C
      COMMON /ZLATO/  ZLATO
      COMMON /THRD/   C7,C17,C19,C25
      COMMON /STRMSB/ C1,C2,C21,C22,AX,AY,PTENCY,RTENCY
      COMMON /WTEMP/  YDELP,ZDELP,PNN,YC24,ZC24
      COMMON /DUMY44/ SW(800),CW(800),W1218(2),WMAX(2)
      COMMON /DUMMY4/ S(800),C(800),P(800),DELP(800)
C
C     CHARACTER*40    FILNAM
C      CHARACTER*80    DUM
C
C         SET START TIME TO 0
C         NUMBER OF UNIT TIME STEPS FOR THE 1ST HOUR
      ITIME=0
C        REAL TIME IN SECONDS
      TREAL=0.
      NHRAD=NDLTHR
C
C        PREPARATORY VALUES TO UPDATE STORM FOR EACH MB CHANGE
C        IN PRESSURE DROP, AND FOR EACH MILE CHANGE IN STORM SIZE
C        INITIALIZE (X,Y) STORM POSITION, STORM SPEED AND DIRECTION,
C        STORM SIZE, PRESSURE DROP
      AX=0.
      AY=0.
      C1=X(IBGNT)*5280.
      C2=Y(IBGNT)*5280.
      X12(49)=C1
      X12(50)=C2
      ZLATO=XLAT(IBGNT)
      C21=SP(IBGNT)
      C22=DIR(IBGNT)
C
      PDROP=PT(IBGNT)
      YDELP=PT(IBGNT)
      ZDELP=PT(IBGNT)
      YC24=R(IBGNT)
      ZC24=R(IBGNT)
      X12(20)=COS(C22)
      X12(21)=SIN(C22)
C
C        1ST HR SPEED OF STORM IN FT/SEC
      X12(7)=C21*44./30.
C
C        1ST HR COMPONENT SPEED OF STORM IN FT/SEC
      X12(9) =X12(7)*X12(20)
      X12(10)=X12(7)*X12(21)
C
C        1ST HR COMPONENT MOVEMENT OF STORM FOR 1 TIME INTERVAL
      X12(11)=DELT*X12(9)
      X12(12)=DELT*X12(10)
C
      X12(23)=X12(7)*COS(C22+2.*3.14159265358979323846/3.)
      X12(24)=X12(7)*SIN(C22+2.*3.14159265358979323846/3.)
C        COMPUTE WIND DISTORTION COEFFICIENT FOR LAKE WINDS, 1ST HR
C        DISTORTION IS A FUNCTION OF STORM'S FORWARD SPEED
C
C        FSOUTH=-1. FOR SOUTHERN HEMISPHERE, CLOCKWISE CIRCULATION;
C              = 1. FOR NORTHERN HEMISPHERE, COUNTER-CLOCKWISE CIRCULATION.
C      X12(23)=X12(7)*COS(C22+FSOUTH*2.*3.14159265358979/3.)
C      X12(24)=X12(7)*SIN(C22+FSOUTH*2.*3.14159265358979/3.)
C
C         INCREMENTAL CHANGE, PER TIME STEP, FOR PRESSURE DROP
C         AND STORM SIZE
      PTENCY=(PT(IBGNT+1)-PT(IBGNT))/NDLTHR
      RTENCY=(R(IBGNT+1)-R(IBGNT))/NDLTHR
C
C        ADVANCE 1ST HOUR SUBSCRIPT
      ITMADV=IBGNT+1
C
C         X/Y-COMP OF STORM TRAVERSE FOR FIRST UNIT OF TIME
C         RECORD STORM POSITIONS AT ANY TIME IN (X,Y) PLANE (FT)
CC      Arthur 6/8/2012 ... Don't time-step the positions here.
CC          We're initializing variables here so time-step should
CC          be done in STMVAL otherwise we have a double step at beginning.
CC          For Betsy this resulted in a change of position of next to last
CC          point from "09/10/1965 12:00:00 (31.900293, 92.113121)"
CC                  to "09/10/1965 12:00:00 (31.899822, 92.109535)"
CC           should be "09/10/1965 12:00:00 (31.900000, 92.110000)"
CC      AX=AX+X12(11)
CC      AY=AY+X12(12)
      X12(49)=C1+AX
      X12(50)=C2+AY
C
C         UPDATED PRESS DROP, AND STORM SIZE, FOR UNIT TIME INTERVAL
CC      Arthur 6/8/2012 ... Don't time-step the delp/rmax here.
CC          We're initializing variables here so time-step should
CC          be done in STMVAL otherwise we have a double step at beginning.
CC      YDELP=YDELP+PTENCY
CC      YC24 =YC24 +RTENCY
      PN=YDELP
      PNN=PN
C
C         1ST HR OR FIRST UNIT OF TIME FOR APPROX OF MAX WINDS
C         HYDROSTATIC PRESSURE P(I) WILL BE USED FOR OPEN OCEAN.
      IPRT=0
C         OBTAIN INITIAL GUESS OF MAX WIND FROM PRESSURE
C         NCATG=1  FOR LAKE WINDS, =2 FOR OCEAN.
      CALL INTWND(YDELP,YC24,ZLATO,VMAX)
CC      write (*,*) ' ydelp yc24 alto vmax',YDELP,YC24,ALTO,VMAX
      WMAX(2)=VMAX
      WMAX(1)=VMAX*.85
      DO 120 NCATG=1,2
      VMAX=WMAX(NCATG)
      CALL FORCE1(YDELP,YC24,VMAX,ZLATO,NCATG,IPRT)
C         SAVE VMAX'S FOR LAKE/OCEAN FOR NEXT INITIAL GUESSES
      WMAX(NCATG)=VMAX
C      TWICE MAX WINDS IN FT/SEC
      W1218(NCATG)=2.*VMAX*44./30.
      IF (NCATG.EQ.1) THEN
      DO 110 I=1,800
      SW(I)=S(I)
 110  CW(I)=C(I)
      ENDIF
 120  CONTINUE
C      R IN FEET
      X12(4) =YC24*5280.
      X12(15)=X12(4)*X12(4)
      X12(17)=C19*X12(15)
      RETURN
       END
