      SUBROUTINE SMPT2G
C        J. CHEN , AUG 22 1984            TDL   IBM 360/195
C        PURPOSE
C           TO COLLECT MOMENTUM GRID POINTS AJACENT TO ANY INTERIOR
C           BOUNDARIES (U=V=0) THEN CONVERT TO HEIGHT POINTS.
C           REPETITION IS AVOIDED. SPECIAL POINTS, ONE OF TH 4 IS
C           DRY, ARE TAGGED AS 888. FOR HEAVIER SMOOTHING.
C           CALL SUBROUTINE 'FLT2G' FOR SMOOTHING.
C        DATA SET USE
C           NONE
C        VARIABLES
C           HSUB( , ) = TEMPORARY STORAGE SPACE FOR HEIGHT FIELD
C
      USE PARM2
      INCLUDE 'parm.for'

C     MCT_ set to 8000  06/09/10
      PARAMETER (MCT_=8000)
C      PARAMETER (MCT_=1500)
C
      COMMON /FLWCPT/ NSQRS,NSQRW,NSQRWC,NPSS,NCUT
      COMMON /DUMB3/  IMXB,JMXB,IMXB1,JMXB1,IMXB2,JMXB2
      COMMON /SM2G/   MM2G,MCMX,I2G(M2G_),J2G(M2G_)
      COMMON /DUMB8/  IP(4),JP(4),IH(4),JH(4)
      COMMON /DUM88/  IIH(4),JJH(4),IHH(4),JHH(4)
      COMMON /FFTH/   ITIME,MHALT
      INTEGER*2       MM2G,MCMX,I2G,J2G
      INTEGER*2       MCT(MCT_),I2GG(MCT_),J2GG(MCT_)
      M=0
      DO 10 J=2,JMXB2
      DO 10 I=2,IMXB2
      IF (UB(I,J).EQ.0..OR.ZBM(I,J).LE.-30.) GOTO 10
      IF (UB(I-1,J  ).EQ.0.) GOTO 20
      IF (UB(I  ,J-1).EQ.0.) GOTO 20
      IF (UB(I  ,J+1).EQ.0.) GOTO 20
      IF (UB(I+1,J  ).EQ.0.) GOTO 20
      GOTO 10
 20   IF (M+1.GE.M2G_) GOTO 22
      M=M+1
      I2G(M)=I
      J2G(M)=J
 10   CONTINUE
      GOTO 23
C
 22   CONTINUE
CC      WRITE(*,998)I2G(M),J2G(M)
 998  FORMAT(' TOTAL MOMN. POINTS FOR SMOOTHING REACHES 3000.',
     1 ' LAST I,J =',2I8)
      STOP
C      SAVE THE TOTAL COUNT OF CORNER MOMN. POINTS
 23    MM2G=M
C      write (*,*) "num momn points for smooth", mm2g
C
      DO 100 J=1,JMXB1
      DO 100 I=1,IMXB1
C
C       COLLECT MOMNTURMUMTURM POINTS NEXT TO THE INTERIOR BOUNDARY OF
C       COMPUTATIONS
 100  HSUB(I,J)=999.
C
      MC=0
      DO 120 M=1,MM2G
      II=I2G(M)
      IF(II.LE.1.OR.II.GE.IMXB) GO TO 120
      JJ=J2G(M)
      IF(JJ.LE.1.OR.JJ.GE.JMXB) GO TO 120
      DO 110 K=1,4
      I=II+IH(K)
      J=JJ+JH(K)
      IF(HB(I,J)+ZB(I,J).EQ.0.) GO TO 112
      HSUB(I,J)=HB(I,J)
      GO TO 110
 112  IF(MC+1.GE.MCT_) GO TO 113
      MC=MC+1
      MCT(MC)=M
 110  CONTINUE
 120  CONTINUE
      GOTO 125
 113  CONTINUE
CC      WRITE(*,997) I2G(M),J2G(M)
 997  FORMAT(' TOTAL SPECIAL CORNER POINTS (MOMN) REACHES 1500.',
     1 ' LAST I,J =',2I8)
       STOP
 125   MCMX=MC
C      write (*,*) "num special corner points smooth", mcmx
C
      IF(MCMX.EQ.0) GO TO 115
      DO 114 M=1,MCMX
      MM=MCT(M)
      II=I2G(MM)
      JJ=J2G(MM)
      DO 116 K=1,4
      I=II+IH(K)
      J=JJ+JH(K)
      IF(HB(I,J)+ZB(I,J).EQ.0.) GO TO 116
      HSUB(I,J)=888.
 116  CONTINUE
 114  CONTINUE
 115  CONTINUE
C
      IF(NSQRW.EQ.0) GO TO 124
      DO 122 L=1,NSQRW
      IF(F1DACT(L).EQ.'T') GO TO 122
      I=ISQR(L)
      IF(I.LE.1.OR.I.GE.IMXB1) GO TO 122
      J=JSQR(L)
      IF(J.LE.1.OR.J.GE.JMXB1) GO TO 122
      IF(HSUB(I,J).EQ.999.) GO TO 122
      K=ISIDE(L)
      II=I+IHH(K)
      JJ=J+JHH(K)
      IF(HSUB(II,JJ).EQ.999.) GO TO 122
      IF(HSUB(I,J).LE.(ZBMIN(L)+1.)) GO TO 123
      IF(HSUB(II,JJ).LE.(ZBMIN(L)+1.)) GO TO 123
      GO TO 122
 123  HSUB(I,J)=888.
      HSUB(II,JJ)=888.
 122  CONTINUE
 124  CONTINUE
      M=0
      MM=0
      DO 130 J=1,JMXB1
      DO 130 I=1,IMXB1
      IF(HSUB(I,J).EQ.999.) GO TO 130
      IF(HSUB(I,J).EQ.888.) GO TO 132
      IF(M+MM.GE.M2G_) GO TO 140
      M=M+1
      I2G(M)=I
      J2G(M)=J
      GO TO 130
 132  IF(MM.GE.MCT_) GO TO 140
      MM=MM+1
      I2GG(MM)=I
      J2GG(MM)=J
 130  CONTINUE
 140  MM2G=M
      MCMX=MM
      IF (MM2G.GE.M2G_) THEN
       WRITE(*,1998) M2G_,I2G(M),J2G(M)
 1998  FORMAT(' TOTAL HGHT. POINTS FOR SMOOTHING REACHES MAX.',I8,
     1 ' LAST I,J =',2I8)
      STOP
      ENDIF
      IF (MCMX.GE.MCT_) THEN
      WRITE(*,1997) MCT_,I2G(M),J2G(M)
 1997 FORMAT(' TOTAL SPECIAL CORNER POINTS (HGHTS) REACHES MAX.',I8,
     1 ' LAST I,J =',2I8)
      STOP
      ENDIF
C
      IF(MCMX.EQ.0) GO TO 400
      DO 310 M=1,MCMX
      I2G(M+MM2G)=I2GG(M)
      J2G(M+MM2G)=J2GG(M)
 310  CONTINUE
 400  CONTINUE
C
C      write (*,*)'  itime = ',ITIME
C      WRITE(*,150)MM2G,MCMX
C 150  FORMAT('  TOTAL NO OF SQUARES FOR SMOOTHING = ',I10,' + ',I10)
C      WRITE(*,332)MCMX
C 332  FORMAT('   TOTAL SPECIAL CORNER POINTS=',I7,' I AND J =')
c     PRINT 333,(I2GG(M),M=1,MCMX)
c     PRINT 333,(J2GG(M),M=1,MCMX)
C 333  FORMAT (40I3)
c
      CALL FLT2G
      RETURN
        END
