      SUBROUTINE SNAPSH
C       CONVERT SURGE ENVELOP DATA WITH 999 FOR DRY SQUARES SO THAT ZB()
C       CAN BE FREE FROM THE MEMORY.
      INCLUDE 'parm.for'
C
      COMMON /IDENT/  AIDENT(40),DACLOK(7)
      COMMON /GPRT1/  DOLLAR,EBSN
      COMMON /SWTCH/  IOPERL(5)
      COMMON /DUMB3/  IMXB,JMXB,IMXB1,JMXB1,IMXB2,JMXB2
      CHARACTER*2     DOLLAR
      CHARACTER*1     EBSN
C        REPLACE HMX BY 999 IF THE SQUARE IS DRY.
       DO 1 J=1,JMXB
       DO 1 I=1,IMXB
        IF (HB(I,J)+ZB(I,J).EQ.0) THEN
         IHMX(I,J)=999
         ELSE
         IHMX(I,J)=HB(I,J)*10.+.5
         ENDIF
  1    CONTINUE
C
C      WRITE(77) IMXB,JMXB
C      WRITE(77) AIDENT
C      WRITE (77) ((IHMX(I,J),I=1,IMXB),J=1,JMXB)
C
      IF (DOLLAR.EQ.'2$') THEN
      DO  20 J=1,JMXB
      DO  20 I=1,IMXB
      IF (IHMX(I,J).EQ.999) GOTO 20
      IHMX(I,J)=(HMX(I,J)-ZSUB(J))*10.+.5
 20   CONTINUE
      ENDIF
C
      IF(IOPERL(1).NE.2) THEN
      NGRP=(JMXB1-1)/25+1
      DO 1130 NN=1,NGRP
      J1=1+(NN-1)*25
      J2=J1+MIN0(24,JMXB1-J1  )
CC      WRITE(*,180)(J,J=J1,J2)
 180  FORMAT(/I6,26I5)
C
C      DO 1120 I=1,IMXB1
CC      WRITE(*,'(1H ,I2,26I5)') I,(IHMX(I,J),J=J1,J2)
C 1120  CONTINUE
 1130  CONTINUE
       ENDIF
C
       RETURN
       END
