      SUBROUTINE STMVAL
C        JELESNIANSKI   SEPTEMBER 1980 TDL   IBM 360/195
C
C        PURPOSE
C           THIS SUBROUTINE (STMVAL) TESTS FOR INCREMENTAL HOURS AND
C           SETS HOURLY TRACK AND METEOROLOGY VALUES. IT TESTS FOR 1-MB
C           CHANGE IN PRESSURE DROP, OR 1 MILE CHANGE IN STORM SIZE,
C           FOR EACH ADVANCE IN TIME. PREPARATORY VALUES ARE SET FOR
C           LATER ADVANCING IN TIME.
C
C        DATA SET USE
C           NONE
C
C        VARIABLES
C             ITIME = CUMULATIVE TIME COUNTER
C                N1 = TIME STEPS AT HOURLY INTERVALS, SET IN 'SETCMP'
C            NDLTHR = NUMBER OF TIME STEPS IN ONE HOUR
C            ITMADV = COUNTER FOR HOURLY TIME, SET IN 'SETCMP'
C               C22 = DUMMY VALUE FOR HOURLY DIRECTION OF STORM MOTION
C          DIR(100) = HOURLY DIRECTION OF STORM MOVEMENT
C   X12(20) X12(21) = DIRECTIONS OF STORM MOTION, HOURLY VALUE
C           SP(100) = HOURLY FORWARD SPEED OF STORM
C               C21 = DUMMY VALUE FOR STORM'S HOURLY FORWARD SPEED
C            X12(7) = SPEED OF STORM IN FT/SEC, HOURLY VALUES
C    X12(9) X12(10) = COMPONENTS OF FORWARD STORM SPEED
C              DELT = UNIT TIME STEP
C   X12(11) X12(12) = STORM MOVEMENT IN X/Y-DIR FOR UNIT TIME STEP
C           X12(17) = FRICTION COEFFICIENT (3X10-6) TIMES SQUARE OF STORM SIZE
C           PT(100) = HOURLY PRESSURE DROPS
C            R(100) = HOURLY STORM SIZES
C            PTENCY = CHANGE IN PRESSURE DROP FOR ONE HOUR
C            RTENCY = CHANGE IN STORM SIZE    FOR ONE HOUR
C              YC24 = STORM SIZE FOR PRESENT TIME
C             YDELP = PRESSURE DROP FOR PRESENT TIME
C             AX AY = COMPONENTS OF TOTAL STORM TRAVERSE WITH TIME
C             ZDELP = PRESSURE DROP AT PREVIOUS MB. STEP
C                PN = INTEGER VALUE OF PRESS DROP AT PRESENT TIME
C               PNN = INTEGER VALUE OF PRESS DROP AT PREVIOUS TIME
C           WMAX(2) = MAX WIND SPEED OVER INLAND WATER BODIES OR OCEAN
C             IGBNT = SUBSCRIPT FOR STORM INITIALIZATION
C               JHR = SUBSCRIPT FOR NEAREST STORM APPROACH
C              ZC24 = STORM SIZE AT PREVIOUS MILE STEP
C              VMAX = DUMMY VALUE FOR MAXIMUM WINDS
C          W1218(2) = TWICE THE MAXIMUM WINDS (LAKE OR OCEAN)
C     C(800) S(800) = COSINE-SINE OF INFLOW ANGLE, MILE INTERVALS FROM
C                     STORM CENTER (SEA WINDS)
C   CW(800) SW(800) = COSINE-SINE OF INFLOW ANGLE (LAKE WINDS)
C  ISTMAP MAPIN(10) = PRINT OUT TIME FOR SNAPSHOTS, SET IN 'BLCKDT'
C                     AND RECONDITIONED IN 'INTVAL'
C            NUMBER = SUBSCRIPT FOR PRINT-OUT OF ABOVE, SET IN 'INTVAL'
C             IPRHR = 1,WHEN ON THE HOUR; 2, WHEN HALF HOUR IN BETWEEN;
C                     3, OTHERWISE
C            IPRTSV = TIME TO SAVE HISTORICAL SURGES, 10 POINTS, SET 'INTVAL'
C            IPRTAD = UPDATE TIME OF IPRTSV, SET IN 'INTVAL'
C            IOPERL = 2 IF IN OPERATIONAL MODE
C
C        GENERAL COMMENTS
C           THIS SUBROUTINE RESIDES IN OVERLAY 'CMPUTE'. IT IS CALLED
C           IN BY SUBROUTINE 'CMPUTE'.
C
C      COMMON /SLAT/   FSOUTH
      include 'parm.for'
      COMMON /KEYS/   KEY1
      COMMON /FFTH/   ITIME,MHALT
      COMMON /WTEMP/  YDELP,ZDELP,PNN,YC24,ZC24
      COMMON /BSN/    PHI,ALTO,ALNO,PHI1,ALT1,ALN1,ALT1C
      COMMON /ZLATO/  ZLATO
      COMMON /DELTH/  NDLTHR,NDLTH2,DLTHR,DLTH2
      COMMON /FRST/   X1(50),X12(50)
      COMMON /EGTH/   DELS,DELT,G,COR
      COMMON /THRD/   C7,C17,C19,C25
      COMMON /STRMSB/ C1,C2,C21,C22,AX,AY,PTENCY,RTENCY
      PARAMETER (NT_=999)
      COMMON /STRMPS/ X(NT_),Y(NT_),PT(NT_),R(NT_),DIR(NT_),SP(NT_)
      COMMON /SPLN/   ALT(15),ALN(15),DUMX(15),DUMY(15),RL(15),ANGD(15),
     1                PDUM(15),RDUM(15),XLAT(NT_),YLONG(NT_),RLNGTH
C STIME interferes with C code, so switched to STIME2
      COMMON /STIME2/  ISTM,JHR,ITMADV,NHRAD,IBGNT,ITEND
      COMMON /TMEREL/ TREAL
      COMMON /PRHSY/  IPRHR,JUMPR,IPRT
      COMMON /DUMY44/ SW(800),CW(800),W1218(2),WMAX(2)
      COMMON /DUMMY4/ S(800),C(800),P(800),DELP(800)
      COMMON /MAPTME/ ISTMAP,IADMAP
      COMMON /DELH11/ MAPIN(10),NUMBER
      COMMON /PRTSV/  IPRTSV,IPRTAD
      COMMON /DLTDTA/ DLTIN(3),DLTB
      COMMON /SWTCH/  IOPERL(5)
C
C
C        TEST FOR INCREMENTAL HOURLY CHANGES IN STORM TRACK
C        The -1 is needed to make sure that the shift from one time-step to
C        another occurs on the hour, rather than one time-step before the hour
C        The first time-step (ITIME) past the hour is when the new delt-t kicks
C        in.
      IF(HTSTRT) GO TO 101
      IF(ITIME-1.NE.NHRAD) GO TO 100
 101  CONTINUE
C        PRINTOUT SELECTED HOURS FOR SNAPSHOT SURGES
      IF (ITMADV.NE.MAPIN(NUMBER)) GO TO 20
      CALL SNAPSH
      NUMBER=NUMBER+1
  20  CONTINUE
C
C        TEST TO REDUCE DELT-T BEFORE NEAREST APPROACH
C        FOR WEAK STORM,THERE IS NO CHANGE OF DELT-T.
C        FOR MEDIUM AND STRONG STORMS, REDUCE DELT-T ONE STEP 3 HR BEFORE
C        THE NEAREST APPROACH.
C        FOR STRONG STORMS, REDUCE DELT-T FURTHER AT NEAREST APPROACH.
C        RETURN TO INTERMEDIATE TIME STEP 3 HR AFTER NEAREST APPROACH.
      IF (DLTB.EQ.DLTIN(1)) GO TO 300
      IF(ITMADV.NE.JHR-6) GO TO 143
      DELT1 =DLTIN(2)
      GO TO 144
 143  IF(ITMADV.NE.JHR) GO TO 300
      IF (DLTB.EQ.DLTIN(2)) GO TO 300
      DELT1=DLTIN(3)
 144  CONTINUE
C
C        RECOMPUTE THE PARAMETERS DEPENDING ON TIME STEP AS DELT-T CHANGED
      MHALT=(ITIME-1)+(MHALT-(ITIME-1))*DELT/DELT1 + .01
      DELT=DELT1
      NDLTHR=3600./(DELT-.001)
      IPRTSV=IPRTSV-IPRTAD
      IPRTAD=NDLTHR/4
      IF(MOD(NDLTHR,6).EQ.0) IPRTAD=NDLTHR/6
      IPRTSV=IPRTSV+IPRTAD
CC      WRITE(*,55)DELT,ITIME
 55   FORMAT('  DELT NOW CHANGED TO ',F10.1,' AT TIME STEP',I8)
      CALL CNSDLT
 300  CONTINUE
C
      NHRAD=NHRAD+NDLTHR
      ZLATO=XLAT(ITMADV)
      C22=DIR(ITMADV)
      X12(20)=COS(C22)
      X12(21)=SIN(C22)
C
C        SPEED OF STORM IN FT/SEC
      C21=SP(ITMADV)
      X12(7) =C21*44./30.
C
C        COMPONENT SPEED OF STORM IN FT/SEC
      X12(9) =X12(7)*X12(20)
      X12(10)=X12(7)*X12(21)
C
C        COMPUTE MOVEMENT OF STORM, FOR 1 TIME INTERVAL, DURING 1 HR INTERVAL
      X12(11)=DELT*X12(9)
      X12(12)=DELT*X12(10)
C
C        COMPUTE WIND DISTORTION COEFFICIENT FOR LAKE WINDS
C        DISTORTION IS A FUNCTION OF STORM'S FORWARD SPEED
      X12(23)=X12(7)*COS(C22+2.*3.14159265358979323846/3.)
      X12(24)=X12(7)*SIN(C22+2.*3.14159265358979323846/3.)
C
C        FSOUTH=-1. FOR SOUTHERN HEMISPHERE, CLOCKWISE CIRCULATION;
C              = 1. FOR NORTHERN HEMISPHERE, COUNTER-CLOCKWISE CIRCULATION.
C      X12(23)=X12(7)*COS(C22+FSOUTH*2.*3.14159265358979/3.)
C      X12(24)=X12(7)*SIN(C22+FSOUTH*2.*3.14159265358979/3.)
      RTENCY=(R(ITMADV+1)-R(ITMADV))/NDLTHR
      PTENCY=(PT(ITMADV+1)-PT(ITMADV))/NDLTHR
      YC24 =R(ITMADV)
      YDELP=PT(ITMADV)
C
C     ADVANCE HOUR COUNT BY ONE FOR NEXT HOUR
      ITMADV=ITMADV+1
C
C        TEST FOR INCREMENTAL UNIT TIME CHANGES IN TRACK AND METEOROLOGY
C        X/Y-COMPONENT OF TOTAL STORM TRAVERSE WITH ADVANCING TIME
 100  AX=AX+X12(11)
      AY=AY+X12(12)
C
      TREAL=TREAL+DELT
C         UPDATED PRESSURE DROP, AND STORM SIZE, FOR UNIT TIME INTERVAL
      YDELP=YDELP+PTENCY
      YC24=YC24+RTENCY
C
C        JUMPR=2, CALCULATE A STORM FOR PRINTING OUT PROFILES.
C        NO STORM PRINTOUT UNLESS AT NEAREST APPROACH OR LANDFALL.
      IF(JUMPR.GE.2) GO TO 250
      IF (ITMADV.EQ.JHR+1) GO TO 200
      GO TO 250
 200  JUMPR=2
      IPRT=1
C       REDUCE PRINTOUT IF IN OPERATIONAL MODE.
      IF(IOPERL(1).EQ.2) JUMPR=3
      GO TO 110
 250  CONTINUE
C
C          CHECK IF STORM HAS CHANGED BY 1-MB, OR SIZE BY 1 MILE,
C          AS TIME ADVANCES; IF SO, APPROXIMATE MAX WIND
C          FOR INPUT TO CREATE A NEW STORM
      if (key1.eq.0) goto 170
      IF(HTSTRT)THEN
         HTSTRT = .FALSE.
         GO TO 110
      ENDIF
      IF(ABS(YDELP-ZDELP).GE.1.) GO TO 110
 120  IF(ABS(YC24-ZC24) .LT.1.) GO TO 170
 110  NP=YDELP*10.+.5
      PN=NP/10.
      CZ=SQRT(PN/PNN)
C
C        ENTERING WINDS FOR SUBROUTINE FORCE1
C        NCATG=1 FOR LAKE WINDS,   =2 FOR OCEAN WINDS
 130  DO 160 NCATG=1,2
      VMAX=WMAX(NCATG)*CZ
      IF (KEY1.NE.0) CALL FORCE1(PN,YC24,VMAX,ZLATO,NCATG,IPRT)
      WMAX(NCATG)=VMAX
      W1218(NCATG)=2.*VMAX*44./30.
C
      IF (NCATG.EQ.1) THEN
      DO 150 I=1,800
      SW(I)=S(I)
 150  CW(I)=C(I)
      ENDIF
 160  CONTINUE
C
      PNN=PN
      ZDELP=YDELP
      ZC24=YC24
C       PRINT OUT STORM PROFILES ONCE AT NEAREST APPROACH TIME
c      IF(IPRT.EQ.1) IPRT=0
C      R IN FEET
      X12(4) =YC24*5280.
      X12(15)=X12(4)*X12(4)
      X12(17)=C19*X12(15)
C
C      NO UPDATING STORM
 170  CONTINUE
      RETURN
       END
