      SUBROUTINE TMSTEP(IITIME,MMHALT,HHB,DDELT,XXLT,XXLG,YYDELP,YYC24,
     1WSPEED,WDIRCT,FLAG,FPASS,DMCLOCK,RESTART)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C THIS SUBROUTINE CALLS ALL THE FORTRAN SUBROUTINES WHICH ARE NEEDED TO
C DO ONE TIME STEP.
C
C ORIGINALLY THIS WAS DONE IN CMPUTE BETWEEN 100 AND 999.
C THE CODE IS THE SAME EXCEPT CUT AND PASTED HERE.
C
C THIS ALSO RETURNS TO C THE VARIOUS VARIABLES NEEDED SO THAT
C IT CAN UPDATE THE GRAPHICS.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      USE PARM2
      include 'parm.for'
      REAL HHB(M_,N_)
      INTEGER*2 FLAG,FPASS
      INTEGER*2 RESTART

      COMMON /GPRT2/  EBSN1,EBSN2
      CHARACTER*1  EBSN1,EBSN2
      COMMON /FFTH/   ITIME, MHALT
      COMMON /FLWCPT/ NSQRS,NSQRW,NSQRWC,NPSS,NCUT
      COMMON /OPTS/   NOFLD,NOF1D
      CHARACTER*1     NOFLD,NOF1D
      COMMON /PRHSY/  IPRHR,JUMPR,IPRT
      COMMON /PRTSV/  IPRTSV,IPRTAD
C STIME interferes with C code, so switched to STIME2
      COMMON /STIME2/  ISTM,JHR,ITMADV,NHRAD,IBGNT,ITEND
      COMMON /DELTH/  NDLTHR,NDLTH2,DLTHR,DLTH2
      COMMON /CESAV/  IPN(120),IPL(120),KHSPT
      COMMON /GPRT1/  DOLLAR,EBSN
      CHARACTER*1 EBSN
      CHARACTER*2 DOLLAR
      COMMON /EGTH/   DELS,DELT,G,COR
      COMMON /WTEMP/  YDELP,ZDELP,PNN,YC24,ZC24
      COMMON /STRMSB/ C1,C2,C21,C22,AX,AY,PTENCY,RTENCY
      COMMON /POLAR/  DEGREE,RMOUTH,AZMTH,DELA
      COMMON /DUMB3/  IMXB,JMXB,IMXB1,JMXB1,IMXB2,JMXB2
      COMMON /SMTH/   ISMTH
      COMMON /GPRT/   STA
      COMMON /TMEREL/ TREAL
      CHARACTER*16  STA

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C     ADDED FOR WAVE MODEL
C     4/2017 D.Y.
      REAL TMN,TWD,TIO,TWV,DTM,DTI,DTW
      IF (WAVE.EQ.1) THEN
C        IF(.NOT. HTSTRT)CALL WVSTEP(TREAL)
      ENDIF
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

C CODE TO IMPLEMENT ONE TIME STEP..
  100 INCSM=20
      IF (EBSN1.EQ.'+'.OR.EBSN1.EQ.'=') INCSM=1
      IF (EBSN1.EQ.'!'.OR.EBSN1.EQ.'#') INCSM=5
      IF (EBSN1.EQ.'@'.OR.EBSN1.EQ.'%') INCSM=10
      IF (EBSN1.EQ.'&') INCSM=20
      IF (EBSN1.EQ.'^'.OR.EBSN1.EQ.'*') INCSM=30
      ISMPT2G=1
      IF (EBSN1.EQ.'+') ISMPT2G=0
      IF (EBSN1.EQ.'&') ISMPT2G=0    
      IF (EBSN1.EQ.'#') ISMPT2G=0
      IF (EBSN1.EQ.'%') ISMPT2G=0
      IF (EBSN1.EQ.'*') ISMPT2G=0
      CALL TTIMER
      xtime=itime
c
c  continuity
c
C      CALL CPU_TIME(ELAPSE)
C      WRITE (*,*) "5a", ELAPSE
C      CALL TFLUSH
c
c     READ IN HOT START WATER LEVEL AND TRANSPORTATION D.Y 1/2018
      IF (HTSTRT)CALL HBUV_HS
      CALL CONTTY
C      CALL CPU_TIME(ELAPSE)
C      WRITE (*,*) "5b", ELAPSE
C      CALL TFLUSH
c
C       NO CORNER SMOOTHING for PNB BASIN
c

C      IF (EBSN1.EQ.'&'.or.EBSN1.EQ.'+') GOTO 113
      IF (ISMPT2G.EQ.0) GOTO 113
      IF (ITIME.GT.5.AND.INCSM.NE.1)  CALL SMPT2G
 113  CONTINUE
c
c
c
      CALL BDRYHT
      IF (NPSS.NE.0) CALL CHANNL
      IF (NSQRWC.NE.0.and.nof1d.ne.'+') CALL FLW1DM
      CALL HMXSV
C Create C-COPY OF HB TO HHB.. DO THIS RIGHT AFTER HMXSV
C HMXSV is where the envelope calculations are done, so
C we want them as close together as possible.
      IF(FPASS.EQ.1) THEN
        DO J=1,JMXB
          DO I=1,IMXB
C This is so that HHB is never greater than HMX
            IF (HMX(I,J).LT.HB(I,J)) THEN
              HHB(I,J)=HMX(I,J)
            ELSE
              HHB(I,J)=HB(I,J)
            ENDIF
          END DO
        END DO
      ENDIF
C
      IPRHR=3
      IF (ITIME.NE.IPRTSV) GO TO 180
      IF(ITIME.EQ.NHRAD) IPRHR=1
      IF(ITIME.EQ.NHRAD-NDLTHR/2) IPRHR=2
      IPRTSV=IPRTSV+IPRTAD
      IF (KHSPT.EQ.0) THEN
       CALL HISTRY
      ELSE
       IF (IPRHR.NE.3) CALL HSTRY2
      ENDIF
c
c
c    include 'cmpgr3.for'
c
  180 CONTINUE
C
C       IF (KEY1.EQ.0) GOTO 1112
C
c      IF(ITIME+1.EQ.NHRAD.or.EBSN1.EQ.'+') THEN
      IF(mod(ITIME+1,INCSM).EQ.0.or.EBSN1.EQ.'+') THEN
       IF(ISMTH.EQ.1) THEN
        IF (DOLLAR.EQ.'$') THEN
         CALL FLTER2
        ELSE
         CALL FILTER
        ENDIF
       ELSE
        IF (DOLLAR.EQ.'$') THEN
         CALL FLTER2
        ELSE
         IF (STA.EQ."CH2 (2008)") THEN
          CALL XFILTER(1)
         ELSE
          CALL XFILTER(2)
         ENDIF
        ENDIF
       ENDIF      
      ENDIF
c
c  momentum equation
c
C      CALL CPU_TIME(ELAPSE)
C      WRITE (*,*) "5j", ELAPSE
C      CALL TFLUSH
      CALL MOMNTM
      IF (WAVE.EQ.1) THEN
C        IF(HTSTRT)CALL WVSTEP(TREAL)
      ENDIF
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
c FOR HOT START, OUTPUT HB,UB,VB AND STORM POSITION/TIME INFO EVERY HALF HOUR
c 1/2018 D.Y
c      print *, ITIME
c      print *, ITMADV
c      print *, TREAL
c      print *, AX
c      print *, AY
c      print *, NHRAD
      IF (RESTART .EQ. 1) THEN
        IF (MOD(INT(TREAL),3600).EQ. 0)THEN
          print *, treal
          CALL RSTOUT(DMCLOCK)
        ENDIF
      ENDIF
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      CALL STMVAL
c
C GRAPHICS
C
c    include 'cmpgr2.for'
C
C END OF COMPUTE FOR ONE TIME STEP

C ARTHUR: PROCEDURE FOR CS.
C NOTE: ITMADV HAS BEEN ADVANCED FOR NEXT HOUR IN CALL TO STMVAL
      IF (FLAG.EQ.1) THEN
        CALL WAV
      ENDIF

C END CODE FOR ONE TIME STEP

C CODE TO RETURN TO C-CODE THE REST OF THE VALUES IT NEEDS.
      IITIME = ITIME
      MMHALT = MHALT
      DDELT = DELT
      YYDELP = YDELP
      YYC24 = YC24
      XA=(C1+AX)/5280.
      YA=(C2+AY)/5280.
      CALL XY2LLX(XA,YA,XXLT,XXLG)
      WSPEED=C21
C Direction is 0 for north. (I think this is meteorological direction)
C WDIRCT is returned in degrees.
      WDIRCT=(AZMTH-(C22)*180./3.14159265358979323846)
      RETURN
      END
