      SUBROUTINE TMSTP2
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C THIS SUBROUTINE CALLS ALL THE FORTRAN SUBROUTINES WHICH ARE NEEDED TO
C DO ONE TIME STEP.
C
C ORIGINALLY THIS WAS DONE IN CMPUTE BETWEEN 100 AND 999.
C THE CODE IS THE SAME EXCEPT CUT AND PASTED HERE.
C
C THIS ALSO RETURNS TO C THE VARIOUS VARIABLES NEEDED SO THAT
C IT CAN UPDATE THE GRAPHICS.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      include 'parm.for'

      COMMON /GPRT2/  EBSN1,EBSN2
      CHARACTER*1  EBSN1,EBSN2
      COMMON /FFTH/   ITIME, MHALT
      COMMON /FLWCPT/ NSQRS,NSQRW,NSQRWC,NPSS,NCUT
      COMMON /OPTS/   NOFLD,NOF1D
      CHARACTER*1     NOFLD,NOF1D
      COMMON /PRHSY/  IPRHR,JUMPR,IPRT
      COMMON /PRTSV/  IPRTSV,IPRTAD
C STIME interferes with C code, so switched to STIME2
      COMMON /STIME2/  ISTM,JHR,ITMADV,NHRAD,IBGNT,ITEND
      COMMON /DELTH/  NDLTHR,NDLTH2,DLTHR,DLTH2
      COMMON /CESAV/  IPN(120),IPL(120),KHSPT
      COMMON /GPRT1/  DOLLAR,EBSN
      CHARACTER*1 EBSN
      CHARACTER*2 DOLLAR
      COMMON /EGTH/   DELS,DELT,G,COR
      COMMON /WTEMP/  YDELP,ZDELP,PNN,YC24,ZC24
      COMMON /STRMSB/ C1,C2,C21,C22,AX,AY,PTENCY,RTENCY
      COMMON /POLAR/  DEGREE,RMOUTH,AZMTH,DELA
      COMMON /DUMB3/  IMXB,JMXB,IMXB1,JMXB1,IMXB2,JMXB2
      COMMON /SMTH/   ISMTH
      COMMON /GPRT/   STA
      CHARACTER*16  STA
!JWb
      COMMON /TM2/ ITM2
      ITM2=ITM2+1
!JWe

!C CODE TO IMPLEMENT ONE TIME STEP..
  100 INCSM=20
      IF (EBSN1.EQ.'+'.OR.EBSN1.EQ.'=') INCSM=1
      IF (EBSN1.EQ.'!'.OR.EBSN1.EQ.'#') INCSM=5
      IF (EBSN1.EQ.'@'.OR.EBSN1.EQ.'%') INCSM=10
      IF (EBSN1.EQ.'&') INCSM=20
      IF (EBSN1.EQ.'^'.OR.EBSN1.EQ.'*') INCSM=30
      ISMPT2G=1
      IF (EBSN1.EQ.'+') ISMPT2G=0
      IF (EBSN1.EQ.'&') ISMPT2G=0
      IF (EBSN1.EQ.'#') ISMPT2G=0
      IF (EBSN1.EQ.'%') ISMPT2G=0
      IF (EBSN1.EQ.'*') ISMPT2G=0
!      CALL TTIMER
!      xtime=itime
!c
c  continuity
      CALL CONTTY
!c
!C       NO CORNER SMOOTHING for PNB BASIN
!
      IF (ISMPT2G.NE.0.AND.ITM2.GT.5.AND.INCSM.NE.1)  CALL SMPT2G
!c
!c
!c
      CALL BDRYHT

      IF (NPSS.NE.0) CALL CHANNL
      IF (NSQRWC.NE.0.and.nof1d.ne.'+') CALL FLW1DM2

  180 CONTINUE
!C
!c      IF(ITIME+1.EQ.NHRAD.or.EBSN1.EQ.'+') THEN
!      IF(mod(ITIME+1,INCSM).EQ.0.or.EBSN1.EQ.'+') THEN
!JWb
      IF(mod(ITM2+1,INCSM).EQ.0.or.EBSN1.EQ.'+') THEN
!JWe
       IF(ISMTH.EQ.1) THEN
        IF (DOLLAR.EQ.'$') THEN
         CALL FLTER2
        ELSE
         CALL FILTER
        ENDIF
       ELSE
        IF (DOLLAR.EQ.'$') THEN
         CALL FLTER2
        ELSE
         IF (STA.EQ."CH2 (2008)") THEN
          CALL XFILTER(1)
         ELSE
          CALL XFILTER(2)
         ENDIF
        ENDIF
       ENDIF
      ENDIF
!c
!c  momentum equation
      CALL MOMNTM2
!C
!      CALL STMVAL
!C END OF COMPUTE FOR ONE TIME STEP
      RETURN
      END
