      PARAMETER (IDIM=1000,JDIM=1000)
      CHARACTER*80 FNAME,FGRID,FINPUT,FOUT,FINI,FBTH
      COMMON/CPARM/FNAME,FGRID,FINPUT,FOUT,FINI,FBTH
      COMMON/TPARM/DT,DTWIND,DTT,NHRS,NDTT
      COMMON/SPARM/LT0,LT1,LG0,LG1
      REAL LT0,LT1,LG0,LG1
      COMMON/DIRS/COSD(8),SIND(8),COSM2(8),SINM2(8),SINCO(8)
      COMMON/BISC/G,VK,RHOAIR,RHOH2O,GAMMA,CBF,EPS1,PI,WTPI
      COMMON/CONV/R2D,S2H,GTPI,COEFF0,COEFF,FAC2
      COMMON/SPAV/AC1,AC2,AC3,AC4,AC5,AC6
      COMMON/WNDD/PA,CALP,CBET,CDS,SPM,MPA,DELT
      REAL MPA
      COMMON/INPT/DS,DMIN,DDS,IM,JM,IMM1,JMM1,NSTEPS
      COMMON/INPV/D(IDIM,JDIM),DPTH(IDIM,JDIM),S(IDIM,JDIM)
      COMMON/ENGW/XXMOM1(IDIM,JDIM),XYMOM1(IDIM,JDIM),YYMOM1(IDIM,JDIM),
     1 YXMOM1(IDIM,JDIM),XXMOM2(IDIM,JDIM),XYMOM2(IDIM,JDIM),
     2 YYMOM2(IDIM,JDIM),YXMOM2(IDIM,JDIM)
      COMMON/ENGS/ERXX1(IDIM,JDIM),ERXY1(IDIM,JDIM),ERYY1(IDIM,JDIM),
     1 ERYX1(IDIM,JDIM),ERXX2(IDIM,JDIM),ERXY2(IDIM,JDIM),
     2 ERYY2(IDIM,JDIM),ERYX2(IDIM,JDIM)
      COMMON/FRQW/FXX1(IDIM,JDIM),FXY1(IDIM,JDIM),FYY1(IDIM,JDIM),
     1 FYX1(IDIM,JDIM),FXX2(IDIM,JDIM),FXY2(IDIM,JDIM),
     2 FYY2(IDIM,JDIM),FYX2(IDIM,JDIM)
      COMMON/FRQS/FRXX1(IDIM,JDIM),FRXY1(IDIM,JDIM),FRYY1(IDIM,JDIM),
     1 FRYX1(IDIM,JDIM),FRXX2(IDIM,JDIM),FRXY2(IDIM,JDIM),
     2 FRYY2(IDIM,JDIM),FRYX2(IDIM,JDIM)
      COMMON/WVLW/CXX1(IDIM,JDIM),CXY1(IDIM,JDIM),CYY1(IDIM,JDIM),
     1 CYX1(IDIM,JDIM),CXX2(IDIM,JDIM),CXY2(IDIM,JDIM),
     2 CYY2(IDIM,JDIM),CYX2(IDIM,JDIM)
      COMMON/WVNM/WNXX1(IDIM,JDIM),WNXY1(IDIM,JDIM),WNYY1(IDIM,JDIM),
     1 WNYX1(IDIM,JDIM),WNXX2(IDIM,JDIM),WNXY2(IDIM,JDIM),
     2 WNYY2(IDIM,JDIM),WNYX2(IDIM,JDIM)
      COMMON/MPID/XIDX(IDIM,JDIM),YIDX(IDIM,JDIM)
      INTEGER XIDX,YIDX
