      SUBROUTINE XY2LLX(XA,YA,XLT,XLG)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      COMMON /BSN/    PHI,ALTO,ALNO,PHI1,ALT1,ALN1,ALT1C
      REAL PHI,ALTO,ALNO,PHI1,ALT1,ALN1,ALT1C
      COMMON /ORIGN/  XMOUTH,YMOUTH
      REAL XMOUTH,YMOUTH

C PASSED PARAMETERS
      REAL XA,YA,XLT,XLG

C LOCAL VARIABLES
      REAL CLTO,SLTO,XCORD,YCORD,RLL,ENU,PSI,SPSI,CPSI,CNU
      REAL DLAT,DLONG

      CLTO=COS(ALT1C)
      SLTO=SIN(ALT1C)
      XCORD=(XA-XMOUTH)*5280./6080.21
      YCORD=(YA-YMOUTH)*5280./6080.21
      RLL=SQRT(XCORD**2+YCORD**2)
      IF (RLL.LT.1.E-5) THEN
        ENU=PHI1
      ELSE
        ENU=ATAN2(XCORD,YCORD)+PHI1
      ENDIF
      PSI=2.*ATAN(.5*RLL/3437.87)
      SPSI=SIN(PSI)
      CPSI=COS(PSI)
      CNU=COS(ENU)
      DLAT=ACOS(CLTO*CPSI+SPSI*SLTO*CNU)
      DLONG=ALN1-ATAN2(SPSI*SIN(ENU),CPSI*SLTO-SPSI*CNU*CLTO)
      XLT=90.-DLAT/1.74532925199433E-2
      XLG=DLONG/1.74532925199433E-2
      return
      end
