      SUBROUTINE CNSDLT
C        J   CHEN  AUG 1982   IBM  360/195
C
C        PURPOSE
C           THIS SUBROUTINE (CNSDLT) FIXES COEFFICIENTS DEPENDING ON
C           TIME STEP FOR VARIATIONS IN THE COURSE OF COMPUTATION..
C
C        DATA SET USE
C           NONE
C
C        VARIABLES
C            X1(50) = STORED ARRAY OF CONSTANTS
C              DELT = TIME INCREMENT FOR FINITE DIFFERENCING, SET IN 'INTDLT'
C               COR = CORIOLIS (1/SEC), (SET IN 'INTVAL')
C            DEGREE = ANGLE BETWEEN TWO RAYS, READ IN 'CRDRD1'
C              DELA = VALUE OF 'DEGREE' IN RADIANS
C               RAD = RADIAN MEASURE
C           X1B(10) = STORED ARRAY OF CONSTANTS
C                 G = GRAVITY = 32.2 FT/SEC-2
C
C        GENERAL COMMENTS
C           THIS SUBROUTINE IS CALLED BY SUBROUTINES INITLZ AND STMVAL.
C
C      COMMON /SLAT/   FSOUTH
      COMMON /EGTH/   DELS,DELT,G,COR
      COMMON /FRST/   X1(50),X12(50)
      COMMON /POLAR/  DEGREE,RMOUTH,AZMTH,DELA
      COMMON /DUMB4/  X1B(10)
C
      X1B(1)=G*DELT/DELA
      X1B(2)=DELT/DELA
c
      X1B(4)=DELT*COR
C
C        FSOUTH=-1. FOR SOUTHERN HEMISPHERE, NEGATIVE CORIOLIS PARAMETER
C              = 1. FOR NORTHERN HEMISPHERE,
c
C      X1B(4)=DELT*COR*FSOUTH
C
      X1B(5)=.5*X1B(2)
      X1B(6)=.5*X1B(1)
C        WEIR COEFFICIENT
      X1B(7)=.6*DELT*SQRT(2.*G/3.)/3.
      RETURN
       END
