      SUBROUTINE FILTRP
C        JELESNIANSKI   OCTOBER 1980   TDL   IBM 360/195
C
C        PURPOSE
C           THIS SUBROUTINE (FILTRP) SMOOTHS THE COMPUTED SURGE ENVELOPE
C           OF HIGHEST WATERS, IN SPACE. THE PROCEDURES ARE THE SILLIER
C           IN 'FILTER' AND 'HMXSV', 2 PASSES OF 3-POINT SMOOTHER.
C           IT IS FOR COSMETIC APPEARANCE. NO SMOOTHING ACROSS THE NON-
C           OVER TOPPED BARRIERS IS ALLOWED.
C        DATA SET USE
C           NONE
C
C        VARIABLES
C         IMAX JMAX = MAXIMUM GRID POINTS IN THE BASIN
C       IMXB1 JMXB1 = IMAX LESS 1, JMXB LESS 1
C        HMX(  ,  ) = SURGE ENVELOPE
C          HZ(  ,3) = DUMMY STORAGE FOR 3 LINES
C         ZB(  ,  ) = DEPTH FIELD
C     IIH(4) JJH(4) = SHIFT SUBSCRIPTS TO 4 ADJOINING MOMENTUM POINTS
C       IP(4) JP(4) = SHIFT SUBSCRIPTS TO 4 ADJOINING SURGE POINTS
C        ZBM(  ,  ) = MAX BARRIER HEIGHTS AT MOMENTUM POINTS
C
C        GENERAL COMMENTS
C           THIS SUBROUTINE RESIDES IN OVERLAY 'PLOTS'. IT IS CALLED
C           IN BY SUBROUTINE 'PLOTS'.
C
      INCLUDE 'parm.for'
C
      COMMON /FFTH/   ITIME,MHALT
      COMMON /DUMB3/  IMXB,JMXB,IMXB1,JMXB1,IMXB2,JMXB2
      COMMON /DUMB8/  IP(4),JP(4),IH(4),JH(4)
      COMMON /DUM88/  IIH(4),JJH(4),IHH(4),JHH(4)
      COMMON /HTERAIN/ HTER
      DIMENSION       HZ(M_,3)
      DIMENSION       GAMF(4)
      DATA HT/0./
C
C        STORE 2 OF 3 INITIAL LINES FOR SMOOTHING MIDDLE LINE
      DO 300 IPS=1,2
      KR=IPS
C
      IF(IPS.EQ.2) THEN
        I1=2
        I2=IMXB2
        J1=1
        J2=JMXB1
        DO 100 J=1,2
        DO 100 I=1,IMXB1
 100    HZ(I,J+1)=HMX(I,J)
      ELSE
        I1=1
        I2=IMXB1
        J1=2
        J2=JMXB2
        DO 112 J=1,3
        DO 112 I=1,IMXB1
 112    HZ(I,J)=HMX(I,J)
      ENDIF
C
      DO 220 J=J1,J2
      DO 190 I=I1,I2
C    CHANGED BY NSM TO HTER FROM 35 11/20/2010 : Accepted 4/4/2011
      IF(ZB(I,J).LE.(-HTER)) CYCLE
      HST=HMX(I,J)+ZB(I,J)
      IF(HST.LT.HT) CYCLE
      HSM=0.
      HDIF=0.
      GAM0=ELPDL2(I)+(ELPCL2(I)-ELPDL2(I))*SINL2(J)
C
C**************SMOOTHING ROUTINE****************************************
      DO 150 K=KR,4,2
      II=I+IIH(K)
      JK=J+JJH(K)
      IF (II.EQ.0.OR.JK.EQ.0) THEN
        GAMF(K)=0.
        HSM=HSM+HZ(I,2)
        HZZ=HZ(I,2)
C       WEIGHTING ADJUSTMENTS IN I-DIRECTION DUE TO POLAR GRIDS.
        HDIF=HDIF+HZZ*GAMF(K)
        CYCLE
      ENDIF
      GAMFK=ELPDL2(II)+(ELPCL2(II)-ELPDL2(II))*SINL2(JK)
c     GAMF(K)=.5*(1.+GAMFK/GAM0)-1.
      Z=GAMFK/GAM0
      GAMF(K)=2.*Z/(1.+Z)-1.
      IF (II.EQ.IMXB.OR.JK.EQ.JMXB) THEN
        HSM=HSM+HZ(I,2)
        HZZ=HZ(I,2)
C       WEIGHTING ADJUSTMENTS IN I-DIRECTION DUE TO POLAR GRIDS.
        HDIF=HDIF+HZZ*GAMF(K)
        CYCLE
      ENDIF
      JJ=JJH(K)+2
      IF (HZ(II,JJ)+ZB(II,JK).LT.HT) THEN
        HSM=HSM+HZ(I,2)
        HZZ=HZ(I,2)
C       WEIGHTING ADJUSTMENTS IN I-DIRECTION DUE TO POLAR GRIDS.
        HDIF=HDIF+HZZ*GAMF(K)
        CYCLE
      ENDIF
      KK=MOD(K,4)+1
      IA=I+IP(K)
      IB=I+IP(KK)
      JA=J+JP(K)
      JB=J+JP(KK)
      Z =ZBM(IA,JA)
      ZZ=ZBM(IB,JB)
      ZZZ=AMIN1(Z,ZZ)+HT
      IF(HZ(I,2).LT.ZZZ.OR.HZ(II,JJ).LT.ZZZ) THEN
        HSM=HSM+HZ(I,2)
        HZZ=HZ(I,2)
      ELSE
        HSM=HSM+HZ(II,JJ)
        HZZ=HZ(II,JJ)
      ENDIF
C       WEIGHTING ADJUSTMENTS IN I-DIRECTION DUE TO POLAR GRIDS.
      HDIF=HDIF+HZZ*GAMF(K)
 150  CONTINUE
C**************END SMOOTHING ROUTINE************************************
C
      HMX(I,J)=(2.*HMX(I,J)+HSM)/4.
C 180  HMX(I,J)=HMX(I,J)+HDIF/4.
      HMX(I,J)=AMAX1(HMX(I,J),-ZB(I,J))
 190  CONTINUE
C
C        UPDATE 3 LINES FOR SMOOTHING
      IF(J.LT.J2) THEN
        DO 200 II=1,IMXB1
        HZ(II,1)=HZ(II,2)
        HZ(II,2)=HZ(II,3)
 200    HZ(II,3)=HMX(II,J+2)
      ENDIF
 220  CONTINUE
 300  CONTINUE
      RETURN
      END
