        SUBROUTINE FORCE1(PDROP,RMAX,VMAX,ALTO,NCATG,IPRT)
C        JELESNIANSKI    SEPTEMBER 1980TDL   IBM 360/195
C
C        PURPOSE
C           THIS SUBROUTINE (FORCE1) COMPUTES, AT MILE INTERVALS FROM
C           THE STORM CENTER, FOR 800 MILES,
C                (1) SINE   OF THE INFLOW ANGLE
C                (2) COSINE OF THE INFLOW ANGLE
C                (3) SURFACE PRESSURE
C                (4) STATIC HEIGHT
C           REFERENCE FOR THE ALGORITHM AND THEORY IS:
C           JELESNIANSKI AND TAYLOR, 1973, A PRELIMINARY
C           VIEW OF STORM SURGES BEFORE AND AFTER STORM
C           MODIFICATIONS, NOAA TECHNICAL MEMORANDUM
C           ERL WMPO-3, WEATHER MODIFICATION PROGRAM OFFICE,
C           ERL, NOAA, U.S. DEPARTMENT OF COMMERCE, WASHINGTON,
C           D.C., MAY, 33 PP.
C
C        DATA SET USE
C           NONE
C
C        VARIABLES
C             PDROP = INPUT PRESSURE DROP
C              RMAX = DUMMY VALUE FOR STORM SIZE
C              VMAX = DUMMY VALUE FOR MAXIMUM WINDS
C              ALTO = LATITUDE OF BASIN MOUTH POINT
C              IPRT = 1 TO PRINT OUT STORM PROFILE,OTHERWISE =0.
C           XKS XKN = WIND FRICTION VALUES
C             CFRIC = FRICTION FACTOR, =1. IN OCEAN, =4*SQRT(22/RMAX)
C              JSET = DISTANCE BEYOND WHICH APPROX. BY
C                     CONSTANT INFLOW ANGLES
C               COR = CORIOLIS (1/SEC)
C     C(800) S(800) = COS/SIN OF INFLOW ANGLE, MILE INTERVALS
C         DELP(800) = STATIC HEIGHTS, MILE INTERVALS
C            P(800) = PRESSURE GRADIENT, MILE INTERVALS
C              RHOA = AIR DENSITY (MB HR**2 MILE**-2)
C              RHOW = WATER DENSITY (MB SEC**2 FT**-1 MILE**-1)
C             RHOWG = WATER DENSITY*GRAVITY (MB FT**-1)
C              PADD = PRESSURE FROM A RADIUS TO INFINITY
C             PINFT = PRESSURE DROP FROM ITERATION
C
C        GENERAL COMMENTS
C           THIS SUBROUTINE RESIDE IN OVERLAY 'CMPUTE'. IT IS CALLED IN
C           BY TWO SUBROUTINES, 'SETCMP' AND 'STMVAL'. SUBROUTINE
C           'FORCE1' CALLS IN SUBROUTINE 'PRTSTM'.
C
      COMMON /DUMMY4/ S(800),C(800),P(800),DELP(800)
C
      DATA RHOA/2.298E-3/,RHOW/4905./,RHOWG/29.89/
      DATA EPSLN /1.E-5/,IC12/795/
C
C         5 FUNCTIONAL FORMS FOLLOW
      VEE(R)     =2.*VMAX*RMAX*R/(RMAX**2+R**2)
      DERLNV(R)  =1./R-2.*R/(RMAX**2+R**2)
      PRGRAD(R,V)=RHOA*V*V*(XKS/SINPHI-DERLNV(R))
      PYTHAG(X)  =SQRT(1.-X*X)
      JSET       =MIN0(IC12-51,MAX0(150,INT(12.*RMAX)))
C
      COR=2.*(7.292116E-5)*SIN(ABS(ALTO)*1.74532925199433E-2)
      CORHR=3600.*COR
      CFRIC=1.
C        LAKE WINDS FRICTION WAS CALIBRATED BY MEASUREMENTS OF
C        STORM 1949, OVER LAKE OKEECHOBEE. RMAX=22.
      IF (NCATG.EQ.1) CFRIC=4.*SQRT(22./RMAX)
C
C         BEGIN ITERATION ALGORITHM
  100 CONTINUE
C
C         FORM 2 FRICTION VALUES FOR A STORM: COMPUTE FOR 2 STORMS
      XKS=.01*SQRT(RMAX/(.3*VMAX+60.))
      XKN=.01*SQRT(RMAX/(.4*VMAX+80.))
      XKS=XKS*CFRIC
      XKN=XKN*CFRIC
C         SET RANGES RELATIVE TO STORM CENTER, SCALED TO STORM SIZE
      J2=MIN1(3.*RMAX,50.)
      R0=JSET+50
      MMAX=JSET+9*J2+49
      DELR=1.
      VEER0=VEE(R0)*R0
      COTPHI=(CORHR*R0/VEER0+XKN)/XKS
      SINPHI=1./SQRT(1.+COTPHI*COTPHI)
      COSPHI=PYTHAG(SINPHI)
      OSINFI=1./SINPHI
      W0=VEER0*COSPHI
C        DWDR=0. WITH THIS INITIAL CONDITION
      PRESS=0.
      DPDR0=PRGRAD(R0,VEER0/R0)
C
C        RUNGE-KUTTA-HEUN-TAYLOR METHOD TO SOLVE THE EQUATION
C        DWDR=W*XKS/SIN(PHI)-CORHR*R-XKN*V*R=G(W,R) WHERE W=V*R*COS(PHI)
      DO 160 I=1,MMAX
      FACT=2./DELR
      SLP0=W0*XKS/SINPHI-CORHR*R0-XKN*VEER0
      R1=R0-DELR
      VEER1=VEE(R1)*R1
      W1=VEER1*COSPHI
C
C        NEWTON-RAPHSON METHOD TO FIND W1 SO THAT
C        .5*(G(W1,R1)+G(W0,R0))=(W0-W1)/(R0-R1)
      DO 120 KK=1,75
      SLP1=W1*XKS/SINPHI-CORHR*R1-XKN*VEER1
      PADD=FACT*(W0-W1)-SLP0
      DGDW=XKS/(SINPHI*SINPHI*SINPHI)
      DELW=(SLP1-PADD)/(DGDW+FACT)
      DOSINF=-DELW*COSPHI/VEER1/SINPHI/SINPHI/SINPHI
      OSINFI=OSINFI+DOSINF
      SINPHI=1./OSINFI
         COS1=COSPHI
      COSPHI=PYTHAG(SINPHI)
      W1=VEER1*COSPHI
      IF(W1) 180,180,110
  110 IF(ABS((COS1-COSPHI)/COS1)-EPSLN) 140,140,120
  120 CONTINUE
C
CC      WRITE(*,130)
  130 FORMAT('0INSUFFICIENT STEPS IN NEWTON-RAPHSON LOOP')
      STOP 999
  140 R0=R1
      K=R1+1.01
      VEER0=VEER1
      W0=W1
      S(K)=SINPHI
      C(K)=COSPHI
      DPDR1=PRGRAD(R1,VEER1/R1)
      P(K)=DPDR1
      PRESS=PRESS-(DPDR0+DPDR1)/FACT
      DELP(K)=PRESS
      DPDR0=DPDR1
       IF(K-J2-1) 150,150,160
  150 DELR=.1
  160 CONTINUE
C
      DELP(1)=PRESS-DPDR0/FACT
      P(1)=0.
      S(1)=0.
      C(1)=1.
      R0=JSET-1
      TERM=R0/(RMAX*RMAX+R0*R0)
      PADD=2.*RHOA*((VMAX*RMAX)**2)*(XKS*(ATAN(RMAX/R0)/RMAX+TERM)/
     1 S(JSET)+TERM*TERM)
C
C        PADD = PRESSURE IN MB FROM R0=JSET-1 TO R0=INFINITY, ASSUMING
C   SINPHI=S(JSET)=CONST. FROM R=JSET-1 TO INFINITY
      PINFT=PADD+DELP(JSET)-DELP(1)
C   PINFT= PRESSURE DROP IN MB FROM R=0 TO INFINITY,
C   THEN ON THIS ASSUMPTION
      PRS=PDROP
      IF (ABS(PINFT-PRS)-.2) 200,200,170
  170 VMAX=VMAX*SQRT(PRS/PINFT)
      GO TO 100
C
  180 CONTINUE
CC      WRITE(*,190)
  190 FORMAT('0COS(PHI).LT.0.')
      STOP
C
  200 SINPHI=S(JSET-1)
      COSPHI=C(JSET-1)
      JSTP1=JSET+1
C
      DO 210 K=JSTP1,IC12
      R0=K+1
      S(K)=SINPHI
      C(K)=COSPHI
      P(K)=PRGRAD(R0,VEE(R0))
      DELP(K)=DELP(K-1)+.5*(P(K)+P(K-1))
  210 CONTINUE
C
      PRESS=PADD+DELP(JSET)
      DO 220 I=1,IC12
      DELP(I)=(PRESS-DELP(I))/RHOWG
      P(I)=P(I)/RHOW
  220 CONTINUE
C
C      IF(IPRT.EQ.1) CALL PRTSTM(PADD,PINFT,VMAX,RMAX,ALTO,NCATG)
      IF(IPRT.EQ.1) CALL PRTSTM(PINFT,VMAX,RMAX,ALTO)
C
C      USE P( ) TO STORE P(I)/R.
      DO 290 I=2,IC12
      P(I)=P(I)/((I-1.)*5280.)
  290 CONTINUE
      RETURN
      END
