#!/bin/make
#------------------------------------------------------------------------------
# Makefile.MinGW                                        Last Change: 2026-10-07
#                                                        Arthur.Taylor@noaa.gov
#                                                              NWS/OSTI/MDL/DSB
#
# Makefile for slosh (command line and GUI interface) on MS-Windows systems
# Usage:
#    make                     Build the executable
#    make install             Move the built executable to the exec dir
#    make clean               Start with a clean slate
#
#    make B=4.5.0             Version of MinGW or cygwin ([4.5.0], cygwin)
#------------------------------------------------------------------------------
SHELL=/bin/bash#              # Shell for script evaluations
MPI=false#                    # Do we build with MPI?
MINGW=true#                   # Allow MinGW specific functions
B?=4.5.0#                     # See usage.
DOUBLE=true#                  # Use double precision flags
CC_OPT?=3#                    # Optimization level to use (0,1,2,3)

#------------------------------------------------------------------------------
# Following assumes we're still using GCC 4.5.0 32-bit
BIT=64#                       # Use 32 (vs 64) bit compilation
COMPLEX_16=new#               # Use COMPLEX*16 (original) or COMPLEX(16) (new)
WAVE=no#                      # Include wave code
VER=$(shell source ../../versions/run.ver ; echo $$slosh_ver)
DATE=$(shell source ../../versions/run.ver ; echo $$slosh_date)

uname_O := $(shell sh -c 'uname -o 2>/dev/null || echo not')
ifeq ($(uname_O),Cygwin)
   PATH=/cygdrive/c/sys/MinGW/MinGW-$(B)/bin
endif

#-----------------
# Set up the PATH
#-----------------
ifeq ($(B),cygwin)
   MINGW=false
   COMPLEX_16=new
   PATH=/usr/bin
endif

#-------------------------------------------
# Set up the called executables and version
#-------------------------------------------
CC=gcc
CC_VER:=$(shell $(CC) --version | head -n1 | sed 's/ /_/g')
CC_NUM:=$(shell $(CC) --version | head -n1 | sed 's/^.* //')
#$(info $$CC_NUM is [${CC_NUM}])
FC=gfortran
MV=/bin/mv
RM=/bin/rm
MKDIR=/bin/mkdir

#----------------------------------------
# Set Defaults based on compiler version
#----------------------------------------
ifeq ($(CC_NUM),4.5.0)
  COMPLEX_16=original#          # Use COMPLEX*16 (original) or COMPLEX(16) (new)
  BIT=32
endif

#--------------------------
# Set the C compiler flags
#--------------------------
CFLAGS=-O$(CC_OPT)#           # Optimization level
CFLAGS+=-Wall#                # Activate all warnings
CFLAGS+=-Wextra -pedantic -ansi# Activate more warnings
ifeq ($(CC_NUM),"4.5.0")
   CFLAGS+=-D4.5.0
endif
ifeq ($(BIT),64)
   CFLAGS+=-DSIZEOF_LONG_INT=8#  # Compile on a 64 bit platform
endif
CFLAGS+=-D_GCC_#              # Use GCC wrappings for binding to FORTRAN
ifeq ($(DOUBLE),true)
   CFLAGS+=-DDOUBLE_FORTRAN#  # Compile with double precision in FORTRAN
endif
ifeq ($(MPI),true)
   CFLAGS+=-D_MPI_#           # Compile with MPI
endif
ifeq ($(MINGW),true)
   CFLAGS+=-D_MINGW_#         # Allow MinGW specific sleep(), mkdir() functions
endif
# CFLAGS+=-DEBUG#             # Turn on debug flags
CFLAGS+=-D_EXPR_#             # Activate experimental options
CFLAGS+=-I.#                  # Add '.' to the include path
ifeq ($(BIT),32)
  CFLAGS+=-m32
endif

#-------------------------------
# Set up the GUI compiler flags
#-------------------------------
GUI_FLAGS=$(CFLAGS)
GUI_FLAGS+=-D_WINDOWS_#       # Use MS-Windows GUI Support
GUI_FLAGS+=-DHAVE_TCL#        # Use Tcl API connections
# Order matters with -I
GUI_FLAGS+=-I../../gui/include/tcl8.5.3_win
# Following checks if file **doesn't exist**
ifeq (,$(wildcard ../../gui/include/tcl8.5.3_win/tcl.h))
  GUI_COMPILE=no
else
  GUI_COMPILE=yes
endif

#-----------------------------------
# Set up the FORTRAN compiler flags
#-----------------------------------
FFLAGS=-O$(CC_OPT)#           # Optimization level
ifeq ($(B),intel)
   FFLAGS+=-fpp#              # Run the ifort Pre-processor (similar to -cpp)
else
   FFLAGS+=-cpp#              # Turn on Pre-processing in FORTRAN code
endif
ifeq ($(WAVE),yes)
   FFLAGS+=-DINCLUDE_WAVE#    # Include Wave code
endif
ifeq ($(DOUBLE),true)
   ifeq ($(B),intel)
      FFLAGS+=-r8#            # Use double precision flags
   else
      FFLAGS+=-fdefault-real-8# Use double precision flags
   endif
endif
ifeq ($(COMPLEX_16),new)
   FFLAGS+=-DCOMPLEX_p16
endif
ifeq ($(B),intel)
   FFLAGS+=-fp-model strict#  # Activate more warnings
   FFLAGS+=-check bounds#     # Make sure no out of array index calls.
#   FFLAGS+=-warn all
#   FFLAGS+=-warn nodeclarations
#   FFLAGS+=-warn unused
#   FFLAGS+=-fp-stack-check
#   FFLAGS+=-heap-arrays 10
endif
ifeq ($(BIT),32)
  FFLAGS+=-m32
endif

#------------------------------------------
# Set up the Library flags (order matters)
#------------------------------------------
ifneq ($(B),cygwin)
   LIBS+=-Wl,-Bstatic
endif
LIBS+=-lgfortran

GUI_LIBS=$(LIBS)
GUI_LIBS+=-L../../gui/exec -Wl,-Bdynamic -ltk85
GUI_LIBS+=-L../../gui/exec -Wl,-Bdynamic -ltcl85
GUI_LIBS+=-L../../gui/exec -Wl,-Bdynamic -lhalo85

LIBS+=-L/usr/lib -lm
ifeq ($(B),intel)
   LIBS=-lifcore -limf
endif
GUI_LIBS+=-L/usr/lib -lm#     # Order matters.

#-------------------------------------
# Set up the command executable flags
#-------------------------------------
CMDFLAGS1=$(CFLAGS) -DPRG_VER="\"$(VER)\""# Set the program version
CMDFLAGS1+=-DPRG_DATE="\"$(DATE)\""# Set the program date
CMDFLAGS1+=-DCC_VER="\"$(CC_VER)\""# Add compiler version
CMDFLAGS1+=-DCC_OPT="\"$(CC_OPT)\""# Add compiler optimization level

CMDFLAGS2=$(GUI_FLAGS) -DPRG_VER="\"$(VER)\""#  Set the program version
CMDFLAGS2+=-DPRG_DATE="\"$(DATE)\""# Set the program date
CMDFLAGS2+=-DCC_VER="\"$(CC_VER)\""# Add compiler version
CMDFLAGS2+=-DCC_OPT="\"$(CC_OPT)\""# Add compiler optimization level

#--------------------------------------------------------
# Set up the Linker flags
#   86,115,305 is min after move itree to parm2.f
#   85,983,233 is min after -fmax-stack-var-size=4000
#   85,917,697 is min after -fno-automatic (But slower!)
#   Max size on MS-Windows 10: 885,983,233
#--------------------------------------------------------
LDFLAGS=-Wl,--stack,46500000# Set the stack size
ifeq ($(DOUBLE),true)
   LDFLAGS=-Wl,--stack,86115305# Set the stack size
endif
ifeq ($(B),intel)
   LDFLAGS=-xAVX#             # Avoid complaint about MOVBE, FMA, BMI, LZCNT,
                              # AVX2 when at higher than O0 optimization.
endif
GUI_LDFLAGS=$(LDFLAGS)
GUI_LDFLAGS+=-mconsole#       # Provide console diagnostics

#------------------------------------------------------------------------------
# Source (CSRC, MPISRC, FSRC); HEADERS, FORT_HEADERS; OBJS; Main
#------------------------------------------------------------------------------
CSRC=amyutil.c
CSRC+=clock.c
CSRC+=complex.c
CSRC+=myassert.c
CSRC+=myutil.c
CSRC+=pack.c
CSRC+=rex.c
CSRC+=savellx.c
CSRC+=setup.c
CSRC+=slosh2.c
CSRC+=tendian.c
CSRC+=tideutil.c
CSRC+=tio3.c
CSRC+=usrparse.c

MPISRC=leader.c
MPISRC+=team.c
MPISRC+=mstUtil.c
MPISRC+=topology.c
MPISRC+=winBuffer.c

FSRC+=mapshift.f
FSRC+=mapdup.f

#----------------------------------
# Intrface.f :: Was in this order.
#----------------------------------
FSRC+=inital.f
FSRC+=wind.f
FSRC+=wav.f
FSRC+=tmstpc1.f#               # First part of tmstep.f
FSRC+=tmstpc2.f#               # Second part of tmstep.f
FSRC+=tmstpm.f#                # Third part of tmstep.f
FSRC+=clnup.f
FSRC+=cln_hs.f
FSRC+=xy2llx.f
FSRC+=staticht.f
FSRC+=issubgrid.f
FSRC+=casename.f

#--------------------------------
# Spinup.f :: Was in this order.
#--------------------------------
FSRC+=intlhtsub.f
FSRC+=intlhtadd.f
FSRC+=momntm2.f
FSRC+=mntmbd2.f
FSRC+=flw1dm2.f
FSRC+=tmstp2.f

FSRC+=initalcommon.f

#---------------------------------
# runslhg.f :: Was in this order.
#---------------------------------
FSRC+=extrpt.f
FSRC+=intdlt.f
FSRC+=intval.f
FSRC+=cnstnt.f
FSRC+=btmstr.f
FSRC+=setcmp.f
FSRC+=stmval.f
FSRC+=cnsdlt.f
FSRC+=force1.f
FSRC+=intwnd.f
FSRC+=prtstm.f
FSRC+=crdrd1.f
FSRC+=ttimer.f
FSRC+=initlz.f
FSRC+=inputn.f
FSRC+=steron.f
FSRC+=setdst.f
FSRC+=depmsy.f
FSRC+=intlht.f
FSRC+=crdrd2.f
FSRC+=contty.f
FSRC+=bdryht.f
FSRC+=flw1dm_block_c.f#        # subblock and flw1dm continuity combined.
FSRC+=flw1dm_block_m.f#        # flw1dm momentum.
FSRC+=depsfc.f
FSRC+=channl.f
FSRC+=frcpnt.f
FSRC+=momntm.f
FSRC+=mntmbd.f
FSRC+=fhmxsv.f
FSRC+=archiv.f
FSRC+=histry.f
FSRC+=hstry2.f
FSRC+=filtrp.f
FSRC+=hmxsv.f
FSRC+=smpt2g.f
FSRC+=flt2g.f
FSRC+=filter.f
FSRC+=flter2.f
FSRC+=snapsh.f
FSRC+=xfilter.f
FSRC+=inputn2.f
FSRC+=spline.f
FSRC+=splint.f
ifeq ($(B),intel)
   FSRC+=rstout_WCOSS.f
else
   FSRC+=rstout.f
endif
FSRC+=setcmp_hs.f
FSRC+=hbuv_hs.f
ifeq ($(WAVE),yes)
   FSRC+=wave.f
   FSRC+=calcwind.f
endif

#----------------
# C header files
#----------------
HEADERS=amyutil.h
HEADERS+=clock.h
HEADERS+=complex.h
HEADERS+=halotype.h
HEADERS+=leader.h
HEADERS+=team.h
HEADERS+=mstUtil.h
HEADERS+=myassert.h
HEADERS+=myutil.h
HEADERS+=pack.h
HEADERS+=rex.h
HEADERS+=savellx.h
HEADERS+=setup.h
HEADERS+=slosh2.h
HEADERS+=tendian.h
HEADERS+=tideutil.h
HEADERS+=tio3.h
HEADERS+=topology.h
HEADERS+=type.h
HEADERS+=usrparse.h
HEADERS+=winBuffer.h

#------------------------------------
# FORTRAN include (aka header) files
#------------------------------------
FORT_HEADERS+=parm.for
FORT_HEADERS+=parmmsy.for
ifeq ($(WAVE),yes)
   FORT_HEADERS+=wav1.for
endif

#---------------------------------
# Setup OBJ1 list and CMD1 target
#---------------------------------
OBJS1=$(CSRC:.c=.o)
# Handle MPISRC
ifeq ($(MPI),true)
   OBJS1+=leader.o
   OBJS1+=team.o
   OBJS1+=mstUtil.o
   OBJS1+=topology.o
   OBJS1+=winBuffer.o
endif
OBJS1+=$(FSRC:.f=.o)

MAIN1=cstart.c
ifeq ($(MPI),true)
   CMD1=slosh_mpi
else
   CMD1=sloshDos
endif
EXT=.exe

#---------------------------------------
# Setup GUI (OBJ2) list and CMD2 target
#---------------------------------------
GUISRC=haloclock2.c
GUISRC+=tclslosh.c

GUI_HEADERS+=$(HEADERS)
GUI_HEADERS+=haloclock2.h
GUI_HEADERS+=halo_out.h
GUI_HEADERS+=tclslosh.h

OBJS2=$(CSRC:.c=.o)
ifeq ($(MPI),true)
  OBJS2+=$(MPISRC:.c=.o)
endif
OBJS2+=$(FSRC:.f=.o)
OBJS2+=$(GUISRC:.c=.o)

MAIN2=tclstart.c
ifeq ($(GUI_COMPILE),yes)
  CMD2=sloshGui
else
  CMD2=
endif

#------------------------------------------------------------------------------
# Targets
#------------------------------------------------------------------------------
all: $(CMD1) $(CMD2)
.PHONY: all

$(CMD1): $(OBJS1) $(MAIN1) $(HEADERS) $(FORT_HEADERS)
	$(CC) $(MAIN1) $(CMDFLAGS1) $(LDFLAGS) $(OBJS1) $(LIBS) -o $(CMD1)

$(CMD2): $(OBJS2) $(MAIN2) $(GUI_HEADERS) $(FORT_HEADERS)
	$(CC) $(MAIN2) $(CMDFLAGS2) $(GUI_LDFLAGS) $(OBJS2) $(GUI_LIBS) -o $(CMD2)

.PHONY: install
install: $(CMD1) $(CMD2)
	$(MKDIR) -p ../../exec
	$(MV) $(CMD1)$(EXT) ../../exec
ifeq ($(GUI_COMPILE),yes)
	$(MKDIR) -p ../../gui/exec
	$(MV) $(CMD2)$(EXT) ../../gui/exec
endif

.PHONY: clean
clean:
	-$(RM) -f $(OBJS1)
	-$(RM) -f *.mod *.o
	-$(RM) -f $(CMD1)$(EXT)
ifeq ($(GUI_COMPILE),yes)
	-$(RM) -f $(OBJS2)
	-$(RM) -f $(CMD2)$(EXT)
endif

#------------------------------------------------------------------------------
# Suffixes
#------------------------------------------------------------------------------
.c.o:
	$(CC) -c $(CFLAGS) $<

.f.o:
	$(FC) -c $(FFLAGS) $<

leader.o: leader.c $(HEADERS)
	$(CC) -c $(CFLAGS) leader.c

team.o: team.c $(HEADERS)
	$(CC) -c $(CFLAGS) team.c

mstUtil.o: mstUtil.c $(HEADERS)
	$(CC) -c $(CFLAGS) mstUtil.c

topology.o: topology.c $(HEADERS)
	$(CC) -c $(CFLAGS) topology.c

winBuffer.o: winBuffer.c $(HEADERS)
	$(CC) -c $(CFLAGS) winBuffer.c

haloclock2.o: haloclock2.c $(GUI_HEADERS)
	$(CC) -c $(GUI_FLAGS) haloclock2.c

tclslosh.o: tclslosh.c $(GUI_HEADERS)
	$(CC) -c $(GUI_FLAGS) tclslosh.c
