#!/bin/make
#------------------------------------------------------------------------------
# Makefile.linux                                        Last Change: 2024-01-29
#                                                        Arthur.Taylor@noaa.gov
#                                                              NWS/OSTI/MDL/DSB
#
# Makefile for slosh (command line) on LINUX systems
# Usage:
#    make                     Build the executable
#    make install             Move the built executable to the exec dir
#    make clean               Start with a clean slate
#
#    make B=gcc               Build using gcc suite (linux)
#    make B=intel             Build using intel suite
#    make B=cygwin            Build using cygwin
#------------------------------------------------------------------------------
SHELL=/bin/bash#              # Shell for script evaluations
MPI=false#                    # Do we build with MPI?
MINGW=false#                  # Allow MinGW specific functions
B?=gcc#                       # Set to default.  On WCOSS build.sh will set
                              # to 'intel'.  On Cygwin, uname will determine
DOUBLE=true#                  # Use double precision flags
CC_OPT=3#                     # Optimization level to use (0,1,2,3)

#------------------------------------------------------------------------------
# Following assumes we're still using GCC 4.5.0 32-bit
BIT=32#                       # Use 32 (vs 64) bit compilation
COMPLEX_16=original#          # Use COMPLEX*16 (original) or COMPLEX(16) (new)

#------------------------------------------------------------------------------
# Following gets the SLOSH model's version and date
VER=$(shell source ../../versions/run.ver ; echo $$slosh_ver)
DATE=$(shell source ../../versions/run.ver ; echo $$slosh_date)

WAVE=no#                      # Include wave code

#-----------------
# Set up the PATH
#-----------------
OS=$(shell uname -o)
ifeq ($(OS),Cygwin)
   B=cygwin
   COMPLEX_16=new
#   DOUBLE=false#             # Cygwin FORTRAN complex needs this to be false
# Force the PATH to be 'cygwin' vs 'MinGW'
   PATH=/usr/bin
endif

#-------------------------------------------
# Set up the called executables and version
#-------------------------------------------
CC=gcc
CC_VVV:=$(shell $(CC) --version | head -n1 | cut -d' ' -f2,3 --output-delimiter='-')
ifeq ($(MINGW),true)
   CC_VER=MinGW-$(CC_VVV)
else
   CC_VER=$(CC_VVV)
endif
FC=gfortran
ifeq ($(B),intel)
   CC=icc
   FC=ifort
   COMPLEX_16=original
endif
ifeq ($(B),cygwin)
   ifeq ($(MPI),true)
      CC=mpicc
   endif
endif
MV=/bin/mv
RM=/bin/rm
MKDIR=/bin/mkdir

#--------------------------
# Set the C compiler flags
#--------------------------
CFLAGS=-O$(CC_OPT)#           # Optimization level
CFLAGS+=-Wall#                # Activate all warnings
ifeq ($(B),intel)
   CFLAGS+=-strict-ansi -fp-model strict# Activate more warnings
   CFLAGS+=-D_LINUX_#         # Operating system (_LINUX_,_UNIX_,_WINDOWS_)
   CFLAGS+=-DSIZEOF_LONG_INT=8# Compile on a 64 bit platform
endif
ifeq ($(B),cygwin)
   CFLAGS+=-Wextra -pedantic -ansi# Activate more warnings
   CFLAGS+=-DSIZEOF_LONG_INT=8# # Compile on a 64 bit platform
endif
ifeq ($(B),gcc)
   CFLAGS+=-Wextra -pedantic -ansi# Activate more warnings
   CFLAGS+=-D_LINUX_#         # Operating system (_LINUX_,_UNIX_,_WINDOWS_)
endif
ifeq ($(BIT),64)
   CFLAGS+=-DSIZEOF_LONG_INT=8#  # Compile on a 64 bit platform
endif
CFLAGS+=-D_GCC_#              # Use GCC wrappings for binding to FORTRAN
ifeq ($(DOUBLE),true)
   CFLAGS+=-DDOUBLE_FORTRAN#  # Compile with double precision in FORTRAN
endif
ifeq ($(MPI),true)
   CFLAGS+=-D_MPI_#           # Compile with MPI
endif
ifeq ($(MINGW),true)
   CFLAGS+=-D_MINGW_#         # Allow MinGW specific sleep(), mkdir() functions
endif
# CFLAGS+=-DEBUG#             # Turn on debug flags
CFLAGS+=-D_EXPR_#             # Activate experimental options
CFLAGS+=-I.#                  # Add '.' to the include path
ifeq ($(BIT),32)
  CFLAGS+=-m32
endif

#-----------------------------------
# Set up the FORTRAN compiler flags
#-----------------------------------
FFLAGS=-O$(CC_OPT)#           # Optimization level
ifeq ($(B),intel)
   FFLAGS+=-fpp#              # Run the ifort Pre-processor (similar to -cpp)
else
   FFLAGS+=-cpp#              # Turn on Pre-processing in FORTRAN code
endif
ifeq ($(WAVE),yes)
   FFLAGS+=-DINCLUDE_WAVE#    # Include Wave code
endif
ifeq ($(DOUBLE),true)
   ifeq ($(B),intel)
      FFLAGS+=-r8#            # Use double precision flags
   else
      FFLAGS+=-fdefault-real-8# Use double precision flags
   endif
endif
ifeq ($(COMPLEX_16),new)
   FFLAGS+=-DCOMPLEX_p16
endif
ifeq ($(B),intel)
   FFLAGS+=-fp-model strict#  # Activate more warnings
   FFLAGS+=-check bounds#     # Make sure no out of array index calls.
#   FFLAGS+=-warn all
#   FFLAGS+=-warn nodeclarations
#   FFLAGS+=-warn unused
#   FFLAGS+=-fp-stack-check
#   FFLAGS+=-heap-arrays 10
endif
ifeq ($(BIT),32)
  FFLAGS+=-m32
endif

#------------------------------------------
# Set up the Library flags (order matters)
#------------------------------------------
LIBS=-lgfortran
# LIBS+=-Wl,-Bstatic
# LIBS+=-lquadmath#           # Used for EMC's workstation (8/9/2019)

LIBS+=-L/usr/lib -lm
ifeq ($(B),intel)
   LIBS=-lifcore -limf
endif

#-------------------------------------
# Set up the command executable flags
#-------------------------------------
CMDFLAGS1=$(CFLAGS) -DPRG_VER="\"$(VER)\""# Set the program version
CMDFLAGS1+=-DPRG_DATE="\"$(DATE)\""# Set the program date
CMDFLAGS1+=-DCC_VER="\"$(CC_VER)\""# Add compiler version
CMDFLAGS1+=-DCC_OPT="\"$(CC_OPT)\""# Add compiler optimization level

#--------------------------------------------------------
# Set up the Linker flags
#   86,115,305 is min after move itree to parm2.f
#   85,983,233 is min after -fmax-stack-var-size=4000
#   85,917,697 is min after -fno-automatic (But slower!)
#   Max size on MS-Windows 10: 885,983,233
#--------------------------------------------------------
LDFLAGS=
ifeq ($(B),cygwin)
   # --stack is a PE and BeOS option only.
   # On linux you control the stack via `ulimit -s 84500`
   LDFLAGS=-Wl,--stack,46500000# Set the stack size
   ifeq ($(DOUBLE),true)
      LDFLAGS=-Wl,--stack,86115305# Set the stack size
   endif
endif
ifeq ($(B),intel)
   LDFLAGS=-xAVX#             # Avoid complaint about MOVBE, FMA, BMI, LZCNT,
                              # AVX2 when at higher than O0 optimization.
endif

#------------------------------------------------------------------------------
# Source (CSRC, MPISRC, FSRC); HEADERS, FORT_HEADERS; OBJS; Main
#------------------------------------------------------------------------------
CSRC=amyutil.c
CSRC+=clock.c
CSRC+=complex.c
CSRC+=myassert.c
CSRC+=myutil.c
CSRC+=pack.c
CSRC+=rex.c
CSRC+=savellx.c
CSRC+=setup.c
CSRC+=slosh2.c
CSRC+=tendian.c
CSRC+=tideutil.c
CSRC+=tio3.c
CSRC+=usrparse.c

MPISRC=leader.c
MPISRC+=team.c
MPISRC+=mstUtil.c
MPISRC+=topology.c
MPISRC+=winBuffer.c

FSRC+=mapshift.f
FSRC+=mapdup.f

#----------------------------------
# Intrface.f :: Was in this order.
#----------------------------------
FSRC+=inital.f
FSRC+=wind.f
FSRC+=wav.f
FSRC+=tmstpc1.f#               # First part of tmstep.f
FSRC+=tmstpc2.f#               # Second part of tmstep.f
FSRC+=tmstpm.f#                # Third part of tmstep.f
FSRC+=clnup.f
FSRC+=cln_hs.f
FSRC+=xy2llx.f
FSRC+=staticht.f
FSRC+=issubgrid.f
FSRC+=casename.f

#--------------------------------
# Spinup.f :: Was in this order.
#--------------------------------
FSRC+=intlhtsub.f
FSRC+=intlhtadd.f
FSRC+=momntm2.f
FSRC+=mntmbd2.f
FSRC+=flw1dm2.f
FSRC+=tmstp2.f

FSRC+=initalcommon.f

#---------------------------------
# runslhg.f :: Was in this order.
#---------------------------------
FSRC+=extrpt.f
FSRC+=intdlt.f
FSRC+=intval.f
FSRC+=cnstnt.f
FSRC+=btmstr.f
FSRC+=setcmp.f
FSRC+=stmval.f
FSRC+=cnsdlt.f
FSRC+=force1.f
FSRC+=intwnd.f
FSRC+=prtstm.f
FSRC+=crdrd1.f
FSRC+=ttimer.f
FSRC+=initlz.f
FSRC+=inputn.f
FSRC+=steron.f
FSRC+=setdst.f
FSRC+=depmsy.f
FSRC+=intlht.f
FSRC+=crdrd2.f
FSRC+=contty.f
FSRC+=bdryht.f
FSRC+=flw1dm_block_c.f#        # subblock and flw1dm continuity combined.
FSRC+=flw1dm_block_m.f#        # flw1dm momentum.
FSRC+=depsfc.f
FSRC+=channl.f
FSRC+=frcpnt.f
FSRC+=momntm.f
FSRC+=mntmbd.f
FSRC+=fhmxsv.f
FSRC+=archiv.f
FSRC+=histry.f
FSRC+=hstry2.f
FSRC+=filtrp.f
FSRC+=hmxsv.f
FSRC+=smpt2g.f
FSRC+=flt2g.f
FSRC+=filter.f
FSRC+=flter2.f
FSRC+=snapsh.f
FSRC+=xfilter.f
FSRC+=inputn2.f
FSRC+=spline.f
FSRC+=splint.f
ifeq ($(B),intel)
   FSRC+=rstout_WCOSS.f
else
   FSRC+=rstout.f
endif
FSRC+=setcmp_hs.f
FSRC+=hbuv_hs.f
ifeq ($(WAVE),yes)
   FSRC+=wave.f
endif

#----------------
# C header files
#----------------
HEADERS=amyutil.h
HEADERS+=clock.h
HEADERS+=complex.h
HEADERS+=halotype.h
HEADERS+=leader.h
HEADERS+=team.h
HEADERS+=mstUtil.h
HEADERS+=myassert.h
HEADERS+=myutil.h
HEADERS+=pack.h
HEADERS+=rex.h
HEADERS+=savellx.h
HEADERS+=setup.h
HEADERS+=slosh2.h
HEADERS+=tendian.h
HEADERS+=tideutil.h
HEADERS+=tio3.h
HEADERS+=topology.h
HEADERS+=type.h
HEADERS+=usrparse.h
HEADERS+=winBuffer.h

#------------------------------------
# FORTRAN include (aka header) files
#------------------------------------
FORT_HEADERS+=parm.for
FORT_HEADERS+=parmmsy.for
ifeq ($(WAVE),yes)
   FORT_HEADERS+=wav1.for
endif

#---------------------------------
# Setup OBJ1 list and CMD1 target
#---------------------------------
OBJS1=$(CSRC:.c=.o)
# Handle MPISRC
ifeq ($(MPI),true)
   OBJS1+=leader.o
   OBJS1+=team.o
   OBJS1+=mstUtil.o
   OBJS1+=topology.o
   OBJS1+=winBuffer.o
endif
OBJS1+=$(FSRC:.f=.o)

MAIN1=cstart.c
ifeq ($(MPI),true)
   CMD1=slosh_mpi
else
   CMD1=sloshLinux
endif
EXT=

#------------------------------------------------------------------------------
# Targets
#------------------------------------------------------------------------------
all: $(CMD1)
.PHONY: all

$(CMD1): $(OBJS1) $(MAIN1) $(HEADERS) $(FORT_HEADERS)
ifeq ($(B),intel)
	@echo "********************************************************************"
	@echo "Remember to 'module load ./Intel.module' for icc version 14."
	@echo "********************************************************************"
endif
	$(CC) $(MAIN1) $(CMDFLAGS1) $(LDFLAGS) $(OBJS1) $(LIBS) -o $(CMD1)

.PHONY: install
install: $(CMD1)
	$(MKDIR) -p ../../exec
	$(MV) $(CMD1)$(EXT) ../../exec

.PHONY: clean
clean:
	-$(RM) -f $(OBJS1)
	-$(RM) -f *.mod *.o
	-$(RM) -f $(CMD1)$(EXT)

#------------------------------------------------------------------------------
# Suffixes
#------------------------------------------------------------------------------
.c.o:
	$(CC) -c $(CFLAGS) $<

.f.o:
	$(FC) -c $(FFLAGS) $<

leader.o: leader.c $(HEADERS)
	$(CC) -c $(CFLAGS) leader.c

team.o: team.c $(HEADERS)
	$(CC) -c $(CFLAGS) team.c

mstUtil.o: mstUtil.c $(HEADERS)
	$(CC) -c $(CFLAGS) mstUtil.c

topology.o: topology.c $(HEADERS)
	$(CC) -c $(CFLAGS) topology.c

winBuffer.o: winBuffer.c $(HEADERS)
	$(CC) -c $(CFLAGS) winBuffer.c
