      SUBROUTINE PRTSTM(PINFT,VMAX,RMAX,ALTO)
C        THIS SUBROUTINE (STMPRT) PRINTTDL   IBM 360/195
C
C        PURPOSE
C           THIS SUBROUTINE (STRMPRT) PRINTS OUT, AT TIME OF NEAREST
C           APPROACH, THE TWO STORM SYSTEMS FOR LAKE AND OCEAN. THE
C           STORM VALUES ARE INCREMENTED AT REGULAR INTERVALS FROM
C           THE STORM CENTER.
C
C        DATA SET USE
C           NONE
C
C        VARIABLES
C            P(800) = PRESSURE GRADIENT
C            S(800) = SINE OF INFLOW ANGLE
C         DELP(800) = STATIC HEIGHTS FROM STORM CENTER
C             NCATG = 1 FOR LAKE WINDS, =2 FOR OCEAN
C              PADD = PRESSURE DROP FROM A RADIUS TO INFINITY
C             PINFT = PRESSURE DROP FROM ITERATION
C             RHOWG = WATER DENSITY*GRAVITY (MB SEC**2 FT**-1 MILE**-1)
C               PHI = INFLOW ANGLE
C              VMAX = DUMMY VALUE FOR MAXIMUM WINDS
C              ALTO = LATITUDE
C   IBEG(3) IEND(3) = BEGIN/END LOOP
C             IN(3) = INCREMENT OF DO LOOP
C
C        GENERAL COMMENTS
C           THIS SUBROUTINE RESIDES IN OVERLAY 'CMPUTE'. IT IS CALLED
C           IN BY SUBROUTINE 'FORCE1'. 'FORCE1' IS CALLED IN BY
C           SUBROUTINE 'STMVAL'.
C
      COMMON /DUMMY4/ S(800),C(800),P(800),DELP(800)
      DIMENSION       IBEG(3),IEND(3),IN(3)
C
      DATA IBEG/1,111,251/,IEND/101,231,751/,IN/2,10,50/
      DATA RHOA/2.298E-3/,RHOW/4905./,RHOWG/29.89/
C
      VEE(R)     =2.*VMAX*RMAX*R/(RMAX**2+R**2)
C
      COR=2.*(7.292116E-5)*SIN(ALTO*1.74532925199433E-2)
      CORHR=3600.*COR
C
c      IF(NCATG.EQ.2) THEN
c      WRITE(*,*)'  ***  SLOSH SYMMETRIC WIND PROFILES OVER OCEAN  ***'
c      ELSE
c      WRITE(*,*)'  ***  SLOSH SYMMETRIC WIND PROFILES OVER LAKES ***'
c      ENDIF
C
c      WRITE(*,240) PINFT,VMAX,RMAX,PADD,ALTO
c  240 FORMAT('  PRES DROP  MAX WIND   RADIUS     PADD   LATITUDE',
c     1 /4F10.3,F7.2)
C
c      WRITE(*,250)
c  250 FORMAT (/'    RADIUS     SPEED PRES DROP INFLW ANG  STC HGHT',
c     1   ' GRAD WIND')
C
      DO 260 K=1,3
      J1=IBEG(K)
      J2=IEND(K)
      J3=IN(K)
      DO 260 I=J1,J2,J3
      J=I-1
      PHI=ASIN(S(I))/1.74532925199433E-2
      PRESS=PINFT-RHOWG*DELP(I)
      R0=J
      XX=VEE(R0)
      VG=R0*P(I)*RHOW/RHOA
      CORR=.5*CORHR*R0
      VGRD=SQRT(VG+CORR*CORR)-CORR
c      WRITE(*,270)J,XX,PRESS,PHI,DELP(I),VGRD
  260 CONTINUE
C
  270 FORMAT (I10,5F10.2)
      RETURN
       END
