      SUBROUTINE SETDST
C        JELESNIANSKI    SEPTEMBER 1980 TDL   IBM 360/195
C
C        PURPOSE
C           THIS SUBROUTINE (SETDST) COMPUTES SIZE SPECIFICS OF THE
C           POLAR GRID, AS WELL AS THE ORIENTATION OF THE (P,Q) POLAR
C           SYSTEM VERSUS THE (X,Y) SYSTEM.  THE END RESULTS ARE USED
C           FOR DRIVING FORCES TRANSFORMED FROM THE (X,Y) TO (P,Q)
C           SYSTEMS.  PRINT OUT OF POLAR SPECIFICS ARE EFFECTED.
C
C        DATA SET USE
C           NONE
C
C        VARIABLES
C              DELA = RADIAN MEASURE BETWEEN CONTIGUOUS RAYS
C         IMXB JMXB = TOTAL GRID SPACINGS, SET IN 'CRDRD1'
C       IMXB1 JMXB1 = IMXB LESS 1, JMXB LESS 1
C           IRB JRB = TOTAL GRID POINTS IN +-DIRECTION FROM ORIGIN
C           NDB NDE = TOTAL GRID POINTS IN +-Q DIRECTION FROM ORIGIN
C            RMOUTH = DISTANCE FROM POLE TO BASIN ORIGIN IN MILES
C        SIDEHZ(  ) = ARC LENGTH BETWEEN CONTIGUOUS GRID POINTS IN FT
C        ARESQ(  ) = AREA OF SQUARES, BETWEEN CONCENTRIC CIRCLES IN FT-2
C        SIDEVT(  ) = DISTANCE BETWEEN CONCENTRIC CIRCLES IN MILES IN FEET
C            DEGREE = ANGLE BETWEEN 2 CONTIGUOUS RAYS
C          ANGD(  ) = ANGLE BETWEEN P-AXIS AND ANY RAY, IN DEGREES
C               RAD = RADIAN MEASURE
C COST(  ) SINT(  ) = RAY PROJECTIONS THRU MOMENTUM POINTS, ON (X,Y) AXIS
C COSL(  ) SINL(  ) = RAY PROJECTIONS THRU SURGE POINTS, ON (X,Y) AXIS
C
C        GENERAL COMMENTS
C           THIS SUBROUTINE RESIDES IN OVERLAY 'INITLZ'. IT IS
C           CALLED IN BY SUBROUTINE 'INITLZ'.
C
      INCLUDE 'parm.for'
C
      COMMON /POLAR/  DEGREE,RMOUTH,AZMTH,DELA
      COMMON /ELLIP/  AAXIS,BAXIS,ABQAB
      COMMON /DUMB3/  IMXB,JMXB,IMXB1,JMXB1,IMXB2,JMXB2
      COMMON /FRANK/  IRANK,ISTAR,ISTOP,JSTAR,JSTOP,IHALO
      COMMON /INDX/   IRB,IRE,NDB,NDE
      COMMON /EGTH/   DELS,DELT,G,COR
      COMMON /FLWCPT/ NSQRS,NSQRW,NSQRWC,NPSS,NCUT
      COMMON /CHNL/   IPT0(2,5),JPT0(2,5),IPTL(2,5),JPTL(2,5),ENTEXT(5)
      COMMON /CHNARA/ ARESQ0(5),ARESQL(5)
C      DIMENSION DUMMY(800)
C        COMPUTING RADII OF CONCENTRIC CIRCLES IN ST MILES
      DO 100 I=1,IMXB
C      X=I-1-IRB
      X=I-1+ISTAR-1-IRB
      RFEET1=EXP(X*DELA)
      GRID=RMOUTH*RFEET1*5280.
      Z1=1./(RFEET1*RFEET1)
      ELPCT(I)=(1.+ABQAB*Z1)*GRID
      ELPDT(I)=(1.-ABQAB*Z1)*GRID
 100  CONTINUE
C
C        COMPUTING AZIMUTHS FOR EACH RAY FROM STORM CENTER
      DO 130 J=1,JMXB
C      X=J-1-NDB
      X=J-1+JSTAR-1-NDB
      ANGL=X*DELA
C        AZIMUTHS ON MOMENTUM POINTS
      COST(J)=COS(ANGL)
      SINT(J)=SIN(ANGL)
      SINT2(J)=SINT(J)*SINT(J)
C        AZIMUTHS ON HEIGHT POINTS
      ANGH=ANGL+.5*DELA
      COSL(J)=COS(ANGH)
      SINL(J)=SIN(ANGH)
      SINL2(J)=SINL(J)*SINL(J)
 130  CONTINUE
C
C        COMPUTING RADIAL DISTANCES TO HEIGHT POINTS, IN FEET
C        DETERMINING HEIGHT POINT JACOBIANS FOR CONTTY EQUATION IN FEET
      DO 150 I=1,IMXB
C      X=I-1-IRB
      X=I-1+ISTAR-1-IRB
      X=X+0.5
      RFEET1=EXP(X*DELA)
      GRID=RMOUTH*RFEET1*5280.
C      GRID2=1./(RMOUTH*RFEET1*5280.)**2
      Z1=1./(RFEET1*RFEET1)
      ELPCL(I)=(1.+ABQAB*Z1)*GRID
      ELPDL(I)=(1.-ABQAB*Z1)*GRID
      ELPCL2(I)=ELPCL(I)*ELPCL(I)
      ELPDL2(I)=ELPDL(I)*ELPDL(I)
 150  CONTINUE
C        APPROX. THE AREAS OF THE ENTRANCE AND EXIT SQUARES OF CHANNELS.
      IF (NPSS.NE.0) THEN
      DO 310 NPASS=1,NPSS
      Z1=0.
      Z2=0.
      ARESQ0(NPASS)=0.
      ARESQL(NPASS)=0.
      DO 300 K=1,2
      I=IPT0(K,NPASS)
      J=JPT0(K,NPASS)
      II=IPTL(K,NPASS)
      JJ=JPTL(K,NPASS)
      IF (I.LE.0 .OR. J.LE.0.OR.I.GT.IMXB.OR.J.GT.JMXB) CYCLE
      IF (II.LE.0 .OR. JJ.LE.0.OR.II.GT.IMXB.OR.JJ.GT.JMXB) CYCLE
      Z1=Z1+ELPDL2(I)+(ELPCL2(I)-ELPDL2(I))*SINL2(J)
      Z2=Z2+ELPDL2(II)+(ELPCL2(II)-ELPDL2(II))*SINL2(JJ)
 300  CONTINUE
      ARESQ0(NPASS)=.5*Z1*DELA*DELA
      ARESQL(NPASS)=.5*Z2*DELA*DELA
 310  CONTINUE
        ENDIF
C
C        PRINT OUT X-DISTANCES ALONG Q=0, IN MILES
C      WRITE(*,190)
C      DO 140 I=1,IMXB
C      DUMMY(I)=ELPCT(I)/5280.
C 140  CONTINUE
C      WRITE(*,170)(DUMMY(I),I=1,IMXB)
C        PRINT OUT Y-DISTANCES ALONG P=0, IN MILES
C      WRITE(*,210)
C      DO 135 J=1,JMXB1
C      X=J-1-NDB
C      ANGL=ELPDT(1)*SIN(X*DELA)/5280.
C 135  DUMMY(J)=ANGL
C      WRITE(*,170)(DUMMY(J),J=1,JMXB1)
 160  FORMAT (10X,' RADIUS OF CIRCLES FROM ORIGIN, IN MILES')
 170  FORMAT(F7.1,19F6.1)
 180  FORMAT(3X,20I6)
 190  FORMAT(10X,' GRID DISTANCES ALONG X-AXIS (ALONG Q=0)')
 200  FORMAT(20F6.2)
 210  FORMAT(10X,' GRID DISTANCES ALONG Y-AXIS (ALONG P=0)')
      RETURN
      END
