      SUBROUTINE STERON
C        JELESNIANSKI/CHEN   OCT 1989    TDL   IBM 360/195
C
C        PURPOSE
C           THIS SUBROUTINE CHANGES HOURLY STORM TRACK
C           POSITIONS (LATITUDE AND LONGITUDE) TO POSITIONS ON (X,Y)
C           PLANE. RECORDS HOURLY SPEEDS AND DIRECTIONS IN (X,Y) PLANE.
C
C        DATA SET USE
C           NONE
C
C        VARIABLES
C  XLAT( ) YLONG( ) = LAT/LONG OF HOURLY STORM POSITIONS
C       X(  ) Y(  ) = COMPONENTS OF HOURLY STORM POSITIONS
C         ALTO ALNO = LAT/LONG OF BASIN ORIGIN
C              PHI  = SLANT FROM N/S AXIS TO Y-AXIS;E.G., 'AZMTH+270'
C              ERAD = RADIUS OF EARTH (SPHERICAL)
C             FTPNM = NO OF FEET IN A NAUTICAL MILE
C     XMOUTH YMOUTH = MOUTH COORDINATES IN X-Y PLANE
C
C        GENERAL COMMENTS
C
      PARAMETER (NT_=999)
      COMMON /STRMPS/ X(NT_),Y(NT_),PT(NT_),R(NT_),DIR(NT_),SP(NT_)
      COMMON /SPLN/   ALT(15),ALN(15),AX(15),AY(15),RL(15),ANGD(15),
     1                PDUM(15),RT(15),XLAT(NT_),YLONG(NT_),RLNGTH
      COMMON /BSN/    PHI,ALTO,ALNO,PHI1,ALT1,ALN1,ALT1C
      COMMON /EGTH/   DELS,DELT,G,COR
      COMMON /ORIGN/  XMOUTH,YMOUTH
C STIME interferes with C code, so switched to STIME2
      COMMON /STIME2/  ISTM,JHR,ITMADV,NHRAD,IBGNT,ITEND
      DATA ERAD/3437.87/,FTPNM/6080.21/
      COMMON /TRKHRS/ ITRACKLEN
C
C        SET LAT/LONG AND SLANT IN RADIANS; COMPLEMENT LAT BY 90 DEG
      SO=SIN(ALT1C)
      CO=COS(ALT1C)
      ERAD2=2.*ERAD
      CO2=2.*CO
C        TRANSFORM LAT/LONG TO CARTESIAN (X,Y)
      DO 120 I=1,iTrackLen
      ALTII=1.74532925199433E-2*(90.-XLAT(I))
      ALNII=1.74532925199433E-2*YLONG(I)
      DLAT=ALT1C-ALTII
      DLAT2=.5*DLAT
      DLON=ALN1-ALNII
      DLON2=.5*DLON
      S2=SIN(DLON2)**2
      S=SIN(DLAT2)**2+SO*SIN(ALTII)*S2
      RLZ=ERAD2*SQRT(S/(1.-S))
  110 AN=SIN(ALTII)*SIN(DLON)
      AD=SIN(DLAT)+CO2*SIN(ALTII)*S2
      IF (AN**2+AD**2.LT.1.E-10) THEN
      ANG=3.14159265358979323846-PHI1
         ELSE
      ANG=3.14159265358979323846+ATAN2(-AN,-AD)-PHI1
         ENDIF
      X(I)=(RLZ*SIN(ANG))*FTPNM/5280.+XMOUTH
      Y(I)=(RLZ*COS(ANG))*FTPNM/5280.+YMOUTH
C
      IF (I.NE.1) THEN
        SP(I-1)=SQRT((X(I-1)-X(I))**2+(Y(I-1)-Y(I))**2)
        IF (SP(I-1).LT.1.E-5) THEN
        DIR(I-1)=3.14159265358979323846
        ELSE
        DIR(I-1)=3.14159265358979323846+ATAN2(Y(I-1)-Y(I),X(I-1)-X(I))
        ENDIF
c       WRITE(*,*) X(I),Y(I),SP(I-1),DIR(I-1)/1.74532925E-2
      ENDIF
  120 CONTINUE
      SP(iTrackLen)=SP(iTrackLen-1)
      DIR(iTrackLen)=DIR(iTrackLen-1)
C
C      CALCULATE THE MINIMUM DISTANCE TO MOUTH POINT
       RLNGTH=SQRT((X(JHR)-XMOUTH)**2+(Y(JHR)-YMOUTH)**2)
C
      RETURN
       END
