      SUBROUTINE TMSTPC1(HHB,FPASS,RESTART)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C THIS SUBROUTINE CALLS ALL THE FORTRAN SUBROUTINES WHICH ARE NEEDED TO
C DO ONE TIME STEP.
C
C ORIGINALLY THIS WAS DONE IN CMPUTE BETWEEN 100 AND 999.
C THE CODE IS THE SAME EXCEPT CUT AND PASTED HERE.
C
C THIS ALSO RETURNS TO C THE VARIOUS VARIABLES NEEDED SO THAT
C IT CAN UPDATE THE GRAPHICS.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      include 'parm.for'
      REAL HHB(M_,N_)
      INTEGER*2 FPASS
      INTEGER*2 RESTART

      COMMON /GPRT2/  EBSN1,EBSN2
      CHARACTER*1  EBSN1,EBSN2
      COMMON /FFTH/   ITIME, MHALT
      COMMON /FLWCPT/ NSQRS,NSQRW,NSQRWC,NPSS,NCUT
      COMMON /OPTS/   NOFLD,NOF1D
      CHARACTER*1     NOFLD,NOF1D
      COMMON /PRHSY/  IPRHR,JUMPR,IPRT
      COMMON /PRTSV/  IPRTSV,IPRTAD
C STIME interferes with C code, so switched to STIME2
      COMMON /STIME2/  ISTM,JHR,ITMADV,NHRAD,IBGNT,ITEND
      COMMON /DELTH/  NDLTHR,NDLTH2,DLTHR,DLTH2
      COMMON /CESAV/  IPN(120),IPL(120),KHSPT
      COMMON /GPRT1/  DOLLAR,EBSN
      CHARACTER*1 EBSN
      CHARACTER*2 DOLLAR
      COMMON /EGTH/   DELS,DELT,G,COR
      COMMON /WTEMP/  YDELP,ZDELP,PNN,YC24,ZC24
      COMMON /STRMSB/ C1,C2,C21,C22,AX,AY,PTENCY,RTENCY
      COMMON /POLAR/  DEGREE,RMOUTH,AZMTH,DELA
      COMMON /DUMB3/  IMXB,JMXB,IMXB1,JMXB1,IMXB2,JMXB2
      COMMON /SMTH/   ISMTH
      COMMON /GPRT/   STA
      COMMON /TMEREL/ TREAL
      CHARACTER*16  STA

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C     ADDED FOR WAVE MODEL
C     4/2017 D.Y.
      REAL TMN,TWD,TIO,TWV,DTM,DTI,DTW
#ifdef INCLUDE_WAVE
      IF (WAVE.EQ.1) THEN
        IF(.NOT. HTSTRT)CALL WVSTEP(TREAL)
      ENDIF
#endif
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

C CODE TO IMPLEMENT ONE TIME STEP..
  100 INCSM=20
      IF (EBSN1.EQ.'+'.OR.EBSN1.EQ.'=') INCSM=1
      IF (EBSN1.EQ.'!'.OR.EBSN1.EQ.'#') INCSM=5
      IF (EBSN1.EQ.'@'.OR.EBSN1.EQ.'%') INCSM=10
      IF (EBSN1.EQ.'&') INCSM=20
      IF (EBSN1.EQ.'^'.OR.EBSN1.EQ.'*') INCSM=30
      ISMPT2G=1
      IF (EBSN1.EQ.'+') ISMPT2G=0
      IF (EBSN1.EQ.'&') ISMPT2G=0    
      IF (EBSN1.EQ.'#') ISMPT2G=0
      IF (EBSN1.EQ.'%') ISMPT2G=0
      IF (EBSN1.EQ.'*') ISMPT2G=0
      CALL TTIMER
      xtime=itime
c
c  continuity
c
C      CALL CPU_TIME(ELAPSE)
C      WRITE (*,*) "5a", ELAPSE
C      CALL TFLUSH
c
c     READ IN HOT START WATER LEVEL AND TRANSPORTATION D.Y 1/2018
      IF (HTSTRT)CALL HBUV_HS
      CALL CONTTY
C      CALL CPU_TIME(ELAPSE)
C      WRITE (*,*) "5b", ELAPSE
C      CALL TFLUSH
c
C       NO CORNER SMOOTHING for PNB BASIN
c

      IF (ISMPT2G.NE.0.AND.ITIME.GT.5.AND.INCSM.NE.1) CALL SMPT2G
c
c
c
      CALL BDRYHT
      IF (NPSS.NE.0) CALL CHANNL
      IF (NSQRWC.NE.0.and.nof1d.ne.'+') CALL FLW1DM_C
      RETURN
      END
