      SUBROUTINE TMSTPM(IITIME,MMHALT,DDELT,XXLT,XXLG,YYDELP,YYC24,
     1WSPEED,WDIRCT,DMCLOCK,RESTART)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      include 'parm.for'
      INTEGER*2 RESTART

      COMMON /FFTH/   ITIME, MHALT
      COMMON /EGTH/   DELS,DELT,G,COR
      COMMON /WTEMP/  YDELP,ZDELP,PNN,YC24,ZC24
      COMMON /STRMSB/ C1,C2,C21,C22,AX,AY,PTENCY,RTENCY
      COMMON /POLAR/  DEGREE,RMOUTH,AZMTH,DELA
      COMMON /TMEREL/ TREAL
c
c  momentum equation
c
C      CALL CPU_TIME(ELAPSE)
C      WRITE (*,*) "5j", ELAPSE
C      CALL TFLUSH
      CALL MOMNTM
#ifdef INCLUDE_WAVE
      IF (WAVE.EQ.1) THEN
        IF(HTSTRT)CALL WVSTEP(TREAL)
      ENDIF
#endif
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
c FOR HOT START, OUTPUT HB,UB,VB AND STORM POSITION/TIME INFO EVERY HALF HOUR
c 1/2018 D.Y
c      print *, ITIME
c      print *, ITMADV
c      print *, TREAL
c      print *, AX
c      print *, AY
c      print *, NHRAD
      IF (RESTART .EQ. 1) THEN
        IF (MOD(INT(TREAL),3600).EQ. 0)THEN
          print *, treal
          CALL RSTOUT(DMCLOCK)
        ENDIF
      ENDIF
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      CALL STMVAL
c
C GRAPHICS
C
c    include 'cmpgr2.for'
C
C END OF COMPUTE FOR ONE TIME STEP

C ARTHUR: PROCEDURE FOR CS.
C NOTE: ITMADV HAS BEEN ADVANCED FOR NEXT HOUR IN CALL TO STMVAL
C      IF (FLAG.EQ.1) THEN
C        CALL WAV
C      ENDIF

C END CODE FOR ONE TIME STEP

C CODE TO RETURN TO C-CODE THE REST OF THE VALUES IT NEEDS.
      IITIME = ITIME
      MMHALT = MHALT
      DDELT = DELT
      YYDELP = YDELP
      YYC24 = YC24
      XA=(C1+AX)/5280.
      YA=(C2+AY)/5280.
      CALL XY2LLX(XA,YA,XXLT,XXLG)
      WSPEED=C21
C Direction is 0 for north. (I think this is meteorological direction)
C WDIRCT is returned in degrees.
      WDIRCT=(AZMTH-(C22)*180./3.14159265358979323846)
      RETURN
      END
