      PARAMETER (IDIM=485,JDIM=780,KDIM=8)
C      PARAMETER (IDIM=480,JDIM=523,KDIM=8)
c      PARAMETER (IDIM=333,JDIM=1332,KDIM=8)
C      CHARACTER*80 FNAME,FGRID,FINPUT,FOUT,FINI,FBTH
C      COMMON/CPARM/FNAME,FGRID,FINPUT,FOUT,FINI,FBTH
C!      COMMON/TPARM/DT,DTWIND,DTT,NHRS,NDTT
      COMMON/TPARM/DT,DTWIND,DTT,NDTT
      COMMON/BISC/G,VK,RHOAIR,RHOH2O,GAMMA,CBF,EPS1,PI,WTPI,NDIR
      COMMON/CONV/R2D,S2H,GTPI,COEFF0,COEFF,FAC2
C!      COMMON/SPAV/AC1,AC2,AC3,AC4,AC5,AC6
      COMMON/WNDD/PA,CALP,CBET,CDS,SPM,DELT,IWCNT,IRCNT
C!      COMMON/INPT/IM,JM,IMM1,JMM1,NSTEPS
      COMMON/INPT/IM,JM,IMM1,JMM1
      COMMON/DINPT/DS,DMIN
C!      COMMON/INPV/D(IDIM,JDIM),DPTH(IDIM,JDIM),S(IDIM,JDIM)
C!     1            ,S1(IDIM,JDIM),S2(IDIM,JDIM) !testing: separate windsea/swell wave height
      COMMON/INPV/D(IDIM,JDIM),DPTH(IDIM,JDIM),S(IDIM,JDIM)
      COMMON /WVDN/ EWW(IDIM,JDIM,KDIM),ESW(IDIM,JDIM,KDIM),
     1            FRW(IDIM,JDIM,KDIM),FRS(IDIM,JDIM,KDIM),
     2            CPW(IDIM,JDIM,KDIM),CGW(IDIM,JDIM,KDIM),
     3            WNM(IDIM,JDIM,KDIM),VFW(KDIM)
      COMMON/BSNP/GSQRT(IDIM,JDIM),DPDX(IDIM,JDIM),DPDY(IDIM,JDIM),
     1            DQDX(IDIM,JDIM),DQDY(IDIM,JDIM),DS1(IDIM,JDIM)
      COMMON/DIRP/ADIR(KDIM),ECOS(KDIM),ESIN(KDIM),
     1            COSM2(KDIM),SINM2(KDIM),SINCO(KDIM)
