#-------------------------------------------------------------------------------
# .bash_profile                                          Last Change: 2024-06-17
#-------------------------------------------------------------------------------

#----- Source .bashrc for aliases and functions -----
if [ -f "${HOME}/.bashrc" ] ; then
  source "${HOME}/.bashrc"
fi

#----- Set aliases for the interactive session -----
alias vi='vim -p'       # Load a vim tab per file
alias ls='ls -v --color=auto -F --time-style=+"%Y-%m-%d %H:%M:%S"'
alias gitdiff='git difftool -y --extcmd=/usr/bin/diff'
alias gitrevert='git checkout --'

#----- Set the PATH for the interactive session -----
if [ -d "$HOME/docs/bin" ] ; then export PATH="$HOME/docs/bin:$PATH" ; fi
export OrigPath=".:$PATH"
alias setOrig='export PATH=$OrigPath'
nPath=$OrigPath
if [ -d "$HOME/12.3.0/mingw32/bin" ] ; then
  export Ming1230Path=".:$HOME/12.3.0/mingw32/bin:$PATH"
  alias setMing1230='export PATH=$Ming1230Path'
  nPath=$Ming1230Path
fi
if [ -d "$HOME/mingw32/bin" ] ; then
  export Ming450Path=".:$HOME/mingw32/bin:$PATH"
  alias setMing450='export PATH=$Ming450Path'
  nPath=$Ming450Path
fi
export PATH=$nPath

#-------------------------------------------------------------------------------
# The PS1 variable adjusts the prompt.  In this case we first adjust the title
# with the current path, and then update the path.  PS1 uses the following
# variables: \u == User, \h == Host, \w == path of current directory,
#    \t == time, \[ == start escape string, \] == end escape string
#
# For reference the original PS1 is:
# PS1="\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[35m\]$MSYSTEM\[\e[0m\] \[\e[33m\]\w\[\e[0m\]\n\$ "
#-------------------------------------------------------------------------------
Title='\e]0;'     ; TitleEnd='\a'
green='\e[0;32m'  ; GREEN='\e[1;32m'
yellow='\e[0;33m' ; YELLOW='\e[1;33m'
purple='\e[0;35m' ; PURPLE='\e[1;35m'
cyan='\e[0;36m'   ; CYAN='\e[1;36m'
NC='\e[0m'
PS1="\[${Title}\w${TitleEnd}\]\[${green}\]\u@\h \[${purple}\]$MSYSTEM \[${cyan}\]\t \[${yellow}\]\w\[${NC}\]\n\$ "

if [ -e $HOME/PATH ] ; then echo "Welcome to: $(cat $HOME/PATH)" ; echo "" ; fi
