"-------------------------------------------------------------------------------
" .vimrc                                                 Last Change: 2026-09-28
"-------------------------------------------------------------------------------
set modeline            " Allow files to have modelines (vim control lines)
set modelines=4         " top and bottom lines to check for modeline
set history=1000
set nocompatible        " Disable vi compatibility (emulation of old bugs)
set confirm             " Prompt when exiting from an unsaved file
set laststatus=2        " Use 2 lines for the status bar
set mouse-=a            " Disable mouse clicks to change cursor position
                        " Mouse clicks interferes with mouse highlight/copy
set noerrorbells vb t_vb=  " no annoying sound on errors
set title               " Have VI update the title
set ruler               " Display the row,col % in status-bar
set backspace=indent,eol,start " Fix backspace in insert mode
syntax on              " Allow vim to override your color pref
:colorscheme industry